#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H


#define OBJ_EVENT_GFX_BERRY_TREE                  0
#define OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES     1
#define OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES      2

#define OBJ_EVENT_GFX_BALL_CUSHION                3
#define OBJ_EVENT_GFX_DIAMOND_CUSHION             4
#define OBJ_EVENT_GFX_FIRE_CUSHION                5
#define OBJ_EVENT_GFX_GRASS_CUSHION               6
#define OBJ_EVENT_GFX_KISS_CUSHION                7
#define OBJ_EVENT_GFX_PIKA_CUSHION                8
#define OBJ_EVENT_GFX_ROUND_CUSHION               9
#define OBJ_EVENT_GFX_SPIN_CUSHION               10
#define OBJ_EVENT_GFX_WATER_CUSHION              11
#define OBJ_EVENT_GFX_ZIGZAG_CUSHION             12

#define OBJ_EVENT_GFX_AZURILL_DOLL               13
#define OBJ_EVENT_GFX_BALTOY_DOLL                14
#define OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL         15
#define OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL         16
#define OBJ_EVENT_GFX_BIG_LAPRAS_DOLL            17
#define OBJ_EVENT_GFX_BIG_REGICE_DOLL            18
#define OBJ_EVENT_GFX_BIG_REGIROCK_DOLL          19
#define OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL         20
#define OBJ_EVENT_GFX_BIG_RHYDON_DOLL            21
#define OBJ_EVENT_GFX_BIG_SNORLAX_DOLL           22
#define OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL          23
#define OBJ_EVENT_GFX_BIG_WAILMER_DOLL           24
#define OBJ_EVENT_GFX_CHIKORITA_DOLL             25
#define OBJ_EVENT_GFX_CLEFAIRY_DOLL              26
#define OBJ_EVENT_GFX_CYNDAQUIL_DOLL             27
#define OBJ_EVENT_GFX_DITTO_DOLL                 28
#define OBJ_EVENT_GFX_DUSKULL_DOLL               29
#define OBJ_EVENT_GFX_GULPIN_DOLL                30
#define OBJ_EVENT_GFX_JIGGLYPUFF_DOLL            31
#define OBJ_EVENT_GFX_KECLEON_DOLL               32
#define OBJ_EVENT_GFX_LOTAD_DOLL                 33
#define OBJ_EVENT_GFX_MAGNEMITE_DOLL             34
#define OBJ_EVENT_GFX_MARILL_DOLL                35
#define OBJ_EVENT_GFX_MEOWTH_DOLL                36
#define OBJ_EVENT_GFX_MEW_DOLL                   37
#define OBJ_EVENT_GFX_MUDKIP_DOLL                38
#define OBJ_EVENT_GFX_NATU_DOLL                  39
#define OBJ_EVENT_GFX_PICHU_DOLL                 40
#define OBJ_EVENT_GFX_PIKACHU_DOLL               41
#define OBJ_EVENT_GFX_PORYGON2_DOLL              42
#define OBJ_EVENT_GFX_SEEDOT_DOLL                43
#define OBJ_EVENT_GFX_SKITTY_DOLL                44
#define OBJ_EVENT_GFX_SMOOCHUM_DOLL              45
#define OBJ_EVENT_GFX_SQUIRTLE_DOLL              46
#define OBJ_EVENT_GFX_SWABLU_DOLL                47
#define OBJ_EVENT_GFX_TOGEPI_DOLL                48
#define OBJ_EVENT_GFX_TORCHIC_DOLL               49
#define OBJ_EVENT_GFX_TOTODILE_DOLL              50
#define OBJ_EVENT_GFX_TREECKO_DOLL               51
#define OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL        52
#define OBJ_EVENT_GFX_WOOPER_DOLL                53
#define OBJ_EVENT_GFX_WYNAUT_DOLL                54

#define OBJ_EVENT_GFX_BIRCHS_BAG                 55
#define OBJ_EVENT_GFX_BIRTH_ISLAND_STONE         56
#define OBJ_EVENT_GFX_BREAKABLE_ROCK             57
#define OBJ_EVENT_GFX_CABLE_CAR                  58
#define OBJ_EVENT_GFX_CLIPBOARD                  59
#define OBJ_EVENT_GFX_CUTTABLE_TREE              60
#define OBJ_EVENT_GFX_FOSSIL                     61
#define OBJ_EVENT_GFX_GYM_SIGN                   62
#define OBJ_EVENT_GFX_ITEM_BALL                  63
#define OBJ_EVENT_GFX_MOVING_BOX                 64
#define OBJ_EVENT_GFX_MR_BRINEYS_BOAT            65
#define OBJ_EVENT_GFX_OLD_AMBER                  66
#define OBJ_EVENT_GFX_POKEDEX                    67
#define OBJ_EVENT_GFX_PUSHABLE_BOULDER           68
#define OBJ_EVENT_GFX_RUBY                       69
#define OBJ_EVENT_GFX_SAPPHIRE                   70
#define OBJ_EVENT_GFX_SEAGALLOP                  71
#define OBJ_EVENT_GFX_SIGN                       72
#define OBJ_EVENT_GFX_SS_ANNE                    73
#define OBJ_EVENT_GFX_SS_TIDAL                   74
#define OBJ_EVENT_GFX_STATUE                     75
#define OBJ_EVENT_GFX_SUBMARINE_SHADOW           76
#define OBJ_EVENT_GFX_TM_BALL                    77
#define OBJ_EVENT_GFX_TOWN_MAP                   78
#define OBJ_EVENT_GFX_TRUCK                      79
#define OBJ_EVENT_GFX_WOODEN_SIGN                80

#define OBJ_EVENT_GFX_ARTICUNO                   81 
#define OBJ_EVENT_GFX_AZUMARILL                  82 
#define OBJ_EVENT_GFX_AZURILL                    83 
#define OBJ_EVENT_GFX_CELEBI                     84 
#define OBJ_EVENT_GFX_CHANSEY                    85 
#define OBJ_EVENT_GFX_CLEFAIRY                   86 
#define OBJ_EVENT_GFX_CUBONE                     87 
#define OBJ_EVENT_GFX_DEOXYS_ATTACK              88 
#define OBJ_EVENT_GFX_DEOXYS_DEFENSE             89 
#define OBJ_EVENT_GFX_DEOXYS_NORMAL              90 
#define OBJ_EVENT_GFX_DEOXYS_SPEED               91 
#define OBJ_EVENT_GFX_DODUO                      92 
#define OBJ_EVENT_GFX_DUSCLOPS                   93 
#define OBJ_EVENT_GFX_ENEMY_ZIGZAGOON            94 
#define OBJ_EVENT_GFX_ENTEI                      95 
#define OBJ_EVENT_GFX_FEAROW                     96 
#define OBJ_EVENT_GFX_GROUDON_ASLEEP             97 
#define OBJ_EVENT_GFX_GROUDON_FRONT              98 
#define OBJ_EVENT_GFX_GROUDON_SIDE               99 
#define OBJ_EVENT_GFX_HOOH                      100
#define OBJ_EVENT_GFX_JIGGLYPUFF                101
#define OBJ_EVENT_GFX_KANGASKHAN                102
#define OBJ_EVENT_GFX_KABUTO                    103
#define OBJ_EVENT_GFX_KECLEON                   104
#define OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW     105
#define OBJ_EVENT_GFX_KIRLIA                    106
#define OBJ_EVENT_GFX_KYOGRE_ASLEEP             107
#define OBJ_EVENT_GFX_KYOGRE_FRONT              108
#define OBJ_EVENT_GFX_KYOGRE_SIDE               109
#define OBJ_EVENT_GFX_LAPRAS                    110
#define OBJ_EVENT_GFX_LATIAS                    111
#define OBJ_EVENT_GFX_LATIOS                    112
#define OBJ_EVENT_GFX_LUGIA                     113
#define OBJ_EVENT_GFX_MACHOKE                   114
#define OBJ_EVENT_GFX_MACHOP                    115
#define OBJ_EVENT_GFX_MEOWTH                    116
#define OBJ_EVENT_GFX_MEW                       117
#define OBJ_EVENT_GFX_MEWTWO                    118
#define OBJ_EVENT_GFX_MOLTRES                   119
#define OBJ_EVENT_GFX_NIDORAN_F                 120
#define OBJ_EVENT_GFX_NIDORAN_M                 121
#define OBJ_EVENT_GFX_NIDORINO                  122
#define OBJ_EVENT_GFX_OMANYTE                   123
#define OBJ_EVENT_GFX_PIDGEOT                   124
#define OBJ_EVENT_GFX_PIDGEY                    125
#define OBJ_EVENT_GFX_PIKACHU                   126
#define OBJ_EVENT_GFX_POLIWRATH                 127
#define OBJ_EVENT_GFX_POOCHYENA                 128
#define OBJ_EVENT_GFX_PSYDUCK                   129
#define OBJ_EVENT_GFX_RAIKOU                    130
#define OBJ_EVENT_GFX_RAYQUAZA                  131
#define OBJ_EVENT_GFX_RAYQUAZA_STILL            132
#define OBJ_EVENT_GFX_REGICE                    133
#define OBJ_EVENT_GFX_REGIROCK                  134
#define OBJ_EVENT_GFX_REGISTEEL                 135
#define OBJ_EVENT_GFX_SEEL                      136
#define OBJ_EVENT_GFX_SKITTY                    137
#define OBJ_EVENT_GFX_SLOWBRO                   138
#define OBJ_EVENT_GFX_SLOWPOKE                  139
#define OBJ_EVENT_GFX_SNORLAX                   140
#define OBJ_EVENT_GFX_SPEAROW                   141
#define OBJ_EVENT_GFX_SUDOWOODO                 142
#define OBJ_EVENT_GFX_SUICUNE                   143
#define OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX     144
#define OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY      145
#define OBJ_EVENT_GFX_VOLTORB                   146
#define OBJ_EVENT_GFX_WIGGLYTUFF                147
#define OBJ_EVENT_GFX_WINGULL                   148
#define OBJ_EVENT_GFX_ZAPDOS                    149
#define OBJ_EVENT_GFX_ZIGZAGOON                 150

#define OBJ_EVENT_GFX_ARTIST                    151
#define OBJ_EVENT_GFX_BALDING_MAN_1             152
#define OBJ_EVENT_GFX_BALDING_MAN_2             153
#define OBJ_EVENT_GFX_BOY_1                     154
#define OBJ_EVENT_GFX_BOY_2                     155
#define OBJ_EVENT_GFX_BOY_3                     156
#define OBJ_EVENT_GFX_BOY_4                     157
#define OBJ_EVENT_GFX_CHEF                      158
#define OBJ_EVENT_GFX_COOK                      159
#define OBJ_EVENT_GFX_DEVON_EMPLOYEE            160
#define OBJ_EVENT_GFX_FAT_MAN_1                 161
#define OBJ_EVENT_GFX_FAT_MAN_2                 162
#define OBJ_EVENT_GFX_FAT_MAN_3                 163
#define OBJ_EVENT_GFX_GAMEBOY_KID_1             164
#define OBJ_EVENT_GFX_GAMEBOY_KID_2             165
#define OBJ_EVENT_GFX_GAMEBOY_KID_3             166
#define OBJ_EVENT_GFX_GIRL_1                    167
#define OBJ_EVENT_GFX_GIRL_2                    168
#define OBJ_EVENT_GFX_GIRL_3                    169
#define OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN     170
#define OBJ_EVENT_GFX_LITTLE_BOY_1              171
#define OBJ_EVENT_GFX_LITTLE_BOY_2              172
#define OBJ_EVENT_GFX_LITTLE_BOY_3              173
#define OBJ_EVENT_GFX_LITTLE_BOY_4              174
#define OBJ_EVENT_GFX_LITTLE_GIRL_1             175
#define OBJ_EVENT_GFX_LITTLE_GIRL_2             176
#define OBJ_EVENT_GFX_MAN_1                     177
#define OBJ_EVENT_GFX_MAN_2                     178
#define OBJ_EVENT_GFX_MAN_3                     179
#define OBJ_EVENT_GFX_MAN_4                     180
#define OBJ_EVENT_GFX_MAN_5                     181
#define OBJ_EVENT_GFX_MAN_6                     182
#define OBJ_EVENT_GFX_MAN_7                     183
#define OBJ_EVENT_GFX_MAN_8                     184
#define OBJ_EVENT_GFX_OLD_MAN_1                 185
#define OBJ_EVENT_GFX_OLD_MAN_2                 186
#define OBJ_EVENT_GFX_OLD_MAN_3                 187
#define OBJ_EVENT_GFX_OLD_MAN_4                 188
#define OBJ_EVENT_GFX_OLD_MAN_5                 189
#define OBJ_EVENT_GFX_OLD_MAN_LYING_DOWN        190
#define OBJ_EVENT_GFX_OLD_WOMAN_1               191
#define OBJ_EVENT_GFX_OLD_WOMAN_2               192
#define OBJ_EVENT_GFX_OLD_WOMAN_3               193
#define OBJ_EVENT_GFX_OLD_WOMAN_4               194
#define OBJ_EVENT_GFX_SITTING_BOY               195
#define OBJ_EVENT_GFX_WOMAN_1                   196
#define OBJ_EVENT_GFX_WOMAN_2                   197
#define OBJ_EVENT_GFX_WOMAN_3                   198
#define OBJ_EVENT_GFX_WOMAN_4                   199
#define OBJ_EVENT_GFX_WOMAN_5                   200
#define OBJ_EVENT_GFX_WOMAN_6                   201
#define OBJ_EVENT_GFX_WOMAN_7                   202
#define OBJ_EVENT_GFX_WOMAN_8                   203
#define OBJ_EVENT_GFX_WOMAN_9                   204
#define OBJ_EVENT_GFX_WOMAN_10                  205
#define OBJ_EVENT_GFX_WOMAN_11                  206
#define OBJ_EVENT_GFX_WOMAN_12                  207
#define OBJ_EVENT_GFX_WOMAN_13                  208
#define OBJ_EVENT_GFX_WOMAN_14                  209
#define OBJ_EVENT_GFX_WORKER_F                  210
#define OBJ_EVENT_GFX_WORKER_M_1                211
#define OBJ_EVENT_GFX_WORKER_M_2                212

#define OBJ_EVENT_GFX_YAHOO_HOST                213
#define OBJ_EVENT_GFX_YAHOO_LITTLE_GIRL         214
#define OBJ_EVENT_GFX_YAHOO_RECEPTIONIST_BROWN  215
#define OBJ_EVENT_GFX_YAHOO_RECEPTIONIST_SILVER 216
#define OBJ_EVENT_GFX_YAHOO_SCOUT_F             217
#define OBJ_EVENT_GFX_YAHOO_SCOUT_M             218

#define OBJ_EVENT_GFX_ACE_TRAINER_F_DPPT_SNOW   219
#define OBJ_EVENT_GFX_ACE_TRAINER_F_HGSS        220
#define OBJ_EVENT_GFX_ACE_TRAINER_M_DPPT        221
#define OBJ_EVENT_GFX_ACE_TRAINER_M_DPPT_SNOW   222
#define OBJ_EVENT_GFX_ACE_TRAINER_M_HGSS        223
#define OBJ_EVENT_GFX_AQUA_MEMBER_F             224
#define OBJ_EVENT_GFX_AQUA_MEMBER_M             225
#define OBJ_EVENT_GFX_AROMA_LADY_FRLG           226
#define OBJ_EVENT_GFX_BATTLE_GIRL_1             227
#define OBJ_EVENT_GFX_BATTLE_GIRL_HGSS          228
#define OBJ_EVENT_GFX_BATTLE_GIRL_RSE           229
#define OBJ_EVENT_GFX_BEAUTY_1                  230
#define OBJ_EVENT_GFX_BEAUTY_2                  231
#define OBJ_EVENT_GFX_BEAUTY_HGSS               232
#define OBJ_EVENT_GFX_BEAUTY_RSE                233
#define OBJ_EVENT_GFX_BIKER_1                   234
#define OBJ_EVENT_GFX_BIKER_FRLG_OFF_BIKE       235
#define OBJ_EVENT_GFX_BIKER_HGSS                236
#define OBJ_EVENT_GFX_BIRD_KEEPER_FRLG          237
#define OBJ_EVENT_GFX_BIRD_KEEPER_RSE           238
#define OBJ_EVENT_GFX_BLACK_BELT_1              239
#define OBJ_EVENT_GFX_BLACK_BELT_2              240
#define OBJ_EVENT_GFX_BLACK_BELT_FRLG           241
#define OBJ_EVENT_GFX_BLACK_BELT_HGSS           242
#define OBJ_EVENT_GFX_BREEDER_F_FRLG            243
#define OBJ_EVENT_GFX_BREEDER_F_HGSS            244
#define OBJ_EVENT_GFX_BREEDER_F_RSE             245
#define OBJ_EVENT_GFX_BREEDER_M_RSE             246
#define OBJ_EVENT_GFX_BUG_CATCHER_1             247
#define OBJ_EVENT_GFX_BUG_CATCHER_2             248
#define OBJ_EVENT_GFX_BUG_CATCHER_FRLG          249
#define OBJ_EVENT_GFX_BUG_CATCHER_HGSS          250
#define OBJ_EVENT_GFX_BUG_MANIAC_RSE            251
#define OBJ_EVENT_GFX_BURGLAR_FRLG              252
#define OBJ_EVENT_GFX_BURGLAR_HGSS              253
#define OBJ_EVENT_GFX_CAMERAMAN                 254
#define OBJ_EVENT_GFX_CAMPER_1                  255
#define OBJ_EVENT_GFX_CAMPER_2                  256
#define OBJ_EVENT_GFX_CAMPER_HGSS               257
#define OBJ_EVENT_GFX_CHANNELER                 258
#define OBJ_EVENT_GFX_COLLECTOR_HGSS            259
#define OBJ_EVENT_GFX_COLLECTOR_RSE             260
#define OBJ_EVENT_GFX_COOL_TRAINER_F_1          261
#define OBJ_EVENT_GFX_COOL_TRAINER_F_FRLG       262
#define OBJ_EVENT_GFX_COOL_TRAINER_F_RSE        263
#define OBJ_EVENT_GFX_COOL_TRAINER_M_1          264
#define OBJ_EVENT_GFX_COOL_TRAINER_M_FRLG       265
#define OBJ_EVENT_GFX_COOL_TRAINER_M_RSE        266
#define OBJ_EVENT_GFX_COWGIRL_HGSS              267
#define OBJ_EVENT_GFX_CRUSH_GIRL_FRLG           268
#define OBJ_EVENT_GFX_CYCLIST_M_DPPT            269
#define OBJ_EVENT_GFX_DRAGON_TAMER_HGSS         270
#define OBJ_EVENT_GFX_DRAGON_TAMER_RSE          271
#define OBJ_EVENT_GFX_ENGINEER_FRLG             272
#define OBJ_EVENT_GFX_EXPERT_F_1                273
#define OBJ_EVENT_GFX_EXPERT_F_RSE              274
#define OBJ_EVENT_GFX_EXPERT_M_1                275
#define OBJ_EVENT_GFX_EXPERT_M_RSE              276
#define OBJ_EVENT_GFX_FIREBREATHER_HGSS         277
#define OBJ_EVENT_GFX_FISHERMAN_1               278
#define OBJ_EVENT_GFX_FISHERMAN_2               279
#define OBJ_EVENT_GFX_FISHER_HGSS               280
#define OBJ_EVENT_GFX_GENTLEMAN_1               281
#define OBJ_EVENT_GFX_GENTLEMAN_2               282
#define OBJ_EVENT_GFX_GENTLEMAN_HGSS            283
#define OBJ_EVENT_GFX_GUITARIST_RSE             284
#define OBJ_EVENT_GFX_HEX_MANIAC_1              285
#define OBJ_EVENT_GFX_HEX_MANIAC_RSE            286
#define OBJ_EVENT_GFX_HIKER_1                   287
#define OBJ_EVENT_GFX_HIKER_2                   288
#define OBJ_EVENT_GFX_HIKER_3                   289
#define OBJ_EVENT_GFX_HIKER_HGSS                290
#define OBJ_EVENT_GFX_HIKER_RSE                 291
#define OBJ_EVENT_GFX_JUGGLER_FRLG              292
#define OBJ_EVENT_GFX_JUGGLER_HGSS              293
#define OBJ_EVENT_GFX_KINDLER_RSE               294
#define OBJ_EVENT_GFX_LADY_FRLG                 295
#define OBJ_EVENT_GFX_LASS_1                    296
#define OBJ_EVENT_GFX_LASS_2                    297
#define OBJ_EVENT_GFX_LASS_FRLG                 298
#define OBJ_EVENT_GFX_LASS_HGSS                 299
#define OBJ_EVENT_GFX_MAGMA_MEMBER_F            300
#define OBJ_EVENT_GFX_MAGMA_MEMBER_M            301
#define OBJ_EVENT_GFX_MANIAC                    302
#define OBJ_EVENT_GFX_NINJA_BOY_1               303
#define OBJ_EVENT_GFX_NINJA_BOY_DPPT            304
#define OBJ_EVENT_GFX_PAINTER_FRLG              305
#define OBJ_EVENT_GFX_PICNICKER_1               306
#define OBJ_EVENT_GFX_PICNICKER_2               307
#define OBJ_EVENT_GFX_PICNICKER_HGSS            308
#define OBJ_EVENT_GFX_POKE_FAN_F_1              309
#define OBJ_EVENT_GFX_POKE_FAN_F_RSE            310
#define OBJ_EVENT_GFX_POKE_FAN_M_1              311
#define OBJ_EVENT_GFX_POKE_FAN_M_HGSS           312
#define OBJ_EVENT_GFX_POKE_FAN_M_RSE            313
#define OBJ_EVENT_GFX_POKE_KID_DPPT             314
#define OBJ_EVENT_GFX_POKE_MANIAC_HGSS          315
#define OBJ_EVENT_GFX_POKE_MANIAC_RSE           316
#define OBJ_EVENT_GFX_POLICEMAN_1               317
#define OBJ_EVENT_GFX_POLICEMAN_HGSS            318
#define OBJ_EVENT_GFX_PSYCHIC_F_DPPT            319
#define OBJ_EVENT_GFX_PSYCHIC_F_RSE             320
#define OBJ_EVENT_GFX_PSYCHIC_M_1               321
#define OBJ_EVENT_GFX_PSYCHIC_M_DPPT            322
#define OBJ_EVENT_GFX_PSYCHIC_M_HGSS            323
#define OBJ_EVENT_GFX_PSYCHIC_M_RSE             324
#define OBJ_EVENT_GFX_RANCHER_HGSS              325
#define OBJ_EVENT_GFX_RANGER_F_HGSS             326
#define OBJ_EVENT_GFX_RANGER_F_RSE              327
#define OBJ_EVENT_GFX_RANGER_M_HGSS             328
#define OBJ_EVENT_GFX_RANGER_M_RSE              329
#define OBJ_EVENT_GFX_REPORTER_F                330
#define OBJ_EVENT_GFX_REPORTER_M                331
#define OBJ_EVENT_GFX_RICH_BOY_1                332
#define OBJ_EVENT_GFX_RICH_BOY_RSE              333
#define OBJ_EVENT_GFX_ROCKER_1                  334
#define OBJ_EVENT_GFX_ROCKER_FRLG               335
#define OBJ_EVENT_GFX_ROCKET_GRUNT_F            336
#define OBJ_EVENT_GFX_ROCKET_GRUNT_M_1          337
#define OBJ_EVENT_GFX_ROCKET_GRUNT_M_2          338
#define OBJ_EVENT_GFX_ROUGHNECK_DPPT            339
#define OBJ_EVENT_GFX_ROUGHNECK_FRLG            340
#define OBJ_EVENT_GFX_RUIN_MANIAC_FRLG          341
#define OBJ_EVENT_GFX_RUIN_MANIAC_HGSS          342
#define OBJ_EVENT_GFX_RUIN_MANIAC_RSE           343
#define OBJ_EVENT_GFX_SAGE                      344
#define OBJ_EVENT_GFX_SAILOR_1                  345
#define OBJ_EVENT_GFX_SAILOR_2                  346
#define OBJ_EVENT_GFX_SAILOR_HGSS               347
#define OBJ_EVENT_GFX_SCHOOL_KID_F_RSE          348
#define OBJ_EVENT_GFX_SCHOOL_KID_M_1            349
#define OBJ_EVENT_GFX_SCIENTIST_1               350
#define OBJ_EVENT_GFX_SCIENTIST_2               351
#define OBJ_EVENT_GFX_SCIENTIST_3               352
#define OBJ_EVENT_GFX_SCIENTIST_FRLG            353
#define OBJ_EVENT_GFX_SCIENTIST_HGSS            354
#define OBJ_EVENT_GFX_SKIER_F_DPPT              355
#define OBJ_EVENT_GFX_SKIER_M_DPPT              356
#define OBJ_EVENT_GFX_SUPER_NERD_1              357
#define OBJ_EVENT_GFX_SUPER_NERD_FRLG           358
#define OBJ_EVENT_GFX_SUPER_NERD_HGSS           359
#define OBJ_EVENT_GFX_SWIMMER_F_1_SWIMMING      360
#define OBJ_EVENT_GFX_SWIMMER_F_2               361
#define OBJ_EVENT_GFX_SWIMMER_F_3_SWIMMING      362
#define OBJ_EVENT_GFX_SWIMMER_F_HGSS            363
#define OBJ_EVENT_GFX_SWIMMER_F_HGSS_SWIMMING   364
#define OBJ_EVENT_GFX_SWIMMER_F_RSE             365
#define OBJ_EVENT_GFX_SWIMMER_M_1_SWIMMING      366
#define OBJ_EVENT_GFX_SWIMMER_M_2               367
#define OBJ_EVENT_GFX_SWIMMER_M_2_SWIMMING      368
#define OBJ_EVENT_GFX_SWIMMER_M_HGSS            369
#define OBJ_EVENT_GFX_SWIMMER_M_HGSS_SWIMMING   370
#define OBJ_EVENT_GFX_TAMER_FRLG                371
#define OBJ_EVENT_GFX_TRIATHLETE_F_1_CYCLING    372
#define OBJ_EVENT_GFX_TRIATHLETE_F_1_RUNNING    373
#define OBJ_EVENT_GFX_TRIATHLETE_F_RSE_RUNNING  374
#define OBJ_EVENT_GFX_TRIATHLETE_M_1_CYCLING    375
#define OBJ_EVENT_GFX_TRIATHLETE_M_1_RUNNING    376
#define OBJ_EVENT_GFX_TRIATHLETE_M_RSE_RUNNING  377
#define OBJ_EVENT_GFX_TUBER_F_1                 378
#define OBJ_EVENT_GFX_TUBER_F_2                 379
#define OBJ_EVENT_GFX_TUBER_F_FRLG_SWIMMING     380
#define OBJ_EVENT_GFX_TUBER_F_HGSS              381
#define OBJ_EVENT_GFX_TUBER_F_HGSS_SWIMMING     382
#define OBJ_EVENT_GFX_TUBER_M_1                 383
#define OBJ_EVENT_GFX_TUBER_M_1_SWIMMING        384
#define OBJ_EVENT_GFX_TUBER_M_2                 385
#define OBJ_EVENT_GFX_TUBER_M_2_SWIMMING        386
#define OBJ_EVENT_GFX_TUBER_M_HGSS              387
#define OBJ_EVENT_GFX_TUBER_M_HGSS_SWIMMING     388
#define OBJ_EVENT_GFX_TWIN_1                    389
#define OBJ_EVENT_GFX_TWIN_DPPT                 390
#define OBJ_EVENT_GFX_TWIN_FRLG                 391
#define OBJ_EVENT_GFX_TWIN_HGSS                 392
#define OBJ_EVENT_GFX_TWIN_RSE                  393
#define OBJ_EVENT_GFX_VETERAN_DPPT              394
#define OBJ_EVENT_GFX_YOUNGSTER_1               395
#define OBJ_EVENT_GFX_YOUNGSTER_2               396
#define OBJ_EVENT_GFX_YOUNGSTER_HGSS            397
#define OBJ_EVENT_GFX_YOUNG_COUPLE_F_FRLG       398
#define OBJ_EVENT_GFX_YOUNG_COUPLE_M_FRLG       399

#define OBJ_EVENT_GFX_BARD                      400
#define OBJ_EVENT_GFX_CAPTAIN                   401
#define OBJ_EVENT_GFX_CONTEST_JUDGE             402
#define OBJ_EVENT_GFX_GYM_GUY                   403
#define OBJ_EVENT_GFX_LINK_RECEPTIONIST         404
#define OBJ_EVENT_GFX_MART_EMPLOYEE_1           405
#define OBJ_EVENT_GFX_MART_EMPLOYEE_2           406
#define OBJ_EVENT_GFX_MART_EMPLOYEE_3           407
#define OBJ_EVENT_GFX_MOM                       408
#define OBJ_EVENT_GFX_MOM_KANTO                 409
#define OBJ_EVENT_GFX_MYSTERY_GIFT_MAN_1        410
#define OBJ_EVENT_GFX_MYSTERY_GIFT_MAN_2        411
#define OBJ_EVENT_GFX_NURSE_1                   412
#define OBJ_EVENT_GFX_NURSE_2                   413
#define OBJ_EVENT_GFX_NURSE_3                   414
#define OBJ_EVENT_GFX_NURSE_4                   415
#define OBJ_EVENT_GFX_RECEPTIONIST              416
#define OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN        417
#define OBJ_EVENT_GFX_TEACHY_TV_HOST            418
#define OBJ_EVENT_GFX_TEALA_1                   419
#define OBJ_EVENT_GFX_TEALA_2                   420
#define OBJ_EVENT_GFX_TRAINER_TOWER_DUDE        421
#define OBJ_EVENT_GFX_UNION_ROOM_NURSE_1        422
#define OBJ_EVENT_GFX_UNION_ROOM_NURSE_2        423

#define OBJ_EVENT_GFX_BRENDAN_NORMAL            424
#define OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE         425
#define OBJ_EVENT_GFX_BRENDAN_DECORATING        426
#define OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE        427
#define OBJ_EVENT_GFX_BRENDAN_FISHING           428
#define OBJ_EVENT_GFX_BRENDAN_MACH_BIKE         429
#define OBJ_EVENT_GFX_BRENDAN_SURFING           430
#define OBJ_EVENT_GFX_BRENDAN_UNDERWATER        431
#define OBJ_EVENT_GFX_BRENDAN_WATERING          432
#define OBJ_EVENT_GFX_BRENDAN_RED               433
#define OBJ_EVENT_GFX_BRENDAN_BLUE              434
#define OBJ_EVENT_GFX_BRENDAN_GREEN             435
#define OBJ_EVENT_GFX_BRENDAN_RS                436

#define OBJ_EVENT_GFX_MAY_NORMAL                437
#define OBJ_EVENT_GFX_MAY_ACRO_BIKE             438
#define OBJ_EVENT_GFX_MAY_DECORATING            439
#define OBJ_EVENT_GFX_MAY_FIELD_MOVE            440
#define OBJ_EVENT_GFX_MAY_FISHING               441
#define OBJ_EVENT_GFX_MAY_MACH_BIKE             442
#define OBJ_EVENT_GFX_MAY_SURFING               443
#define OBJ_EVENT_GFX_MAY_UNDERWATER            444
#define OBJ_EVENT_GFX_MAY_WATERING              445
#define OBJ_EVENT_GFX_MAY_RED                   446
#define OBJ_EVENT_GFX_MAY_BLUE                  447
#define OBJ_EVENT_GFX_MAY_GREEN                 448
#define OBJ_EVENT_GFX_MAY_RS                    449

#define OBJ_EVENT_GFX_RED                       450
#define OBJ_EVENT_GFX_RED_2                     451
#define OBJ_EVENT_GFX_LEAF                      452
#define OBJ_EVENT_GFX_LEAF_2                    453
#define OBJ_EVENT_GFX_GOLD                      454
#define OBJ_EVENT_GFX_KRIS                      455
#define OBJ_EVENT_GFX_ETHAN                     456
#define OBJ_EVENT_GFX_LYRA                      457
#define OBJ_EVENT_GFX_WES                       458

#define OBJ_EVENT_GFX_ANABEL                    459
#define OBJ_EVENT_GFX_ARCHIE                    460
#define OBJ_EVENT_GFX_BRANDON                   461
#define OBJ_EVENT_GFX_BRAWLY                    462
#define OBJ_EVENT_GFX_DRAKE                     463
#define OBJ_EVENT_GFX_FLANNERY                  464
#define OBJ_EVENT_GFX_GLACIA                    465
#define OBJ_EVENT_GFX_GRETA                     466
#define OBJ_EVENT_GFX_JUAN                      467
#define OBJ_EVENT_GFX_LIZA                      468
#define OBJ_EVENT_GFX_LUCY                      469
#define OBJ_EVENT_GFX_MAXIE                     470
#define OBJ_EVENT_GFX_NOLAND                    471
#define OBJ_EVENT_GFX_NORMAN                    472
#define OBJ_EVENT_GFX_PHOEBE                    473
#define OBJ_EVENT_GFX_PROF_BIRCH                474
#define OBJ_EVENT_GFX_ROXANNE                   475
#define OBJ_EVENT_GFX_SCOTT                     476
#define OBJ_EVENT_GFX_SIDNEY                    477
#define OBJ_EVENT_GFX_SPENSER                   478
#define OBJ_EVENT_GFX_STEVEN                    479
#define OBJ_EVENT_GFX_TATE                      480
#define OBJ_EVENT_GFX_TUCKER                    481
#define OBJ_EVENT_GFX_WALLACE                   482
#define OBJ_EVENT_GFX_WALLY                     483
#define OBJ_EVENT_GFX_WATTSON                   484
#define OBJ_EVENT_GFX_WINONA                    485

#define OBJ_EVENT_GFX_AGATHA                    486
#define OBJ_EVENT_GFX_BILL                      487
#define OBJ_EVENT_GFX_BLAINE                    488
#define OBJ_EVENT_GFX_BLUE                      489
#define OBJ_EVENT_GFX_BROCK                     490
#define OBJ_EVENT_GFX_BRUNO                     491
#define OBJ_EVENT_GFX_CELIO                     492
#define OBJ_EVENT_GFX_DAISY                     493
#define OBJ_EVENT_GFX_ERIKA                     494
#define OBJ_EVENT_GFX_GIOVANNI                  495
#define OBJ_EVENT_GFX_KOGA                      496
#define OBJ_EVENT_GFX_LANCE                     497
#define OBJ_EVENT_GFX_LORELEI                   498
#define OBJ_EVENT_GFX_LT_SURGE                  499
#define OBJ_EVENT_GFX_MISTY                     500
#define OBJ_EVENT_GFX_MR_FUJI                   501
#define OBJ_EVENT_GFX_PROF_OAK                  502
#define OBJ_EVENT_GFX_SABRINA                   503

#define OBJ_EVENT_GFX_RED_RY                    504
#define OBJ_EVENT_GFX_LEAF_RY                   (OBJ_EVENT_GFX_LEAF)

#define NUM_OBJ_EVENT_GFX                       505


// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VARS   (0xFFF0)
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VARS + 0x0)
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VARS + 0x1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VARS + 0x2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VARS + 0x3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VARS + 0x4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VARS + 0x5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VARS + 0x6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VARS + 0x7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VARS + 0x8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VARS + 0x9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VARS + 0xA)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VARS + 0xB)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VARS + 0xC)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VARS + 0xD)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VARS + 0xE)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VARS + 0xF)

#define SHADOW_SIZE_S   0
#define SHADOW_SIZE_M   1
#define SHADOW_SIZE_L   2
#define SHADOW_SIZE_XL  3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2

#define FIRST_DECORATION_SPRITE_GFX OBJ_EVENT_GFX_PICHU_DOLL

#define OBJ_KIND_NORMAL 0
#define OBJ_KIND_CLONE  255 // Exclusive to FRLG

// Special object event local ids
#define OBJ_EVENT_ID_PLAYER 0xFF
#define OBJ_EVENT_ID_CAMERA 0x7F

// Object event local ids referenced in C files
#define LOCALID_ROUTE111_PLAYER_FALLING 45
#define LOCALID_BIRTH_ISLAND_EXTERIOR_ROCK 1
#define LOCALID_FARAWAY_ISLAND_MEW 1
#define LOCALID_UNION_ROOM_PLAYER_4 2
#define LOCALID_UNION_ROOM_PLAYER_8 3
#define LOCALID_UNION_ROOM_PLAYER_7 4
#define LOCALID_UNION_ROOM_PLAYER_6 5
#define LOCALID_UNION_ROOM_PLAYER_5 6
#define LOCALID_UNION_ROOM_PLAYER_3 7
#define LOCALID_UNION_ROOM_PLAYER_2 8
#define LOCALID_UNION_ROOM_PLAYER_1 9
#define LOCALID_BATTLE_TOWER_LOBBY_REPORTER 5
#define LOCALID_TRUCK_BOX_TOP 1
#define LOCALID_TRUCK_BOX_BOTTOM_L 2
#define LOCALID_TRUCK_BOX_BOTTOM_R 3
#define LOCALID_OLDALE_MART_CLERK 1
#define LOCALID_LAVARIDGE_MART_CLERK 1
#define LOCALID_FALLARBOR_MART_CLERK 1
#define LOCALID_VERDANTURF_MART_CLERK 1
#define LOCALID_PETALBURG_MART_CLERK 1
#define LOCALID_SLATEPORT_MART_CLERK 1
#define LOCALID_MAUVILLE_MART_CLERK 1
#define LOCALID_RUSTBORO_MART_CLERK 1
#define LOCALID_FORTREE_MART_CLERK 1
#define LOCALID_MOSSDEEP_MART_CLERK 1
#define LOCALID_SOOTOPOLIS_MART_CLERK 1
#define LOCALID_BATTLE_FRONTIER_MART_CLERK 1
#define LOCALID_SLATEPORT_ENERGY_GURU 25

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
