#ifndef GUARD_REGIONMAPSEC_H
#define GUARD_REGIONMAPSEC_H

#define MAPSEC_LITTLEROOT_TOWN              0x00
#define MAPSEC_OLDALE_TOWN                  0x01
#define MAPSEC_DEWFORD_TOWN                 0x02
#define MAPSEC_LAVARIDGE_TOWN               0x03
#define MAPSEC_FALLARBOR_TOWN               0x04
#define MAPSEC_VERDANTURF_TOWN              0x05
#define MAPSEC_PACIFIDLOG_TOWN              0x06
#define MAPSEC_PETALBURG_CITY               0x07
#define MAPSEC_SLATEPORT_CITY               0x08
#define MAPSEC_MAUVILLE_CITY                0x09
#define MAPSEC_RUSTBORO_CITY                0x0A
#define MAPSEC_FORTREE_CITY                 0x0B
#define MAPSEC_LILYCOVE_CITY                0x0C
#define MAPSEC_MOSSDEEP_CITY                0x0D
#define MAPSEC_SOOTOPOLIS_CITY              0x0E
#define MAPSEC_EVER_GRANDE_CITY             0x0F
#define MAPSEC_ROUTE_101                    0x10
#define MAPSEC_ROUTE_102                    0x11
#define MAPSEC_ROUTE_103                    0x12
#define MAPSEC_ROUTE_104                    0x13
#define MAPSEC_ROUTE_105                    0x14
#define MAPSEC_ROUTE_106                    0x15
#define MAPSEC_ROUTE_107                    0x16
#define MAPSEC_ROUTE_108                    0x17
#define MAPSEC_ROUTE_109                    0x18
#define MAPSEC_ROUTE_110                    0x19
#define MAPSEC_ROUTE_111                    0x1A
#define MAPSEC_ROUTE_112                    0x1B
#define MAPSEC_ROUTE_113                    0x1C
#define MAPSEC_ROUTE_114                    0x1D
#define MAPSEC_ROUTE_115                    0x1E
#define MAPSEC_ROUTE_116                    0x1F
#define MAPSEC_ROUTE_117                    0x20
#define MAPSEC_ROUTE_118                    0x21
#define MAPSEC_ROUTE_119                    0x22
#define MAPSEC_ROUTE_120                    0x23
#define MAPSEC_ROUTE_121                    0x24
#define MAPSEC_ROUTE_122                    0x25
#define MAPSEC_ROUTE_123                    0x26
#define MAPSEC_ROUTE_124                    0x27
#define MAPSEC_ROUTE_125                    0x28
#define MAPSEC_ROUTE_126                    0x29
#define MAPSEC_ROUTE_127                    0x2A
#define MAPSEC_ROUTE_128                    0x2B
#define MAPSEC_ROUTE_129                    0x2C
#define MAPSEC_ROUTE_130                    0x2D
#define MAPSEC_ROUTE_131                    0x2E
#define MAPSEC_ROUTE_132                    0x2F
#define MAPSEC_ROUTE_133                    0x30
#define MAPSEC_ROUTE_134                    0x31
#define MAPSEC_UNDERWATER_124               0x32
#define MAPSEC_UNDERWATER_126               0x33
#define MAPSEC_UNDERWATER_127               0x34
#define MAPSEC_UNDERWATER_128               0x35
#define MAPSEC_UNDERWATER_SOOTOPOLIS        0x36
#define MAPSEC_GRANITE_CAVE                 0x37
#define MAPSEC_MT_CHIMNEY                   0x38
#define MAPSEC_SAFARI_ZONE                  0x39
#define MAPSEC_BATTLE_FRONTIER              0x3A
#define MAPSEC_PETALBURG_WOODS              0x3B
#define MAPSEC_RUSTURF_TUNNEL               0x3C
#define MAPSEC_ABANDONED_SHIP               0x3D
#define MAPSEC_NEW_MAUVILLE                 0x3E
#define MAPSEC_METEOR_FALLS                 0x3F
#define MAPSEC_METEOR_FALLS2                0x40
#define MAPSEC_MT_PYRE                      0x41
#define MAPSEC_AQUA_HIDEOUT_OLD             0x42
#define MAPSEC_SHOAL_CAVE                   0x43
#define MAPSEC_SEAFLOOR_CAVERN              0x44
#define MAPSEC_UNDERWATER_SEAFLOOR_CAVERN   0x45
#define MAPSEC_VICTORY_ROAD                 0x46
#define MAPSEC_MIRAGE_ISLAND                0x47
#define MAPSEC_CAVE_OF_ORIGIN               0x48
#define MAPSEC_SOUTHERN_ISLAND              0x49
#define MAPSEC_FIERY_PATH                   0x4A
#define MAPSEC_FIERY_PATH2                  0x4B
#define MAPSEC_JAGGED_PASS                  0x4C
#define MAPSEC_JAGGED_PASS2                 0x4D
#define MAPSEC_SEALED_CHAMBER               0x4E
#define MAPSEC_UNDERWATER_SEALED_CHAMBER    0x4F
#define MAPSEC_SCORCHED_SLAB                0x50
#define MAPSEC_ISLAND_CAVE                  0x51
#define MAPSEC_DESERT_RUINS                 0x52
#define MAPSEC_ANCIENT_TOMB                 0x53
#define MAPSEC_INSIDE_OF_TRUCK              0x54
#define MAPSEC_SKY_PILLAR                   0x55
#define MAPSEC_SECRET_BASE                  0x56
#define MAPSEC_DYNAMIC                      0x57
#define MAPSEC_PALLET_TOWN                  0x58
#define MAPSEC_VIRIDIAN_CITY                0x59
#define MAPSEC_PEWTER_CITY                  0x5A
#define MAPSEC_CERULEAN_CITY                0x5B
#define MAPSEC_LAVENDER_TOWN                0x5C
#define MAPSEC_VERMILION_CITY               0x5D
#define MAPSEC_CELADON_CITY                 0x5E
#define MAPSEC_FUCHSIA_CITY                 0x5F
#define MAPSEC_CINNABAR_ISLAND              0x60
#define MAPSEC_INDIGO_PLATEAU               0x61
#define MAPSEC_SAFFRON_CITY                 0x62
#define MAPSEC_ROUTE_4_POKECENTER           0x63
#define MAPSEC_ROUTE_10_POKECENTER          0x64
#define MAPSEC_ROUTE_1                      0x65
#define MAPSEC_ROUTE_2                      0x66
#define MAPSEC_ROUTE_3                      0x67
#define MAPSEC_ROUTE_4                      0x68
#define MAPSEC_ROUTE_5                      0x69
#define MAPSEC_ROUTE_6                      0x6A
#define MAPSEC_ROUTE_7                      0x6B
#define MAPSEC_ROUTE_8                      0x6C
#define MAPSEC_ROUTE_9                      0x6D
#define MAPSEC_ROUTE_10                     0x6E
#define MAPSEC_ROUTE_11                     0x6F
#define MAPSEC_ROUTE_12                     0x70
#define MAPSEC_ROUTE_13                     0x71
#define MAPSEC_ROUTE_14                     0x72
#define MAPSEC_ROUTE_15                     0x73
#define MAPSEC_ROUTE_16                     0x74
#define MAPSEC_ROUTE_17                     0x75
#define MAPSEC_ROUTE_18                     0x76
#define MAPSEC_ROUTE_19                     0x77
#define MAPSEC_ROUTE_20                     0x78
#define MAPSEC_ROUTE_21                     0x79
#define MAPSEC_ROUTE_22                     0x7A
#define MAPSEC_ROUTE_23                     0x7B
#define MAPSEC_ROUTE_24                     0x7C
#define MAPSEC_ROUTE_25                     0x7D
#define MAPSEC_VIRIDIAN_FOREST              0x7E
#define MAPSEC_MT_MOON                      0x7F
#define MAPSEC_S_S_ANNE                     0x80
#define MAPSEC_UNDERGROUND_PATH             0x81
#define MAPSEC_UNDERGROUND_PATH_2           0x82
#define MAPSEC_DIGLETTS_CAVE                0x83
#define MAPSEC_KANTO_VICTORY_ROAD           0x84
#define MAPSEC_ROCKET_HIDEOUT               0x85
#define MAPSEC_SILPH_CO                     0x86
#define MAPSEC_POKEMON_MANSION              0x87
#define MAPSEC_KANTO_SAFARI_ZONE            0x88
#define MAPSEC_POKEMON_LEAGUE               0x89
#define MAPSEC_ROCK_TUNNEL                  0x8A
#define MAPSEC_SEAFOAM_ISLANDS              0x8B
#define MAPSEC_POKEMON_TOWER                0x8C
#define MAPSEC_CERULEAN_CAVE                0x8D
#define MAPSEC_POWER_PLANT                  0x8E
#define MAPSEC_ONE_ISLAND                   0x8F
#define MAPSEC_TWO_ISLAND                   0x90
#define MAPSEC_THREE_ISLAND                 0x91
#define MAPSEC_FOUR_ISLAND                  0x92
#define MAPSEC_FIVE_ISLAND                  0x93
#define MAPSEC_SEVEN_ISLAND                 0x94
#define MAPSEC_SIX_ISLAND                   0x95
#define MAPSEC_KINDLE_ROAD                  0x96
#define MAPSEC_TREASURE_BEACH               0x97
#define MAPSEC_CAPE_BRINK                   0x98
#define MAPSEC_BOND_BRIDGE                  0x99
#define MAPSEC_THREE_ISLE_PORT              0x9A
#define MAPSEC_SEVII_ISLE_6                 0x9B
#define MAPSEC_SEVII_ISLE_7                 0x9C
#define MAPSEC_SEVII_ISLE_8                 0x9D
#define MAPSEC_SEVII_ISLE_9                 0x9E
#define MAPSEC_RESORT_GORGEOUS              0x9F
#define MAPSEC_WATER_LABYRINTH              0xA0
#define MAPSEC_FIVE_ISLE_MEADOW             0xA1
#define MAPSEC_MEMORIAL_PILLAR              0xA2
#define MAPSEC_OUTCAST_ISLAND               0xA3
#define MAPSEC_GREEN_PATH                   0xA4
#define MAPSEC_WATER_PATH                   0xA5
#define MAPSEC_RUIN_VALLEY                  0xA6
#define MAPSEC_TRAINER_TOWER                0xA7
#define MAPSEC_CANYON_ENTRANCE              0xA8
#define MAPSEC_SEVAULT_CANYON               0xA9
#define MAPSEC_TANOBY_RUINS                 0xAA
#define MAPSEC_SEVII_ISLE_22                0xAB
#define MAPSEC_SEVII_ISLE_23                0xAC
#define MAPSEC_SEVII_ISLE_24                0xAD
#define MAPSEC_NAVEL_ROCK_FRLG              0xAE
#define MAPSEC_MT_EMBER                     0xAF
#define MAPSEC_BERRY_FOREST                 0xB0
#define MAPSEC_ICEFALL_CAVE                 0xB1
#define MAPSEC_ROCKET_WAREHOUSE             0xB2
#define MAPSEC_TRAINER_TOWER_2              0xB3
#define MAPSEC_DOTTED_HOLE                  0xB4
#define MAPSEC_LOST_CAVE                    0xB5
#define MAPSEC_PATTERN_BUSH                 0xB6
#define MAPSEC_ALTERING_CAVE_FRLG           0xB7
#define MAPSEC_TANOBY_CHAMBERS              0xB8
#define MAPSEC_THREE_ISLE_PATH              0xB9
#define MAPSEC_TANOBY_KEY                   0xBA
#define MAPSEC_BIRTH_ISLAND_FRLG            0xBB
#define MAPSEC_MONEAN_CHAMBER               0xBC
#define MAPSEC_LIPTOO_CHAMBER               0xBD
#define MAPSEC_WEEPTH_CHAMBER               0xBE
#define MAPSEC_DILFORD_CHAMBER              0xBF
#define MAPSEC_SCUFIB_CHAMBER               0xC0
#define MAPSEC_RIXY_CHAMBER                 0xC1
#define MAPSEC_VIAPOIS_CHAMBER              0xC2
#define MAPSEC_EMBER_SPA                    0xC3
#define MAPSEC_SPECIAL_AREA                 0xC4
#define MAPSEC_AQUA_HIDEOUT                 0xC5
#define MAPSEC_MAGMA_HIDEOUT                0xC6
#define MAPSEC_MIRAGE_TOWER                 0xC7
#define MAPSEC_BIRTH_ISLAND                 0xC8
#define MAPSEC_FARAWAY_ISLAND               0xC9
#define MAPSEC_ARTISAN_CAVE                 0xCA
#define MAPSEC_MARINE_CAVE                  0xCB
#define MAPSEC_UNDERWATER_MARINE_CAVE       0xCC
#define MAPSEC_TERRA_CAVE                   0xCD
#define MAPSEC_UNDERWATER_105               0xCE
#define MAPSEC_UNDERWATER_125               0xCF
#define MAPSEC_UNDERWATER_129               0xD0
#define MAPSEC_DESERT_UNDERPASS             0xD1
#define MAPSEC_ALTERING_CAVE                0xD2
#define MAPSEC_NAVEL_ROCK                   0xD3
#define MAPSEC_TRAINER_HILL                 0xD4
#define MAPSEC_NONE                         0xD5

//Battle Tower from Ruby/Sapphire
#define MAPSEC_BATTLE_TOWER					0xFC

#define METLOC_SPECIAL_EGG					0xFD
#define METLOC_IN_GAME_TRADE				0xFE
#define METLOC_FATEFUL_ENCOUNTER			0xFF

//Johto met locations using CrystalDust as the standard
#define MAPSEC_NEW_BARK_TOWN_CD				0x00
#define MAPSEC_CHERRYGROVE_CITY_CD			0x01
#define MAPSEC_AZALEA_TOWN_CD				0x02
#define MAPSEC_CIANWOOD_CITY_CD				0x03
#define MAPSEC_MAHOGANY_TOWN_CD				0x04
#define MAPSEC_VIOLET_CITY_CD				0x07
#define MAPSEC_ECRUTEAK_CITY_CD				0x08
#define MAPSEC_OLIVINE_CITY_CD				0x09
#define MAPSEC_GOLDENROD_CITY_CD			0x0A
#define MAPSEC_BLACKTHORN_CITY_CD			0x0C
#define MAPSEC_ROUTE_29_CD					0x10
#define MAPSEC_ROUTE_30_CD					0x11
#define MAPSEC_ROUTE_31_CD					0x12
#define MAPSEC_ROUTE_32_CD					0x13
#define MAPSEC_ROUTE_33_CD					0x14
#define MAPSEC_ROUTE_34_CD					0x15
#define MAPSEC_ROUTE_35_CD					0x16
#define MAPSEC_ROUTE_36_CD					0x17
#define MAPSEC_ROUTE_37_CD					0x18
#define MAPSEC_ROUTE_38_CD					0x19
#define MAPSEC_ROUTE_39_CD					0x1A
#define MAPSEC_ROUTE_40_CD					0x1B
#define MAPSEC_ROUTE_41_CD					0x1C
#define MAPSEC_ROUTE_42_CD					0x1D
#define MAPSEC_ROUTE_43_CD					0x1E
#define MAPSEC_ROUTE_44_CD					0x1F
#define MAPSEC_ROUTE_45_CD					0x20
#define MAPSEC_ROUTE_46_CD					0x21
#define MAPSEC_ROUTE_26_CD					0x22
#define MAPSEC_ROUTE_27_CD					0x23
#define MAPSEC_ROUTE_28_CD					0x24
#define MAPSEC_ROUTE_32_FLYDUP_CD			0x25
#define MAPSEC_DARK_CAVE_CD					0x37
#define MAPSEC_SLOWPOKE_WELL_CD				0x38
#define MAPSEC_BATTLE_FRONTIER_CD			0x3A
#define MAPSEC_ILEX_FOREST_CD				0x3B
#define MAPSEC_UNION_CAVE_CD				0x3C
#define MAPSEC_SPROUT_TOWER_CD				0x3D
#define MAPSEC_RUINS_OF_ALPH_CD				0x3E
#define MAPSEC_ALPH_CHAMBERS_CD				0x3F
#define MAPSEC_RADIO_TOWER_CD				0x40
#define MAPSEC_MT_MORTAR_CD					0x41
#define MAPSEC_LIGHTHOUSE_CD				0x43
#define MAPSEC_DRAGONS_DEN_CD				0x44
#define MAPSEC_LAKE_OF_RAGE_CD				0x4A
#define MAPSEC_NATIONAL_PARK_CD				0x4B
#define MAPSEC_ICE_PATH_CD					0x4C
#define MAPSEC_SILVER_CAVE_CD				0x4D
#define MAPSEC_WHIRL_ISLANDS_CD				0x51
#define MAPSEC_TIN_TOWER_CD					0x52


//Orre met locations
#define MAPSEC_DISTANT_LAND					0x00
#define MAPSEC_OUTSKIRT_STAND				0x01
#define MAPSEC_PHENAC_CITY					0x02
#define MAPSEC_MAYORS_HOUSE					0x03
#define MAPSEC_PRE_GYM						0x04
#define MAPSEC_PHENAC_STADIUM				0x05
#define MAPSEC_PYRITE_TOWN					0x06
#define MAPSEC_PYRITE_BLDG					0x07
#define MAPSEC_PYRITE_CAVE					0x08
#define MAPSEC_MIRORS_HIDEOUT				0x09
#define MAPSEC_PYRITE_COLOSSEUM				0x10
#define MAPSEC_AGATE_VILLAGE				0x11
#define MAPSEC_RELIC_CAVE					0x12
#define MAPSEC_THE_UNDER					0x13
#define MAPSEC_THE_UNDER_SUBWAY				0x14
#define MAPSEC_UNDER_COLOSSEUM				0x15
#define MAPSEC_DEEP_COLOSSEUM				0x16
#define MAPSEC_FRONT_OF_LAB					0x17
#define MAPSEC_LABORATORY					0x18
#define MAPSEC_MT_BATTLE					0x19
#define MAPSEC_MTBTL_COLOSSEUM				0x20
#define MAPSEC_REALGAM_TOWER				0x21
#define MAPSEC_REALGAMTWR_DOME				0x22
#define MAPSEC_REALGAMTWR_LOBBY				0x23
#define MAPSEC_TOWER_COLOSSEUM				0x24
#define MAPSEC_ORRE_COLOSSEUM				0x25
#define MAPSEC_SNAGEM_HIDEOUT				0x26
#define MAPSEC_REALGAM_TOWER_2F				0x27
#define MAPSEC_CIPHER_LAB					0x28
#define MAPSEC_S_S_LIBRA					0x29
#define MAPSEC_CIPHER_KEY_LAIR				0x30
#define MAPSEC_CITADARK_ISLE				0x31
#define MAPSEC_ROCK							0x32
#define MAPSEC_OASIS						0x33
#define MAPSEC_CAVE							0x34
#define MAPSEC_POKEMON_HQ_LAB				0x35
#define MAPSEC_GATEON_PORT					0x36
#define MAPSEC_KAMINKOS_HOUSE				0x37


//Gen 4 Locations
#define MAPSEC_MYSTERY_ZONE					0x00
#define MAPSEC_TWINLEAF_TOWN				0x01
#define MAPSEC_SANDGEM_TOWN					0x02
#define MAPSEC_FLOAROMA_TOWN				0x03
#define MAPSEC_SOLACEON_TOWN				0x04
#define MAPSEC_CELESTIC_TOWN				0x05
#define MAPSEC_JUBILIFE_CITY				0x06
#define MAPSEC_CANALAVE_CITY				0x07
#define MAPSEC_OREBURGH_CITY				0x08
#define MAPSEC_ETERNA_CITY					0x09
#define MAPSEC_HEARTHOME_CITY				0x0A
#define MAPSEC_PASTORIA_CITY				0x0B
#define MAPSEC_VEILSTONE_CITY				0x0C
#define MAPSEC_SUNYSHORE_CITY				0x0D
#define MAPSEC_SNOWPOINT_CITY				0x0E
#define MAPSEC_SINNOH_POKEMON_LEAGUE		0x0F
#define MAPSEC_ROUTE_201					0x10
#define MAPSEC_ROUTE_202					0x11
#define MAPSEC_ROUTE_203					0x12
#define MAPSEC_ROUTE_204					0x13
#define MAPSEC_ROUTE_205					0x14
#define MAPSEC_ROUTE_206					0x15
#define MAPSEC_ROUTE_207					0x16
#define MAPSEC_ROUTE_208					0x17
#define MAPSEC_ROUTE_209					0x18
#define MAPSEC_ROUTE_210					0x19
#define MAPSEC_ROUTE_211					0x1A
#define MAPSEC_ROUTE_212					0x1B
#define MAPSEC_ROUTE_213					0x1C
#define MAPSEC_ROUTE_214					0x1D
#define MAPSEC_ROUTE_215					0x1E
#define MAPSEC_ROUTE_216					0x1F
#define MAPSEC_ROUTE_217					0x20
#define MAPSEC_ROUTE_218					0x21
#define MAPSEC_ROUTE_219					0x22
#define MAPSEC_ROUTE_220					0x23
#define MAPSEC_ROUTE_221					0x24
#define MAPSEC_ROUTE_222					0x25
#define MAPSEC_ROUTE_223					0x26
#define MAPSEC_ROUTE_224					0x27
#define MAPSEC_ROUTE_225					0x28
#define MAPSEC_ROUTE_226					0x29
#define MAPSEC_ROUTE_227					0x2A
#define MAPSEC_ROUTE_228					0x2B
#define MAPSEC_ROUTE_229					0x2C
#define MAPSEC_ROUTE_230					0x2D
#define MAPSEC_OREBUGH_MINE					0x2E
#define MAPSEC_VALLEY_WINDWORKS				0x2F
#define MAPSEC_ETERNA_FOREST				0x30
#define MAPSEC_FUEGO_IRONWORKS				0x31
#define MAPSEC_MT_CORONET					0x32
#define MAPSEC_SPEAR_PILLAR					0x33
#define MAPSEC_GREAT_MARSH					0x34
#define MAPSEC_SOLACEON_RUINS				0x35
#define MAPSEC_SINNOH_VICTORY_ROAD			0x36
#define MAPSEC_PAL_PARK						0x37
#define MAPSEC_AMITY_SQUARE					0x38
#define MAPSEC_RAVAGED_PATH					0x39
#define MAPSEC_FLOAROMA_MEADOW				0x3A
#define MAPSEC_OREBURG_GATE					0x3B
#define MAPSEC_FULLMOON_ISLAND				0x3C
#define MAPSEC_SENDOFF_SPRING				0x3D
#define MAPSEC_TURNBACK_CAVE				0x3E
#define MAPSEC_FLOWER_PARADISE				0x3F
#define MAPSEC_SNOWPOINT_TEMPLE				0x40
#define MAPSEC_WAYWARD_CAVE					0x41
#define MAPSEC_RUIN_MANIAC_CAVE				0x42
#define MAPSEC_MANIAC_TUNNEL				0x43
#define MAPSEC_TROPHY_GARDEN				0x44
#define MAPSEC_IRON_ISLAND					0x45
#define MAPSEC_OLD_CHATEAU					0x46
#define MAPSEC_GALACTIC_HQ					0x47
#define MAPSEC_VERITY_LAKEFRONT				0x48
#define MAPSEC_VALOR_LAKEFRONT				0x49
#define MAPSEC_ACUITY_LAKEFRONT				0x4A
#define MAPSEC_SPRING_PATH					0x4B
#define MAPSEC_LAKE_VERITY					0x4C
#define MAPSEC_LAKE_VALOR					0x4D
#define MAPSEC_LAKE_ACUITY					0x4E
#define MAPSEC_NEWMOON_ISLAND				0x4F
#define MAPSEC_SINNOH_BATTLE_TOWER			0x50
#define MAPSEC_FIGHT_AREA					0x51
#define MAPSEC_SURVIVAL_AREA				0x52
#define MAPSEC_RESORT_AREA					0x53
#define MAPSEC_STARK_MOUNTAIN				0x54
#define MAPSEC_SEABREAK_PATH				0x55
#define MAPSEC_HALL_OF_ORIGIN				0x56
#define MAPSEC_VERITY_CAVERN				0x57
#define MAPSEC_VALOR_CAVERN					0x58
#define MAPSEC_ACUITY_CAVERN				0x59
#define MAPSEC_JUBILIFE_TV					0x5A
#define MAPSEC_POKETCH_CO					0x5B
#define MAPSEC_GTS							0x5C
#define MAPSEC_TRAINERS_SCHOOL				0x5D
#define MAPSEC_MINING_MUESEUM				0x5E
#define MAPSEC_FLOWER_SHOP					0x5F
#define MAPSEC_CYCLE_SHOP					0x60
#define MAPSEC_CONTEST_HALL					0x61
#define MAPSEC_POFFIN_HOUSE					0x62
#define MAPSEC_FOREIGN_BUILDING				0x63
#define MAPSEC_SINNOH_POKEMON_DAY_CARE		0x64
#define MAPSEC_VEILSTONE_STORE				0x65
#define MAPSEC_GAME_CORNER_DP				0x66
#define MAPSEC_CANALAVE_LIBRARY				0x67
#define MAPSEC_VISTA_LIGHTHOUSE				0x68
#define MAPSEC_SUNYSHORE_MARKET				0x69
#define MAPSEC_SINNOH_POKEMON_MANSION		0x6A
#define MAPSEC_FOOTSTEP_HOUSE				0x6B
#define MAPSEC_CAFE							0x6C
#define MAPSEC_GRAND_LAKE					0x6D
#define MAPSEC_RESTAURANT					0x6E
#define MAPSEC_BATTLE_PARK					0x6E
#define MAPSEC_SINJOH_BATTLE_FRONTIER		0x70
#define MAPSEC_BATTLE_FACTORY				0x71
#define MAPSEC_BATTLE_CASTLE				0x72
#define MAPSEC_BATTLE_ARCADE				0x73
#define MAPSEC_BATTLE_HALL					0x74
#define MAPSEC_DISTORTION_WORLD				0x75
#define MAPSEC_GLOBAL_TERMINAL				0x76
#define MAPSEC_VILLA						0x77
#define MAPSEC_BATTLEGROUND					0x78
#define MAPSEC_ROTOMS_ROOM					0x79
#define MAPSEC_TG_ETERNA_BLDG				0x7A
#define MAPSEC_IRON_RUINS					0x7B
#define MAPSEC_ICEBERG_RUINS				0x7C
#define MAPSEC_ROCK_PEAK_RUINS				0x7D
#define MAPSEC_NEW_BARK_TOWN				0x7E
#define MAPSEC_CHERRYGROVE_CITY				0x7F
#define MAPSEC_VIOLET_CITY					0x80
#define MAPSEC_AZALEA_TOWN					0x81
#define MAPSEC_CIANWOOD_CITY				0x82
#define MAPSEC_GOLDENROD_CITY				0x83
#define MAPSEC_OLIVINE_CITY					0x84
#define MAPSEC_ECRUTEAK_CITY				0x85
#define MAPSEC_MAHOGANY_TOWN				0x86
#define MAPSEC_LAKE_OF_RAGE					0x87
#define MAPSEC_BLACKTHORN_CITY				0x88
#define MAPSEC_MT_SILVER					0x89
#define MAPSEC_PALLET_TOWN_HGSS				0x8A
#define MAPSEC_VIRIDIAN_CITY_HGSS			0x8B
#define MAPSEC_PEWTER_CITY_HGSS				0x8C
#define MAPSEC_CERULEAN_CITY_HGSS			0x8D
#define MAPSEC_LAVENDER_TOWN_HGSS			0x8E
#define MAPSEC_VERMILION_CITY_HGSS			0x8F
#define MAPSEC_CELADON_CITY_HGSS			0x90
#define MAPSEC_FUCHSIA_CITY_HGSS			0x91
#define MAPSEC_CINNABAR_ISLAND_HGSS			0x92
#define MAPSEC_INDIGO_PLATEAU_HGSS			0x93
#define MAPSEC_SAFFRON_CITY_HGSS			0x94
#define MAPSEC_ROUTE_1_HGSS					0x95
#define MAPSEC_ROUTE_2_HGSS					0x96
#define MAPSEC_ROUTE_3_HGSS					0x97
#define MAPSEC_ROUTE_4_HGSS					0x98
#define MAPSEC_ROUTE_5_HGSS					0x99
#define MAPSEC_ROUTE_6_HGSS					0x9A
#define MAPSEC_ROUTE_7_HGSS					0x9B
#define MAPSEC_ROUTE_8_HGSS					0x9C
#define MAPSEC_ROUTE_9_HGSS					0x9D
#define MAPSEC_ROUTE_10_HGSS				0x9E
#define MAPSEC_ROUTE_11_HGSS				0x9F
#define MAPSEC_ROUTE_12_HGSS				0xA0
#define MAPSEC_ROUTE_13_HGSS				0xA1
#define MAPSEC_ROUTE_14_HGSS				0xA2
#define MAPSEC_ROUTE_15_HGSS				0xA3
#define MAPSEC_ROUTE_16_HGSS				0xA4
#define MAPSEC_ROUTE_17_HGSS				0xA5
#define MAPSEC_ROUTE_18_HGSS				0xA6
#define MAPSEC_ROUTE_19_HGSS				0xA7
#define MAPSEC_ROUTE_20_HGSS				0xA8
#define MAPSEC_ROUTE_21_HGSS				0xA9
#define MAPSEC_ROUTE_22_HGSS				0xAA
#define MAPSEC_ROUTE_23_HGSS				0xAB
#define MAPSEC_ROUTE_24_HGSS				0xAC
#define MAPSEC_ROUTE_25_HGSS				0xAD
#define MAPSEC_ROUTE_26						0xAE
#define MAPSEC_ROUTE_27						0xAF
#define MAPSEC_ROUTE_28						0xB0
#define MAPSEC_ROUTE_29						0xB1
#define MAPSEC_ROUTE_30						0xB2
#define MAPSEC_ROUTE_31						0xB3
#define MAPSEC_ROUTE_32						0xB4
#define MAPSEC_ROUTE_33						0xB5
#define MAPSEC_ROUTE_34						0xB6
#define MAPSEC_ROUTE_35						0xB7
#define MAPSEC_ROUTE_36						0xB8
#define MAPSEC_ROUTE_37						0xB9
#define MAPSEC_ROUTE_38						0xBA
#define MAPSEC_ROUTE_39						0xBB
#define MAPSEC_ROUTE_40						0xBC
#define MAPSEC_ROUTE_41						0xBD
#define MAPSEC_ROUTE_42						0xBE
#define MAPSEC_ROUTE_43						0xBF
#define MAPSEC_ROUTE_44						0xC0
#define MAPSEC_ROUTE_45						0xC1
#define MAPSEC_ROUTE_46						0xC2
#define MAPSEC_ROUTE_47						0xC3
#define MAPSEC_ROUTE_48						0xC4
#define MAPSEC_DIGLETTS_CAVE_HGSS			0xC5
#define MAPSEC_MT_MOON_HGSS					0xC6
#define MAPSEC_CERULEAN_CAVE_HGSS			0xC7
#define MAPSEC_ROCK_TUNNEL_HGSS				0xC8
#define MAPSEC_POWER_PLANT_HGSS				0xC9
#define MAPSEC_JOHTO_SAFARI_ZONE			0xCA
#define MAPSEC_SEAFOAM_ISLANDS_HGSS			0xCB
#define MAPSEC_SPROUT_TOWER					0xCC
#define MAPSEC_BELL_TOWER					0xCD
#define MAPSEC_BURNED_TOWER					0xCE
#define MAPSEC_NATIONAL_PARK				0xCF
#define MAPSEC_RADIO_TOWER					0xD0
#define MAPSEC_RUINS_OF_ALPH				0xD1
#define MAPSEC_UNION_CAVE					0xD2
#define MAPSEC_SLOWPOKE_WELL				0xD3
#define MAPSEC_LIGHTHOUSE					0xD4
#define MAPSEC_TEAM_ROCKET_HQ				0xD5
#define MAPSEC_ILEX_FOREST					0xD6
#define MAPSEC_GOLDENROD_TUNNEL				0xD7
#define MAPSEC_MT_MORTAR					0xD8
#define MAPSEC_ICE_PATH						0xD9
#define MAPSEC_WHIRL_ISLANDS				0xDA
#define MAPSEC_MT_SILVER_CAVE				0xDB
#define MAPSEC_DARK_CAVE					0xDC
#define MAPSEC_KANTO_VICTORY_ROAD_HGSS		0xDD
#define MAPSEC_DRAGONS_DEN					0xDE
#define MAPSEC_TOHJO_FALLS					0xDF
#define MAPSEC_VIRIDIAN_FOREST_HGSS			0xE0
#define MAPSEC_POKEATHLON_DOME				0xE1
#define MAPSEC_S_S_AQUA						0xE2
#define MAPSEC_SAFARI_ZONE_GATE				0xE3
#define MAPSEC_CLIFF_CAVE					0xE4
#define MAPSEC_FRONTIER_ACCESS				0xE5
#define MAPSEC_BELLCHIME_TRAIL				0xE6
#define MAPSEC_SINJOH_RUINS					0xE7
#define MAPSEC_EMBEDDED_TOWER				0xE8
#define MAPSEC_POKEWALKER					0xE9
#define MAPSEC_CLIFF_EDGE_GATE				0xEA

#define KANTO_MAPSEC_START					MAPSEC_PALLET_TOWN
#define KANTO_MAPSEC_END					MAPSEC_SPECIAL_AREA
#define KANTO_MAPSEC_COUNT					(KANTO_MAPSEC_END - KANTO_MAPSEC_START + 1)

#define JOHTO_MAPSEC_START					MAPSEC_NEW_BARK_TOWN_CD
#define JOHTO_MAPSEC_END					MAPSEC_TIN_TOWER_CD
#define JOHTO_MAPSEC_COUNT					(JOHTO_MAPSEC_END - JOHTO_MAPSEC_START + 1)

#define ORRE_MAPSEC_START					MAPSEC_DISTANT_LAND
#define ORRE_MAPSEC_END						MAPSEC_KAMINKOS_HOUSE
#define ORRE_MAPSEC_COUNT					(ORRE_MAPSEC_END - ORRE_MAPSEC_START + 1)

#define SINJOH_MAPSEC_START					MAPSEC_MYSTERY_ZONE
#define SINJOH_MAPSEC_END					MAPSEC_CLIFF_EDGE_GATE
#define SINJOH_MAPSEC_COUNT					(SINJOH_MAPSEC_END - SINJOH_MAPSEC_START + 1)

#endif //GUARD_REGIONMAPSEC_H
