name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install deps
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi
      - name: Compile
        run: sh build.sh
