gText_NurseIntro_Morning::
	.string "Good morning!\n"
	.string "Welcome to our Pokémon Center.$"

gText_NurseIntro_Day::
	.string "Hello!\n"
	.string "Welcome to our Pokémon Center.$"

gText_NurseIntro_Night::
	.string "Good evening! You're out late.\n"
	.string "Welcome to our Pokémon Center.$"

gText_WouldYouLikeToRestYourPkmn::
    .string "We restore your tired Pokémon\n"
    .string "to full health.\p"
    .string "Would you like to rest your Pokémon?$"

gText_IllTakeYourPkmn::
    .string "Okay, I'll take your Pokémon\n"
    .string "for a few seconds.$"

gText_RestoredPkmnToFullHealth::
    .string "Thank you for waiting.\p"
    .string "We've restored your Pokémon\n"
    .string "to full health.$"

gText_WeHopeToSeeYouAgain::
    .string "We hope to see you again!$"

gText_WelcomeCutShort::
	.string "Hello!\n"
	.string "Welcome to our Pokémon Center.\p$"
    .string "We restore your tired Pokémon\n"
    .string "to full health.\p"
    .string "Would you like to…$"

gText_NoticesGoldCard::
    .string "Th-that card…\n"
    .string "Could it be… The Gold Card?!\p"
    .string "Oh, the gold color is brilliant!\n"
    .string "The four stars seem to sparkle!\p"
    .string "I've seen several Trainers with\n"
    .string "a Silver Card before, but, {PLAYER},\l"
    .string "you're the first Trainer I've ever\l"
    .string "seen with a Gold Card!\p"
    .string "Okay, {PLAYER}, please allow me\n"
    .string "the honor of resting your Pokémon!$"

gText_YouWantTheUsual_Morning::
    .string "I hope you're having\n"
	.string "a great morning, {PLAYER}!\p"
    .string "You want the usual, am I right?$"

gText_YouWantTheUsual::
    .string "I'm delighted to see you, {PLAYER}!\n"
    .string "You want the usual, am I right?$"

gText_YouWantTheUsual_Night::
    .string "How's your night going {PLAYER}?\n"
    .string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
    .string "Okay, I'll take your Pokémon\n"
    .string "for a few seconds.$"

gText_ThankYouForWaiting::
    .string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
    .string "We hope to see you again!$"
