Common_EventScript_SetGymTrainers::
	switch VAR_0x8008
	case 1, RustboroCity_Gym_SetGymTrainers
	case 2, DewfordTown_Gym_SetGymTrainers
	case 3, MauvilleCity_Gym_SetGymTrainers
	case 4, LavaridgeTown_Gym_SetGymTrainers
	case 5, PetalburgCity_Gym_SetGymTrainers
	case 6, FortreeCity_Gym_SetGymTrainers
	case 7, MossdeepCity_Gym_SetGymTrainers
	case 8, SootopolisCity_Gym_SetGymTrainers
	end

RustboroCity_Gym_SetGymTrainers::
	settrainerflag Trainer_JOSH
	settrainerflag Trainer_TOMMY
	settrainerflag Trainer_MARC
	return

DewfordTown_Gym_SetGymTrainers::
	settrainerflag Trainer_TAKAO
	settrainerflag Trainer_JOCELYN
	settrainerflag Trainer_LAURA
	settrainerflag Trainer_BRENDEN
	settrainerflag Trainer_CRISTIAN
	settrainerflag Trainer_LILITH
	return

MauvilleCity_Gym_SetGymTrainers::
	settrainerflag Trainer_KIRK
	settrainerflag Trainer_SHAWN
	settrainerflag Trainer_BEN
	settrainerflag Trainer_VIVIAN
	settrainerflag Trainer_ANGELO
	return

LavaridgeTown_Gym_SetGymTrainers::
	settrainerflag Trainer_COLE
	settrainerflag Trainer_AXLE
	settrainerflag Trainer_KEEGAN
	settrainerflag Trainer_GERALD
	settrainerflag Trainer_DANIELLE
	settrainerflag Trainer_JACE
	settrainerflag Trainer_JEFF
	settrainerflag Trainer_ELI
	return

PetalburgCity_Gym_SetGymTrainers::
	settrainerflag Trainer_RANDALL
	settrainerflag Trainer_PARKER
	settrainerflag Trainer_GEORGE
	settrainerflag Trainer_BERKE
	settrainerflag Trainer_MARY
	settrainerflag Trainer_ALEXIA
	settrainerflag Trainer_JODY
	return

FortreeCity_Gym_SetGymTrainers::
	settrainerflag Trainer_JARED
	settrainerflag Trainer_FLINT
	settrainerflag Trainer_ASHLEY
	settrainerflag Trainer_EDWARDO
	settrainerflag Trainer_HUMBERTO
	settrainerflag Trainer_DARIUS
	return

MossdeepCity_Gym_SetGymTrainers::
	settrainerflag Trainer_PRESTON
	settrainerflag Trainer_VIRGIL
	settrainerflag Trainer_BLAKE
	settrainerflag Trainer_HANNAH
	settrainerflag Trainer_SAMANTHA
	settrainerflag Trainer_MAURA
	settrainerflag Trainer_SYLVIA
	settrainerflag Trainer_NATE
	settrainerflag Trainer_KATHLEEN
	settrainerflag Trainer_CLIFFORD
	settrainerflag Trainer_MACEY
	settrainerflag Trainer_NICHOLAS
	return

SootopolisCity_Gym_SetGymTrainers::
	settrainerflag Trainer_ANDREA
	settrainerflag Trainer_CRISSY
	settrainerflag Trainer_BRIANNA
	settrainerflag Trainer_CONNIE
	settrainerflag Trainer_BRIDGET
	settrainerflag Trainer_OLIVIA
	settrainerflag Trainer_TIFFANY
	settrainerflag Trainer_BETHANY
	settrainerflag Trainer_ANNIKA
	settrainerflag Trainer_DAPHNE
	return
