#ifndef GUARD_CONSTANTS_VARS_H
#define GUARD_CONSTANTS_VARS_H

#define VARS_START         0x4000
#define SPECIAL_VARS_START 0x8000

#define VARS_COUNT 256

#define VAR_PACIFIDLOG_TM_RECEIVED_DAY 0x40C2

#endif // GUARD_CONSTANTS_VARS_H
