#include "global.h"
#include "other_saves.h"
#include "save.h"
#include "union_room_chat.h"
#include "lilycove_lady.h"
#include "apprentice.h"
#include "frontier_util.h"
#include "match_call.h"
#include "trainer_hill.h"
#include "event_data.h"
#include "malloc.h"
#include "convert_save.h"
#include "item.h"
#include "load_save.h"
#include "overworld.h"
#include "constants/heal_locations.h"

/*
Need to look into
FLAG_MET_TEAM_AQUA_HARBOR
FLAG_WHITEOUT_TO_LAVARIDGE
RS_FLAG_LEGENDARY_BATTLE_COMPLETED
FLAG_SCOTT_CALL_BATTLE_FRONTIER
FLAG_DEFEATED_MAGMA_SPACE_CENTER
FLAG_LANDMARK_MIRAGE_TOWER
FLAG_REGISTER_RIVAL_POKENAV
FLAG_DEFEATED_RIVAL_ROUTE_104
FLAG_ENABLE_ROXANNE_FIRST_CALL
FLAG_ENABLE_FIRST_WALLY_POKENAV_CALL
FLAG_SCOTT_CALL_FORTREE_GYM
RS_FLAG_RECEIVED_CONTEST_PASS
FLAG_SOOTOPOLIS_ARCHIE_MAXIE_LEAVE
FLAG_INTERACTED_WITH_DEVON_EMPLOYEE_GOODS_STOLEN
FLAG_HIDE_SECRET_BASE_TRAINER
FLAG_DECORATION_*
FLAG_DEFEATED_GRUNT_SPACE_CENTER_1F
FLAG_TRICK_HOUSE_PUZZLE_7_SWITCH_*
FLAG_INTERACTED_WITH_STEVEN_SPACE_CENTER
FLAG_MET_ARCHIE_METEOR_FALLS
FLAG_DEFEATED_RIVAL_RUSTBORO
FLAG_RECEIVED_RED_OR_BLUE_ORB
RS_FLAG_ROUTE104_PROTOTYPE_COMPLETED_*
FLAG_ENABLE_WALLY_MATCH_CALL
FLAG_ENABLE_SCOTT_MATCH_CALL
FLAG_ENABLE_MOM_MATCH_CALL
FLAG_NEVER_SET_0x0DC
FLAG_ENABLE_RIVAL_MATCH_CALL
FLAG_ENABLE_PROF_BIRCH_MATCH_CALL
FLAG_HAS_MATCH_CALL
FLAG_ADDED_MATCH_CALL_TO_POKENAV
FLAG_REGISTERED_STEVEN_POKENAV
FLAG_ENABLE_NORMAN_MATCH_CALL
FLAG_STEVEN_GUIDES_TO_CAVE_OF_ORIGIN
FLAG_MET_ARCHIE_SOOTOPOLIS
FLAG_MET_MAXIE_SOOTOPOLIS
FLAG_MET_SCOTT_RUSTBORO
FLAG_WALLACE_GOES_TO_SKY_PILLAR
FLAG_RECEIVED_HM07
FLAG_BEAT_MAGMA_GRUNT_JAGGED_PASS
FLAG_RECEIVED_POWDER_JAR
FLAG_ENTERED_CONTEST
FLAG_MET_SLATEPORT_FANCLUB_CHAIRMAN
FLAG_ENABLE_MR_STONE_POKENAV
FLAG_MATCH_CALL_REGISTERED
FLAG_SHOWN_EON_TICKET
FLAG_DEFEATED_*
FLAG_MET_SCOTT_IN_*
FLAG_ENABLE_*_MATCH_CALL
FLAG_HIDE_APPRENTICE
FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
RS_FLAG_HIDE_STEVENS_LETTER
FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_INVISIBLE_NINJA_BOY
FLAG_HIDE_LILYCOVE_FAN_CLUB_INTERVIEWER
FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_SIBLING
FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_MAGMA_NOTE
FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_BRENDAN
FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_MAY
FLAG_HIDE_SAFARI_ZONE_SOUTH_EAST_EXPANSION
FLAG_HIDE_LILYCOVE_HARBOR_EVENT_TICKET_TAKER
FLAG_HIDE_SLATEPORT_CITY_SCOTT
FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_1F_STEVEN
FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_1F_TEAM_MAGMA
FLAG_HIDE_MAUVILLE_CITY_SCOTT
FLAG_HIDE_VERDANTURF_TOWN_SCOTT
FLAG_HIDE_FALLARBOR_TOWN_BATTLE_TENT_SCOTT
FLAG_HIDE_MARINE_CAVE_KYOGRE
FLAG_HIDE_TERRA_CAVE_GROUDON
FLAG_HIDE_ROUTE_119_SCOTT
FLAG_HIDE_LILYCOVE_MOTEL_SCOTT
FLAG_HIDE_MOSSDEEP_CITY_SCOTT
FLAG_HIDE_EVER_GRANDE_POKEMON_CENTER_1F_SCOTT
FLAG_HIDE_LITTLEROOT_TOWN_RIVAL
FLAG_HIDE_LITTLEROOT_TOWN_BIRCH
RS_FLAG_HIDE_CONTEST_REPORTER_FALLARBOR
RS_FLAG_HIDE_CONTEST_REPORTER_VERDANTURF
FLAG_HIDE_SS_TIDAL_CORRIDOR_SCOTT
RS_FLAG_HIDE_WALLY_FATHER_PETALBURG
FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_CYNDAQUIL
RS_FLAG_HIDE_WALLY_MOTHER_PETALBURG
FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_TOTODILE
RS_FLAG_HIDE_WALLACE_SOOTOPOLIS_GYM
FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_SWABLU_DOLL
FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_POKE_BALL
FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_2F_POKE_BALL
FLAG_HIDE_CAVE_OF_ORIGIN_B1F_WALLACE
FLAG_HIDE_MOSSDEEP_CITY_TEAM_MAGMA
FLAG_HIDE_PETALBURG_GYM_WALLYS_DAD
FLAG_HIDE_SOOTOPOLIS_CITY_ARCHIE
FLAG_HIDE_SOOTOPOLIS_CITY_MAXIE
FLAG_HIDE_PETALBURG_CITY_WALLYS_DAD
FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER
FLAG_HIDE_ROUTE_110_BIRCH
FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_CHIKORITA
FLAG_HIDE_SOOTOPOLIS_CITY_MAN_1
FLAG_HIDE_ROUTE_111_ROCK_SMASH_TIP_GUY
FLAG_HIDE_RUSTBORO_CITY_SCIENTIST
FLAG_HIDE_JAGGED_PASS_MAGMA_GUARD
FLAG_HIDE_MAGMA_HIDEOUT_4F_GROUDON_ASLEEP
FLAG_HIDE_MAGMA_HIDEOUT_4F_GROUDON
RS_FLAG_HIDE_CAVE_OF_ORIGIN_ENTRANCE_WOMAN_1
RS_FLAG_HIDE_CAVE_OF_ORIGIN_ENTRANCE_WOMAN_2
FLAG_HIDE_SKY_PILLAR_WALLACE
FLAG_HIDE_MT_PYRE_SUMMIT_MAXIE
FLAG_HIDE_MAGMA_HIDEOUT_GRUNTS
FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_TEAM_MAGMA
FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_STEVEN
FLAG_HIDE_BATTLE_TOWER_MULTI_BATTLE_PARTNER_ALT_1
FLAG_HIDE_BATTLE_TOWER_MULTI_BATTLE_PARTNER_ALT_2
FLAG_UNKNOWN_0x363
FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER_REPLACEMENT
FLAG_HIDE_ROUTE_111_PLAYER_DESCENT
FLAG_HIDE_ROUTE_111_DESERT_FOSSIL
FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_UNKNOWN_0x380
RS_FLAG_HIDE_LATIOS_OR_LATIAS_FLYING
FLAG_HIDE_SOUTHERN_ISLAND_EON_STONE
RS_FLAG_HIDE_LATIOS_OR_LATIAS_STATIONARY
FLAG_HIDE_SOUTHERN_ISLAND_UNCHOSEN_EON_DUO_MON
FLAG_UNKNOWN_0x393
RS_FLAG_HIDE_AWARD_MAN_BATTLE_TOWER
FLAG_HIDE_SEAFLOOR_CAVERN_ENTRANCE_AQUA_GRUNT
FLAG_HIDE_WEATHER_INSTITUTE_2F_AQUA_GRUNT_M
FLAG_HIDE_LILYCOVE_POKEMON_CENTER_CONTEST_LADY_MON
FLAG_HIDE_MT_CHIMNEY_LAVA_COOKIE_LADY
FLAG_HIDE_PETALBURG_CITY_SCOTT
FLAG_HIDE_SOOTOPOLIS_CITY_RAYQUAZA
FLAG_HIDE_SOOTOPOLIS_CITY_KYOGRE
FLAG_HIDE_SOOTOPOLIS_CITY_GROUDON
FLAG_HIDE_RUSTBORO_CITY_POKEMON_SCHOOL_SCOTT
FLAG_DEFEATED_METEOR_FALLS_STEVEN
FLAG_IS_CHAMPION
FLAG_NURSE_UNION_ROOM_REMINDER
RS_FLAG_SYS_NATIONAL_DEX


Reset all items?
Trainer flag convert
Vars




static const u16 sRSFlagsToNLFlags[] = {
    [RS_FLAG_SET_WALL_CLOCK]                             = FLAG_SET_WALL_CLOCK,
    [RS_FLAG_RESCUED_BIRCH]                              = FLAG_RESCUED_BIRCH,
    [RS_FLAG_LINK_CONTEST_ROOM_POKEBALL]                 = FLAG_HIDE_CONTEST_POKE_BALL,
    [RS_FLAG_MET_RIVAL_MOM]                              = FLAG_MET_RIVAL_MOM,
    [RS_FLAG_BIRCH_AIDE_MET]                             = FLAG_BIRCH_AIDE_MET,
    [RS_FLAG_DECLINED_BIKE]                              = FLAG_DECLINED_BIKE,
    [RS_FLAG_RECEIVED_BIKE]                              = FLAG_RECEIVED_BIKE,
    [RS_FLAG_RECEIVED_WAILMER_PAIL]                      = FLAG_RECEIVED_WAILMER_PAIL,
    [RS_FLAG_RECEIVED_POKEBLOCK_CASE]                    = FLAG_RECEIVED_POKEBLOCK_CASE,
    [RS_FLAG_RECEIVED_SECRET_POWER]                      = FLAG_RECEIVED_SECRET_POWER,
    [RS_FLAG_TV_EXPLAINED]                               = FLAG_TV_EXPLAINED,
    [RS_FLAG_MAUVILLE_GYM_BARRIERS_STATE]                = FLAG_MAUVILLE_GYM_BARRIERS_STATE,
    [RS_FLAG_MOSSDEEP_GYM_SWITCH_1]                      = FLAG_MOSSDEEP_GYM_SWITCH_1,
    [RS_FLAG_MOSSDEEP_GYM_SWITCH_2]                      = FLAG_MOSSDEEP_GYM_SWITCH_2,
    [RS_FLAG_MOSSDEEP_GYM_SWITCH_3]                      = FLAG_MOSSDEEP_GYM_SWITCH_3,
    [RS_FLAG_MOSSDEEP_GYM_SWITCH_4]                      = FLAG_MOSSDEEP_GYM_SWITCH_4,
    [RS_FLAG_OCEANIC_MUSEUM_MET_REPORTER]                = FLAG_OCEANIC_MUSEUM_MET_REPORTER,
    [RS_FLAG_RECEIVED_HM04]                              = FLAG_RECEIVED_HM_STRENGTH,
    [RS_FLAG_RECEIVED_HM06]                              = FLAG_RECEIVED_HM_ROCK_SMASH,
    [RS_FLAG_RECEIVED_HM02]                              = FLAG_RECEIVED_HM_FLY,
    [RS_FLAG_RECEIVED_HM05]                              = FLAG_RECEIVED_HM_FLASH,
    [RS_FLAG_MT_PYRE_ORB_STOLEN]                         = FLAG_GROUDON_AWAKENED_MAGMA_HIDEOUT,
    [RS_FLAG_EVIL_TEAM_ESCAPED_IN_SUBMARINE]             = FLAG_TEAM_AQUA_ESCAPED_IN_SUBMARINE,
    [RS_FLAG_LEGENDARY_BATTLE_COMPLETED]                 = 
    [RS_FLAG_RECEIVED_METEORITE]                         = FLAG_RECEIVED_METEORITE,
    [RS_FLAG_ADVENTURE_STARTED]                          = FLAG_ADVENTURE_STARTED,
    [RS_FLAG_MET_HIDDEN_POWER_GIVER]                     = FLAG_MET_HIDDEN_POWER_GIVER,
    [RS_FLAG_RECEIVED_TM31]                              = FLAG_RECEIVED_TM_BRICK_BREAK,
    [RS_FLAG_RECEIVED_HM03]                              = FLAG_RECEIVED_HM_SURF,
    [RS_FLAG_RECEIVED_HM08]                              = FLAG_RECEIVED_HM_DIVE,
    [RS_FLAG_DEFEATED_WALLY_VICTORY_ROAD]                = FLAG_DEFEATED_WALLY_VICTORY_ROAD,
    [RS_FLAG_MET_PRETTY_PETAL_SHOP_OWNER]                = FLAG_MET_PRETTY_PETAL_SHOP_OWNER,
    [RS_FLAG_LEGEND_ESCAPED_SEAFLOOR_CAVERN]             = FLAG_KYOGRE_ESCAPED_SEAFLOOR_CAVERN,
    [RS_FLAG_DEFEATED_RIVAL_ROUTE103]                    = FLAG_DEFEATED_RIVAL_ROUTE103,
    [RS_FLAG_RECEIVED_DOLL_LANETTE]                      = FLAG_RECEIVED_DOLL_LANETTE,
    [RS_FLAG_RECEIVED_POTION_OLDALE]                     = FLAG_RECEIVED_POTION_OLDALE,
    [RS_FLAG_RECEIVED_AMULET_COIN]                       = FLAG_RECEIVED_AMULET_COIN,
    [RS_FLAG_PENDING_DAYCARE_EGG]                        = FLAG_PENDING_DAYCARE_EGG,
    [RS_FLAG_THANKED_FOR_PLAYING_WITH_WALLY]             = FLAG_THANKED_FOR_PLAYING_WITH_WALLY,
    [RS_FLAG_RECEIVED_HM01]                              = FLAG_RECEIVED_HM_CUT,
    [RS_FLAG_DEFEATED_EVIL_TEAM_MT_CHIMNEY]              = FLAG_DEFEATED_EVIL_TEAM_MT_CHIMNEY,
    [RS_FLAG_RECEIVED_6_SODA_POP]                        = FLAG_RECEIVED_6_SODA_POP,
    [RS_FLAG_DEFEATED_SEASHORE_HOUSE_TRAINERS]           = FLAG_DEFEATED_SEASHORE_HOUSE,
    [RS_FLAG_DEVON_GOODS_STOLEN]                         = FLAG_DEVON_GOODS_STOLEN,
    [RS_FLAG_RECOVERED_DEVON_GOODS]                      = FLAG_RECOVERED_DEVON_GOODS,
    [RS_FLAG_RETURNED_DEVON_GOODS]                       = FLAG_RETURNED_DEVON_GOODS,
    [RS_FLAG_MR_BRINEY_SAILING_INTRO]                    = FLAG_MR_BRINEY_SAILING_INTRO,
    [RS_FLAG_DOCK_REJECTED_DEVON_GOODS]                  = FLAG_DOCK_REJECTED_DEVON_GOODS,
    [RS_FLAG_DELIVERED_DEVON_GOODS]                      = FLAG_DELIVERED_DEVON_GOODS,
    [RS_FLAG_RECEIVED_CONTEST_PASS]                      = 
    [RS_FLAG_RECEIVED_CASTFORM]                          = FLAG_RECEIVED_CASTFORM,
    [RS_FLAG_RECEIVED_SUPER_ROD]                         = FLAG_RECEIVED_SUPER_ROD,
    [RS_FLAG_RUSTBORO_NPC_TRADE_COMPLETED]               = 
    [RS_FLAG_PACIFIDLOG_NPC_TRADE_COMPLETED]             = 
    [RS_FLAG_FORTREE_NPC_TRADE_COMPLETED]                = 
    [RS_FLAG_UNKNOWN_9F]                                 = 
    [RS_FLAG_COOL_PAINTING_MADE]                         = FLAG_COOL_PAINTING_MADE,
    [RS_FLAG_BEAUTY_PAINTING_MADE]                       = FLAG_BEAUTY_PAINTING_MADE,
    [RS_FLAG_CUTE_PAINTING_MADE]                         = FLAG_CUTE_PAINTING_MADE,
    [RS_FLAG_SMART_PAINTING_MADE]                        = FLAG_SMART_PAINTING_MADE,
    [RS_FLAG_TOUGH_PAINTING_MADE]                        = FLAG_TOUGH_PAINTING_MADE,
    [RS_FLAG_RECEIVED_TM39]                              = FLAG_RECEIVED_TM_ROCK_TOMB,
    [RS_FLAG_RECEIVED_TM08]                              = FLAG_RECEIVED_TM_BULK_UP,
    [RS_FLAG_RECEIVED_TM34]                              = FLAG_RECEIVED_TM_SHOCK_WAVE,
    [RS_FLAG_RECEIVED_TM50]                              = FLAG_RECEIVED_TM_OVERHEAT,
    [RS_FLAG_RECEIVED_TM42]                              = FLAG_RECEIVED_TM_FACADE,
    [RS_FLAG_RECEIVED_TM40]                              = FLAG_RECEIVED_TM_AERIAL_ACE,
    [RS_FLAG_RECEIVED_TM04]                              = FLAG_RECEIVED_TM_CALM_MIND,
    [RS_FLAG_RECEIVED_TM03]                              = FLAG_RECEIVED_TM_WATER_PULSE,
    [RS_FLAG_DECORATION_1]                               = FLAG_HIDE_SECRET_BASE_TRAINER,
    [RS_FLAG_DECORATION_2]                               = FLAG_DECORATION_1,
    [RS_FLAG_DECORATION_3]                               = FLAG_DECORATION_2,
    [RS_FLAG_DECORATION_4]                               = FLAG_DECORATION_3,
    [RS_FLAG_DECORATION_5]                               = FLAG_DECORATION_4,
    [RS_FLAG_DECORATION_6]                               = FLAG_DECORATION_5,
    [RS_FLAG_DECORATION_7]                               = FLAG_DECORATION_6,
    [RS_FLAG_DECORATION_8]                               = FLAG_DECORATION_7,
    [RS_FLAG_DECORATION_9]                               = FLAG_DECORATION_8,
    [RS_FLAG_DECORATION_10]                              = FLAG_DECORATION_9,
    [RS_FLAG_DECORATION_11]                              = FLAG_DECORATION_10,
    [RS_FLAG_DECORATION_12]                              = FLAG_DECORATION_11,
    [RS_FLAG_DECORATION_13]                              = FLAG_DECORATION_12,
    [RS_FLAG_DECORATION_14]                              = FLAG_DECORATION_13,
    [RS_FLAG_DECORATION_15]                              = FLAG_DECORATION_14,
    [RS_FLAG_RECEIVED_POKENAV]                           = FLAG_RECEIVED_POKENAV,
    [RS_FLAG_DELIVERED_STEVEN_LETTER]                    = FLAG_DELIVERED_STEVEN_LETTER,
    [RS_FLAG_DEFEATED_WALLY_MAUVILLE]                    = FLAG_DEFEATED_WALLY_MAUVILLE,
    [RS_FLAG_RECEIVED_SUN_STONE_MOSSDEEP]                = FLAG_RECEIVED_SUN_STONE_MOSSDEEP,
    [RS_FLAG_WALLY_SPEECH]                               = FLAG_WALLY_SPEECH,
    [RS_FLAG_TRICK_HOUSE_PUZZLE_7_SWITCH_1]              = 
    [RS_FLAG_TRICK_HOUSE_PUZZLE_7_SWITCH_2]              = 
    [RS_FLAG_TRICK_HOUSE_PUZZLE_7_SWITCH_3]              = 
    [RS_FLAG_TRICK_HOUSE_PUZZLE_7_SWITCH_4]              = 
    [RS_FLAG_TRICK_HOUSE_PUZZLE_7_SWITCH_5]              = 
    [RS_FLAG_RUSTURF_TUNNEL_OPENED]                      = FLAG_RUSTURF_TUNNEL_OPENED,
    [RS_FLAG_RECEIVED_RED_SCARF]                         = FLAG_RECEIVED_RED_SCARF,
    [RS_FLAG_RECEIVED_BLUE_SCARF]                        = FLAG_RECEIVED_BLUE_SCARF,
    [RS_FLAG_RECEIVED_PINK_SCARF]                        = FLAG_RECEIVED_PINK_SCARF,
    [RS_FLAG_RECEIVED_GREEN_SCARF]                       = FLAG_RECEIVED_GREEN_SCARF,
    [RS_FLAG_RECEIVED_YELLOW_SCARF]                      = FLAG_RECEIVED_YELLOW_SCARF,
    [RS_FLAG_ENCOUNTERED_LATIAS_OR_LATIOS]               = FLAG_ENCOUNTERED_LATIAS_OR_LATIOS,
    [RS_FLAG_RECEIVED_BASEMENT_KEY]                      = FLAG_GOT_BASEMENT_KEY_FROM_WATTSON,
    [RS_FLAG_RECEIVED_TM24]                              = FLAG_GOT_TM_THUNDERBOLT_FROM_WATTSON,
    [RS_FLAG_RECEIVED_RED_OR_BLUE_ORB]                   = FLAG_RECEIVED_RED_OR_BLUE_ORB,
    [RS_FLAG_RECEIVED_PREMIER_BALL_RUSTBORO]             = FLAG_RECEIVED_PREMIER_BALL_RUSTBORO,
    [RS_FLAG_ROUTE104_PROTOTYPE_COMPLETED_1]             = 
    [RS_FLAG_ROUTE104_PROTOTYPE_COMPLETED_2]             = 
    [RS_FLAG_MET_DIVING_TREASURE_HUNTER]                 = FLAG_MET_DIVING_TREASURE_HUNTER,
    [RS_FLAG_MET_WAILMER_TRAINER]                        = FLAG_MET_WAILMER_TRAINER,
    [RS_FLAG_EVIL_LEADER_PLEASE_STOP]                    = FLAG_EVIL_LEADER_PLEASE_STOP,
    [RS_FLAG_RECEIVED_GO_GOGGLES]                        = FLAG_RECEIVED_GO_GOGGLES,
    [RS_FLAG_WINGULL_SENT_ON_ERRAND]                     = FLAG_WINGULL_SENT_ON_ERRAND,
    [RS_FLAG_RECEIVED_MENTAL_HERB]                       = FLAG_RECEIVED_MENTAL_HERB,
    [RS_FLAG_WINGULL_DELIVERED_MAIL]                     = FLAG_WINGULL_DELIVERED_MAIL,
    [RS_FLAG_RECEIVED_20_COINS]                          = FLAG_RECEIVED_20_COINS,
    [RS_FLAG_RECEIVED_STARTER_DOLL]                      = FLAG_RECEIVED_STARTER_DOLL,
    [RS_FLAG_RECEIVED_GOOD_ROD]                          = FLAG_RECEIVED_GOOD_ROD,
    [RS_FLAG_REGI_DOORS_OPENED]                          = FLAG_REGI_DOORS_OPENED,
    [RS_FLAG_RECEIVED_TM27]                              = FLAG_RECEIVED_TM_RETURN,
    [RS_FLAG_RECEIVED_TM36]                              = FLAG_RECEIVED_TM_SLUDGE_BOMB,
    [RS_FLAG_RECEIVED_TM05]                              = FLAG_RECEIVED_TM_ROAR,
    [RS_FLAG_RECEIVED_TM19]                              = FLAG_RECEIVED_TM_GIGA_DRAIN,
    [RS_FLAG_RECEIVED_TM44]                              = FLAG_RECEIVED_TM_REST,
    [RS_FLAG_RECEIVED_TM45]                              = FLAG_RECEIVED_TM_ATTRACT,
    [RS_FLAG_RECEIVED_GLASS_ORNAMENT]                    = FLAG_RECEIVED_GLASS_ORNAMENT,
    [RS_FLAG_RECEIVED_SILVER_SHIELD]                     = FLAG_RECEIVED_SILVER_SHIELD,
    [RS_FLAG_RECEIVED_GOLD_SHIELD]                       = FLAG_RECEIVED_GOLD_SHIELD,
    [RS_FLAG_USED_STORAGE_KEY]                           = FLAG_USED_STORAGE_KEY,
    [RS_FLAG_USED_ROOM_1_KEY]                            = FLAG_USED_ROOM_1_KEY,
    [RS_FLAG_USED_ROOM_2_KEY]                            = FLAG_USED_ROOM_2_KEY,
    [RS_FLAG_USED_ROOM_4_KEY]                            = FLAG_USED_ROOM_4_KEY,
    [RS_FLAG_USED_ROOM_6_KEY]                            = FLAG_USED_ROOM_6_KEY,
    [RS_FLAG_MET_PROF_COSMO]                             = FLAG_MET_PROF_COZMO,
    [RS_FLAG_RECEIVED_WAILMER_DOLL]                      = FLAG_RECEIVED_WAILMER_DOLL,
    [RS_FLAG_RECEIVED_CHESTO_BERRY_ROUTE104]             = FLAG_RECEIVED_CHESTO_BERRY_ROUTE_104,
    [RS_FLAG_DEFEATED_SS_TIDAL_TRAINERS]                 = FLAG_DEFEATED_SS_TIDAL_TRAINERS,
    [RS_FLAG_RECEIVED_SPELON_BERRY]                      = FLAG_RECEIVED_SPELON_BERRY,
    [RS_FLAG_RECEIVED_PAMTRE_BERRY]                      = FLAG_RECEIVED_PAMTRE_BERRY,
    [RS_FLAG_RECEIVED_WATMEL_BERRY]                      = FLAG_RECEIVED_WATMEL_BERRY,
    [RS_FLAG_RECEIVED_DURIN_BERRY]                       = FLAG_RECEIVED_DURIN_BERRY,
    [RS_FLAG_RECEIVED_BELUE_BERRY]                       = FLAG_RECEIVED_BELUE_BERRY,
    [RS_FLAG_RECEIVED_CHARCOAL]                          = FLAG_RECEIVED_CHARCOAL,
    [RS_FLAG_LATIOS_OR_LATIAS_ROAMING]                   = FLAG_LATIOS_OR_LATIAS_ROAMING,
    [RS_FLAG_RECEIVED_REPEAT_BALL]                       = FLAG_RECEIVED_REPEAT_BALL,
    [RS_FLAG_RECEIVED_OLD_ROD]                           = FLAG_RECEIVED_OLD_ROD,
    [RS_FLAG_RECEIVED_COIN_CASE]                         = FLAG_RECEIVED_COIN_CASE,
    [RS_FLAG_RETURNED_RED_OR_BLUE_ORB]                   = FLAG_RETURNED_RED_OR_BLUE_ORB,
    [RS_FLAG_RECEIVED_TM49]                              = FLAG_RECEIVED_TM_SNATCH,
    [RS_FLAG_RECEIVED_TM28]                              = FLAG_RECEIVED_TM_DIG,
    [RS_FLAG_RECEIVED_TM09]                              = FLAG_RECEIVED_TM_BULLET_SEED,
    [RS_FLAG_ENTERED_ELITE_FOUR]                         = FLAG_ENTERED_ELITE_FOUR,
    [RS_FLAG_RECEIVED_TM10]                              = FLAG_RECEIVED_TM_HIDDEN_POWER,
    [RS_FLAG_RECEIVED_TM41]                              = FLAG_RECEIVED_TM_TORMENT,
    [RS_FLAG_RECEIVED_LAVARIDGE_EGG]                     = FLAG_RECEIVED_LAVARIDGE_EGG,
    [RS_FLAG_RECEIVED_FOSSIL_MON]                        = FLAG_RECEIVED_REVIVED_FOSSIL_MON,
    [RS_FLAG_SECRET_BASE_REGISTRY_ENABLED]               = FLAG_SECRET_BASE_REGISTRY_ENABLED,
    [RS_FLAG_RECEIVED_TM46]                              = FLAG_RECEIVED_TM_THIEF,
    [RS_FLAG_CONTEST_SKETCH_CREATED]                     = FLAG_CONTEST_SKETCH_CREATED,
    [RS_FLAG_EVIL_TEAM_ESCAPED_STERN_SPOKE]              = FLAG_EVIL_TEAM_ESCAPED_STERN_SPOKE,
    [RS_FLAG_RECEIVED_EXP_SHARE]                         = FLAG_RECEIVED_EXP_SHARE,
    [RS_FLAG_POKERUS_EXPLAINED]                          = FLAG_POKERUS_EXPLAINED,
    [RS_FLAG_RECEIVED_RUNNING_SHOES]                     = FLAG_RECEIVED_RUNNING_SHOES,
    [RS_FLAG_RECEIVED_QUICK_CLAW]                        = FLAG_RECEIVED_QUICK_CLAW,
    [RS_FLAG_RECEIVED_KINGS_ROCK]                        = FLAG_RECEIVED_KINGS_ROCK,
    [RS_FLAG_RECEIVED_MACHO_BRACE]                       = FLAG_RECEIVED_MACHO_BRACE,
    [RS_FLAG_RECEIVED_SOOTHE_BELL]                       = FLAG_RECEIVED_SOOTHE_BELL,
    [RS_FLAG_RECEIVED_WHITE_HERB]                        = FLAG_RECEIVED_WHITE_HERB,
    [RS_FLAG_RECEIVED_SOFT_SAND]                         = FLAG_RECEIVED_SOFT_SAND,
    [RS_FLAG_RECEIVED_CLEANSE_TAG]                       = FLAG_RECEIVED_CLEANSE_TAG,
    [RS_FLAG_RECEIVED_FOCUS_BAND]                        = FLAG_RECEIVED_FOCUS_BAND,
    [RS_FLAG_DECLINED_WALLY_BATTLE_MAUVILLE]             = FLAG_DECLINED_WALLY_BATTLE_MAUVILLE,
    [RS_FLAG_RECEIVED_DEVON_SCOPE]                       = FLAG_RECEIVED_DEVON_SCOPE,
    [RS_FLAG_DECLINED_RIVAL_BATTLE_LILYCOVE]             = FLAG_DECLINED_RIVAL_BATTLE_LILYCOVE,
    [RS_FLAG_MET_DEVON_EMPLOYEE]                         = FLAG_MET_DEVON_EMPLOYEE,
    [RS_FLAG_MET_RIVAL_RUSTBORO]                         = FLAG_MET_RIVAL_RUSTBORO,
    [RS_FLAG_RECEIVED_SILK_SCARF]                        = FLAG_RECEIVED_SILK_SCARF,
    [RS_FLAG_NOT_READY_FOR_BATTLE_ROUTE120]              = FLAG_NOT_READY_FOR_BATTLE_ROUTE_120,
    [RS_FLAG_RECEIVED_SS_TICKET]                         = FLAG_RECEIVED_SS_TICKET,
    [RS_FLAG_MET_RIVAL_LILYCOVE]                         = FLAG_MET_RIVAL_LILYCOVE,
    [RS_FLAG_MET_RIVAL_IN_HOUSE_AFTER_LILYCOVE]          = FLAG_MET_RIVAL_IN_HOUSE_AFTER_LILYCOVE,
    [RS_FLAG_EXCHANGED_SCANNER]                          = FLAG_EXCHANGED_SCANNER,
    [RS_FLAG_KECLEON_FLED_FORTREE]                       = FLAG_KECLEON_FLED_FORTREE,
    [RS_FLAG_PETALBURG_MART_EXPANDED_ITEMS]              = FLAG_PETALBURG_MART_EXPANDED_ITEMS,
    [RS_FLAG_RECEIVED_MIRACLE_SEED]                      = FLAG_RECEIVED_MIRACLE_SEED,
    [RS_FLAG_RECEIVED_BELDUM]                            = FLAG_RECEIVED_BELDUM,
    [RS_FLAG_RECEIVED_FANCLUB_TM_THIS_WEEK]              = FLAG_RECEIVED_FANCLUB_TM_THIS_WEEK,
    [RS_FLAG_MET_FANCLUB_YOUNGER_BROTHER]                = FLAG_MET_FANCLUB_YOUNGER_BROTHER,
    [RS_FLAG_RIVAL_LEFT_FOR_ROUTE103]                    = FLAG_RIVAL_LEFT_FOR_ROUTE103,
    [RS_FLAG_OMIT_DIVE_FROM_STEVEN_LETTER]               = FLAG_OMIT_DIVE_FROM_STEVEN_LETTER,
    [RS_FLAG_HIDDEN_ITEM_0]                              = FLAG_HIDDEN_ITEM_LAVARIDGE_TOWN_ICE_HEAL,
    [RS_FLAG_HIDDEN_ITEM_1]                              = FLAG_HIDDEN_ITEM_TRICK_HOUSE_NUGGET,
    [RS_FLAG_HIDDEN_ITEM_2]                              = FLAG_HIDDEN_ITEM_ROUTE_111_STARDUST,
    [RS_FLAG_HIDDEN_ITEM_3]                              = FLAG_HIDDEN_ITEM_ROUTE_113_ETHER,
    [RS_FLAG_HIDDEN_ITEM_4]                              = FLAG_HIDDEN_ITEM_ROUTE_114_CARBOS,
    [RS_FLAG_HIDDEN_ITEM_5]                              = FLAG_HIDDEN_ITEM_ROUTE_119_CALCIUM,
    [RS_FLAG_HIDDEN_ITEM_6]                              = FLAG_HIDDEN_ITEM_ROUTE_119_ULTRA_BALL,
    [RS_FLAG_HIDDEN_ITEM_7]                              = FLAG_HIDDEN_ITEM_ROUTE_123_SUPER_REPEL,
    [RS_FLAG_HIDDEN_ITEM_8]                              = FLAG_HIDDEN_ITEM_UNDERWATER_124_CARBOS,
    [RS_FLAG_HIDDEN_ITEM_9]                              = FLAG_HIDDEN_ITEM_UNDERWATER_124_GREEN_SHARD,
    [RS_FLAG_HIDDEN_ITEM_A]                              = FLAG_HIDDEN_ITEM_UNDERWATER_124_PEARL,
    [RS_FLAG_HIDDEN_ITEM_B]                              = FLAG_HIDDEN_ITEM_UNDERWATER_124_BIG_PEARL,
    [RS_FLAG_HIDDEN_ITEM_C]                              = FLAG_HIDDEN_ITEM_UNDERWATER_126_BLUE_SHARD,
    [RS_FLAG_HIDDEN_ITEM_D]                              = FLAG_HIDDEN_ITEM_UNDERWATER_124_HEART_SCALE_1,
    [RS_FLAG_HIDDEN_ITEM_E]                              = FLAG_HIDDEN_ITEM_UNDERWATER_126_HEART_SCALE,
    [RS_FLAG_HIDDEN_ITEM_F]                              = FLAG_HIDDEN_ITEM_UNDERWATER_126_ULTRA_BALL,
    [RS_FLAG_HIDDEN_ITEM_10]                             = FLAG_HIDDEN_ITEM_UNDERWATER_126_STARDUST,
    [RS_FLAG_HIDDEN_ITEM_11]                             = FLAG_HIDDEN_ITEM_UNDERWATER_126_PEARL,
    [RS_FLAG_HIDDEN_ITEM_12]                             = FLAG_HIDDEN_ITEM_UNDERWATER_126_YELLOW_SHARD,
    [RS_FLAG_HIDDEN_ITEM_13]                             = FLAG_HIDDEN_ITEM_UNDERWATER_126_IRON,
    [RS_FLAG_HIDDEN_ITEM_14]                             = FLAG_HIDDEN_ITEM_UNDERWATER_126_BIG_PEARL,
    [RS_FLAG_HIDDEN_ITEM_15]                             = FLAG_HIDDEN_ITEM_UNDERWATER_127_STAR_PIECE,
    [RS_FLAG_HIDDEN_ITEM_16]                             = FLAG_HIDDEN_ITEM_UNDERWATER_127_HP_UP,
    [RS_FLAG_HIDDEN_ITEM_17]                             = FLAG_HIDDEN_ITEM_UNDERWATER_127_HEART_SCALE,
    [RS_FLAG_HIDDEN_ITEM_18]                             = FLAG_HIDDEN_ITEM_UNDERWATER_127_RED_SHARD,
    [RS_FLAG_HIDDEN_ITEM_19]                             = FLAG_HIDDEN_ITEM_UNDERWATER_128_PROTEIN,
    [RS_FLAG_HIDDEN_ITEM_1A]                             = FLAG_HIDDEN_ITEM_UNDERWATER_128_PEARL,
    [RS_FLAG_HIDDEN_ITEM_1B]                             = FLAG_HIDDEN_ITEM_LILYCOVE_CITY_HEART_SCALE,
    [RS_FLAG_HIDDEN_ITEM_1C]                             = FLAG_HIDDEN_ITEM_FALLARBOR_TOWN_NUGGET,
    [RS_FLAG_HIDDEN_ITEM_1D]                             = FLAG_HIDDEN_ITEM_MT_PYRE_EXTERIOR_ULTRA_BALL,
    [RS_FLAG_HIDDEN_ITEM_1E]                             = FLAG_HIDDEN_ITEM_ROUTE_113_TM_DOUBLE_TEAM,
    [RS_FLAG_HIDDEN_ITEM_1F]                             = FLAG_HIDDEN_ITEM_ABANDONED_SHIP_RM_1_KEY,
    [RS_FLAG_HIDDEN_ITEM_20]                             = FLAG_HIDDEN_ITEM_ABANDONED_SHIP_RM_2_KEY,
    [RS_FLAG_HIDDEN_ITEM_21]                             = FLAG_HIDDEN_ITEM_ABANDONED_SHIP_RM_4_KEY,
    [RS_FLAG_HIDDEN_ITEM_22]                             = FLAG_HIDDEN_ITEM_ABANDONED_SHIP_RM_6_KEY,
    [RS_FLAG_HIDDEN_ITEM_23]                             = FLAG_HIDDEN_ITEM_SS_TIDAL_LOWER_DECK_LEFTOVERS,
    [RS_FLAG_HIDDEN_ITEM_24]                             = FLAG_HIDDEN_ITEM_UNDERWATER_124_CALCIUM,
    [RS_FLAG_HIDDEN_ITEM_25]                             = FLAG_HIDDEN_ITEM_ROUTE_104_POTION,
    [RS_FLAG_HIDDEN_ITEM_26]                             = FLAG_HIDDEN_ITEM_UNDERWATER_124_HEART_SCALE_2,
    [RS_FLAG_HIDDEN_ITEM_27]                             = FLAG_HIDDEN_ITEM_ROUTE_121_HP_UP,
    [RS_FLAG_HIDDEN_ITEM_28]                             = FLAG_HIDDEN_ITEM_ROUTE_121_NUGGET,
    [RS_FLAG_HIDDEN_ITEM_29]                             = FLAG_HIDDEN_ITEM_ROUTE_123_REVIVE,
    [RS_FLAG_HIDDEN_ITEM_2A]                             = FLAG_HIDDEN_ITEM_ROUTE_114_REVIVE,
    [RS_FLAG_HIDDEN_ITEM_2B]                             = FLAG_HIDDEN_ITEM_LILYCOVE_CITY_PP_UP,
    [RS_FLAG_HIDDEN_ITEM_2C]                             = FLAG_HIDDEN_ITEM_ROUTE_104_SUPER_POTION,
    [RS_FLAG_HIDDEN_ITEM_2D]                             = FLAG_HIDDEN_ITEM_ROUTE_116_SUPER_POTION,
    [RS_FLAG_HIDDEN_ITEM_2E]                             = FLAG_HIDDEN_ITEM_ROUTE_106_STARDUST,
    [RS_FLAG_HIDDEN_ITEM_2F]                             = FLAG_HIDDEN_ITEM_ROUTE_106_HEART_SCALE,
    [RS_FLAG_HIDDEN_ITEM_30]                             = FLAG_HIDDEN_ITEM_GRANITE_CAVE_B2F_EVERSTONE_1,
    [RS_FLAG_HIDDEN_ITEM_31]                             = FLAG_HIDDEN_ITEM_GRANITE_CAVE_B2F_EVERSTONE_2,
    [RS_FLAG_HIDDEN_ITEM_32]                             = FLAG_HIDDEN_ITEM_ROUTE_109_REVIVE,
    [RS_FLAG_HIDDEN_ITEM_33]                             = FLAG_HIDDEN_ITEM_ROUTE_109_GREAT_BALL,
    [RS_FLAG_HIDDEN_ITEM_34]                             = FLAG_HIDDEN_ITEM_ROUTE_109_HEART_SCALE_1,
    [RS_FLAG_HIDDEN_ITEM_35]                             = FLAG_HIDDEN_ITEM_ROUTE_110_GREAT_BALL,
    [RS_FLAG_HIDDEN_ITEM_36]                             = FLAG_HIDDEN_ITEM_ROUTE_110_REVIVE,
    [RS_FLAG_HIDDEN_ITEM_37]                             = FLAG_HIDDEN_ITEM_ROUTE_110_FULL_HEAL,
    [RS_FLAG_HIDDEN_ITEM_38]                             = FLAG_HIDDEN_ITEM_ROUTE_111_PROTEIN,
    [RS_FLAG_HIDDEN_ITEM_39]                             = FLAG_HIDDEN_ITEM_ROUTE_111_RARE_CANDY,
    [RS_FLAG_HIDDEN_ITEM_3A]                             = FLAG_HIDDEN_ITEM_PETALBURG_WOODS_POTION,
    [RS_FLAG_HIDDEN_ITEM_3B]                             = FLAG_HIDDEN_ITEM_PETALBURG_WOODS_TINY_MUSHROOM_1,
    [RS_FLAG_HIDDEN_ITEM_3C]                             = FLAG_HIDDEN_ITEM_PETALBURG_WOODS_TINY_MUSHROOM_2,
    [RS_FLAG_HIDDEN_ITEM_3D]                             = FLAG_HIDDEN_ITEM_PETALBURG_WOODS_POKE_BALL,
    [RS_FLAG_HIDDEN_ITEM_3E]                             = FLAG_HIDDEN_ITEM_ROUTE_104_POKE_BALL,
    [RS_FLAG_HIDDEN_ITEM_3F]                             = FLAG_HIDDEN_ITEM_ROUTE_106_POKE_BALL,
    [RS_FLAG_HIDDEN_ITEM_40]                             = FLAG_HIDDEN_ITEM_ROUTE_109_ETHER,
    [RS_FLAG_HIDDEN_ITEM_41]                             = FLAG_HIDDEN_ITEM_ROUTE_110_POKE_BALL,
    [RS_FLAG_HIDDEN_ITEM_42]                             = FLAG_HIDDEN_ITEM_ROUTE_118_HEART_SCALE,
    [RS_FLAG_HIDDEN_ITEM_43]                             = FLAG_HIDDEN_ITEM_ROUTE_118_IRON,
    [RS_FLAG_HIDDEN_ITEM_44]                             = FLAG_HIDDEN_ITEM_ROUTE_119_FULL_HEAL,
    [RS_FLAG_HIDDEN_ITEM_45]                             = FLAG_HIDDEN_ITEM_ROUTE_120_RARE_CANDY_2,
    [RS_FLAG_HIDDEN_ITEM_46]                             = FLAG_HIDDEN_ITEM_ROUTE_120_ZINC,
    [RS_FLAG_HIDDEN_ITEM_47]                             = FLAG_HIDDEN_ITEM_ROUTE_120_RARE_CANDY_1,
    [RS_FLAG_HIDDEN_ITEM_48]                             = FLAG_HIDDEN_ITEM_ROUTE_117_REPEL,
    [RS_FLAG_HIDDEN_ITEM_49]                             = FLAG_HIDDEN_ITEM_ROUTE_121_FULL_HEAL,
    [RS_FLAG_HIDDEN_ITEM_4A]                             = FLAG_HIDDEN_ITEM_ROUTE_123_HYPER_POTION,
    [RS_FLAG_HIDDEN_ITEM_4B]                             = FLAG_HIDDEN_ITEM_LILYCOVE_CITY_POKE_BALL,
    [RS_FLAG_HIDDEN_ITEM_4C]                             = FLAG_HIDDEN_ITEM_JAGGED_PASS_GREAT_BALL,
    [RS_FLAG_HIDDEN_ITEM_4D]                             = FLAG_HIDDEN_ITEM_JAGGED_PASS_FULL_HEAL,
    [RS_FLAG_HIDDEN_ITEM_4E]                             = FLAG_HIDDEN_ITEM_MT_PYRE_EXTERIOR_MAX_ETHER,
    [RS_FLAG_HIDDEN_ITEM_4F]                             = FLAG_HIDDEN_ITEM_MT_PYRE_SUMMIT_ZINC,
    [RS_FLAG_HIDDEN_ITEM_50]                             = FLAG_HIDDEN_ITEM_MT_PYRE_SUMMIT_RARE_CANDY,
    [RS_FLAG_HIDDEN_ITEM_51]                             = FLAG_HIDDEN_ITEM_VICTORY_ROAD_1F_ULTRA_BALL,
    [RS_FLAG_HIDDEN_ITEM_52]                             = FLAG_HIDDEN_ITEM_VICTORY_ROAD_B2F_ELIXIR,
    [RS_FLAG_HIDDEN_ITEM_53]                             = FLAG_HIDDEN_ITEM_VICTORY_ROAD_B2F_MAX_REPEL,
    [RS_FLAG_HIDDEN_ITEM_54]                             = FLAG_HIDDEN_ITEM_ROUTE_120_REVIVE,
    [RS_FLAG_HIDDEN_ITEM_55]                             = FLAG_HIDDEN_ITEM_ROUTE_104_ANTIDOTE,
    [RS_FLAG_HIDDEN_ITEM_56]                             = FLAG_HIDDEN_ITEM_ROUTE_108_RARE_CANDY,
    [RS_FLAG_HIDDEN_ITEM_57]                             = FLAG_HIDDEN_ITEM_ROUTE_119_MAX_ETHER,
    [RS_FLAG_HIDDEN_ITEM_58]                             = FLAG_HIDDEN_ITEM_ROUTE_104_HEART_SCALE,
    [RS_FLAG_HIDDEN_ITEM_59]                             = FLAG_HIDDEN_ITEM_ROUTE_105_HEART_SCALE,
    [RS_FLAG_HIDDEN_ITEM_5A]                             = FLAG_HIDDEN_ITEM_ROUTE_109_HEART_SCALE_2,
    [RS_FLAG_HIDDEN_ITEM_5B]                             = FLAG_HIDDEN_ITEM_ROUTE_109_HEART_SCALE_3,
    [RS_FLAG_HIDDEN_ITEM_5C]                             = FLAG_HIDDEN_ITEM_ROUTE_128_HEART_SCALE_1,
    [RS_FLAG_HIDDEN_ITEM_5D]                             = FLAG_HIDDEN_ITEM_ROUTE_128_HEART_SCALE_2,
    [RS_FLAG_HIDDEN_ITEM_5E]                             = FLAG_HIDDEN_ITEM_ROUTE_128_HEART_SCALE_3,
    [RS_FLAG_HIDDEN_ITEM_5F]                             = FLAG_HIDDEN_ITEM_PETALBURG_CITY_RARE_CANDY,
    [RS_FLAG_HIDDEN_ITEM_BLACK_GLASSES]                  = FLAG_HIDDEN_ITEM_ROUTE_116_BLACK_GLASSES,
    [RS_FLAG_HIDDEN_ITEM_61]                             = FLAG_HIDDEN_ITEM_ROUTE_115_HEART_SCALE,
    [RS_FLAG_HIDE_BIRCH_STARTERS_BAG]                    = FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG,
    [RS_FLAG_HIDE_BIRCH_BATTLE_POOCHYENA]                = FLAG_HIDE_ROUTE_101_BIRCH_ZIGZAGOON_BATTLE,
    [RS_FLAG_HIDE_BIRCH_IN_LAB]                          = FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_BIRCH,
    [RS_FLAG_HIDE_MAY_UPSTAIRS]                          = FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_BEDROOM,
    [RS_FLAG_HIDE_RIVAL_ROUTE103]                        = FLAG_HIDE_ROUTE_103_RIVAL,
    [RS_FLAG_HIDE_DEVON_PETALBURG_WOODS]                 = FLAG_HIDE_PETALBURG_WOODS_DEVON_EMPLOYEE,
    [RS_FLAG_HIDE_EVIL_TEAM_PETALBURG_WOODS]             = FLAG_HIDE_PETALBURG_WOODS_AQUA_GRUNT,
    [RS_FLAG_HIDE_WALLY_PETALBURG]                       = FLAG_HIDE_PETALBURG_CITY_WALLY,
    [RS_FLAG_HIDE_STEVENS_LETTER]                        = FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_INVISIBLE_NINJA_BOY,
    [RS_FLAG_HIDE_WALLY_MOM_PETALBURG_1]                 = FLAG_HIDE_PETALBURG_CITY_WALLYS_MOM,
    [RS_FLAG_HIDE_GRUNT_RUSTBORO]                        = FLAG_HIDE_RUSTBORO_CITY_AQUA_GRUNT,
    [RS_FLAG_HIDE_DEVON_RUSTBORO]                        = FLAG_HIDE_RUSTBORO_CITY_DEVON_EMPLOYEE_1,
    [RS_FLAG_HIDE_SLEEPING_MON_SEAFLOOR_CAVERN]          = FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_KYOGRE_ASLEEP,
    [RS_FLAG_HIDE_NORMAN_LITTLEROOT]                     = FLAG_HIDE_PLAYERS_HOUSE_DAD,
    [RS_FLAG_UNKNOWN_2E1]                                = 
    [RS_FLAG_HIDE_MR_BRINEY_ROUTE104]                    = FLAG_HIDE_ROUTE_104_MR_BRINEY,
    [RS_FLAG_HIDE_MR_BRINEY_ROUTE104_HOUSE]              = FLAG_HIDE_BRINEYS_HOUSE_MR_BRINEY,
    [RS_FLAG_HIDE_MR_BRINEY_DEWFORD_TOWN]                = FLAG_HIDE_MR_BRINEY_DEWFORD_TOWN,
    [RS_FLAG_HIDE_MR_BRINEY_ROUTE109]                    = FLAG_HIDE_ROUTE_109_MR_BRINEY,
    [RS_FLAG_HIDE_MR_BRINEY_BOAT_ROUTE104]               = FLAG_HIDE_ROUTE_104_MR_BRINEY_BOAT,
    [RS_FLAG_HIDE_MR_BRINEY_BOAT_DEWFORD]                = FLAG_HIDE_MR_BRINEY_BOAT_DEWFORD_TOWN,
    [RS_FLAG_HIDE_MR_BRINEY_BOAT_ROUTE109]               = FLAG_HIDE_ROUTE_109_MR_BRINEY_BOAT,
    [RS_FLAG_UNKNOWN_2EB]                                = 
    [RS_FLAG_UNKNOWN_2EC]                                = 
    [RS_FLAG_UNKNOWN_2ED]                                = 
    [RS_FLAG_HIDE_POOCHYENA_ROUTE101]                    = FLAG_HIDE_ROUTE_101_ZIGZAGOON,
    [RS_FLAG_HIDE_WALLY_DEFEATED_VICTORY_ROAD]           = FLAG_HIDE_VICTORY_ROAD_EXIT_WALLY,
    [RS_FLAG_HIDE_MOM_LITTLEROOT]                        = FLAG_HIDE_LITTLEROOT_TOWN_MOM_OUTSIDE,
    [RS_FLAG_HIDE_MACHOKE_MOVER_1]                       = FLAG_HIDE_LITTLEROOT_TOWN_PLAYERS_HOUSE_VIGOROTH_1,
    [RS_FLAG_HIDE_MACHOKE_MOVER_2]                       = FLAG_HIDE_LITTLEROOT_TOWN_PLAYERS_HOUSE_VIGOROTH_2,
    [RS_FLAG_UNKNOWN_2F4]                                = 
    [RS_FLAG_HIDE_MOM_UPSTAIRS]                          = FLAG_HIDE_LITTLEROOT_TOWN_PLAYERS_BEDROOM_MOM,
    [RS_FLAG_HIDE_BRENDAN_MOM_DOWNSTAIRS]                = FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_MOM,
    [RS_FLAG_HIDE_MAY_MOM_DOWNSTAIRS]                    = FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_MOM,
    [RS_FLAG_HIDE_BRENDAN_UPSTAIRS]                      = FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_BEDROOM,
    [RS_FLAG_HIDE_MOVING_TRUCK_BRENDAN]                  = FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_TRUCK,
    [RS_FLAG_HIDE_MOVING_TRUCK_MAY]                      = FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_TRUCK,
    [RS_FLAG_HIDE_VICTOR_WINSTRATE]                      = FLAG_HIDE_ROUTE_111_VICTOR_WINSTRATE,
    [RS_FLAG_HIDE_VICTORIA_WINSTRATE]                    = FLAG_HIDE_ROUTE_111_VICTORIA_WINSTRATE,
    [RS_FLAG_HIDE_VIVI_WINSTRATE]                        = FLAG_HIDE_ROUTE_111_VIVI_WINSTRATE,
    [RS_FLAG_HIDE_VICKI_WINSTRATE]                       = FLAG_HIDE_ROUTE_111_VICKY_WINSTRATE,
    [RS_FLAG_HIDE_NORMAN_PETALBURG_GYM]                  = FLAG_HIDE_PETALBURG_GYM_NORMAN,
    [RS_FLAG_HIDE_RAYQUAZA]                              = FLAG_HIDE_SKY_PILLAR_TOP_RAYQUAZA,
    [RS_FLAG_HIDE_LILYCOVE_CONTEST_ATTENDENT_1]          = FLAG_HIDE_LILYCOVE_CONTEST_HALL_CONTEST_ATTENDANT_1,
    [RS_FLAG_HIDE_LILYCOVE_MUSEUM_CURATOR]               = FLAG_HIDE_LILYCOVE_MUSEUM_CURATOR,
    [RS_FLAG_HIDE_LILYCOVE_MUSEUM_PAINTING_LADY]         = FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_1,
    [RS_FLAG_HIDE_LILYCOVE_MUSEUM_PAINTING_GIRL]         = FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_2,
    [RS_FLAG_HIDE_LILYCOVE_MUSEUM_PAINTING_MAN]          = FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_3,
    [RS_FLAG_HIDE_LILYCOVE_MUSEUM_PAINTER]               = FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_4,
    [RS_FLAG_HIDE_LILYCOVE_MUSEUM_VISITORS]              = FLAG_HIDE_LILYCOVE_MUSEUM_TOURISTS,
    [RS_FLAG_HIDE_PETALBURG_GYM_GUIDE]                   = FLAG_HIDE_PETALBURG_GYM_GREETER,
    [RS_FLAG_UNKNOWN_30E]                                = 
    [RS_FLAG_UNKNOWN_30F]                                = 
    [RS_FLAG_HIDE_BRENDAN_MOM]                           = FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_MOM,
    [RS_FLAG_HIDE_MAY_MOM]                               = FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_MOM,
    [RS_FLAG_HIDE_FANCLUB_OLD_LADY]                      = FLAG_HIDE_FANCLUB_OLD_LADY,
    [RS_FLAG_HIDE_FANCLUB_BOY]                           = FLAG_HIDE_FANCLUB_BOY,
    [RS_FLAG_HIDE_FANCLUB_LITTLE_BOY]                    = FLAG_HIDE_FANCLUB_LITTLE_BOY,
    [RS_FLAG_HIDE_FANCLUB_LADY]                          = FLAG_HIDE_FANCLUB_LADY,
    [RS_FLAG_HIDE_GABBY_AND_TY_ROUTE111_1]               = FLAG_HIDE_ROUTE_111_GABBY_AND_TY_1,
    [RS_FLAG_HIDE_GABBY_AND_TY_ROUTE118_1]               = FLAG_HIDE_ROUTE_118_GABBY_AND_TY_1,
    [RS_FLAG_HIDE_GABBY_AND_TY_ROUTE120_1]               = FLAG_HIDE_ROUTE_120_GABBY_AND_TY_1,
    [RS_FLAG_HIDE_GABBY_AND_TY_ROUTE111_2]               = FLAG_HIDE_ROUTE_111_GABBY_AND_TY_3,
    [RS_FLAG_HIDE_CONTEST_REPORTER_FALLARBOR]            = 
    [RS_FLAG_HIDE_CONTEST_REPORTER_VERDANTURF]           = 
    [RS_FLAG_HIDE_CONTEST_REPORTER_LILYCOVE]             = FLAG_HIDE_LILYCOVE_CONTEST_HALL_REPORTER,
    [RS_FLAG_HIDE_CONTEST_REPORTER_SLATEPORT]            = FLAG_HIDE_SLATEPORT_CITY_CONTEST_REPORTER,
    [RS_FLAG_HIDE_WALLY_MAUVILLE]                        = FLAG_HIDE_MAUVILLE_CITY_WALLY,
    [RS_FLAG_HIDE_WALLY_FATHER_MAUVILLE]                 = FLAG_HIDE_MAUVILLE_CITY_WALLYS_UNCLE,
    [RS_FLAG_HIDE_WALLY_WANDAS_HOUSE]                    = FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WALLY,
    [RS_FLAG_HIDE_BOYFRIEND_RUSTURF_TUNNEL]              = FLAG_HIDE_RUSTURF_TUNNEL_WANDAS_BOYFRIEND,
    [RS_FLAG_HIDE_BOYFRIEND_WANDAS_HOUSE]                = FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WANDAS_BOYFRIEND,
    [RS_FLAG_HIDE_WALLY_FATHER_WANDAS_HOUSE]             = FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WALLYS_UNCLE,
    [RS_FLAG_HIDE_WALLY_FATHER_PETALBURG]                = 
    [RS_FLAG_HIDE_WALLY_MOTHER_PETALBURG]                = 
    [RS_FLAG_HIDE_LOST_GLASSES_MAN]                      = FLAG_HIDE_ROUTE_116_DROPPED_GLASSES_MAN,
    [RS_FLAG_HIDE_RIVAL_RUSTBORO]                        = FLAG_HIDE_RUSTBORO_CITY_RIVAL,
    [RS_FLAG_HIDE_WALLACE_SOOTOPOLIS_GYM]                = 
    [RS_FLAG_HIDE_WALLACE_SOOTOPOLIS]                    = FLAG_HIDE_SOOTOPOLIS_CITY_WALLACE,
    [RS_FLAG_HIDE_GRUNTS_BLOCKING_CABLE_CAR]             = 
    [RS_FLAG_HIDE_GRUNT_1_BLOCKING_HIDEOUT]              = FLAG_HIDE_AQUA_HIDEOUT_1F_GRUNT_1_BLOCKING_ENTRANCE,
    [RS_FLAG_HIDE_GRUNT_2_BLOCKING_HIDEOUT]              = FLAG_HIDE_AQUA_HIDEOUT_1F_GRUNT_2_BLOCKING_ENTRANCE,
    [RS_FLAG_UNKNOWN_337]                                = 
    [RS_FLAG_HIDE_LEGEND_MON_CAVE_OF_ORIGIN]             = 
    [RS_FLAG_HIDE_EVIL_LEADER_SEAFLOOR_CAVERN]           = 
    [RS_FLAG_HIDE_OTHER_LEADER_SEAFLOOR_CAVERN]          = 
    [RS_FLAG_HIDE_OTHER_TEAM_GRUNTS_SEAFLOOR_CAVERN]     = 
    [RS_FLAG_HIDE_STEVEN_GRANITE_CAVE]                   = FLAG_HIDE_GRANITE_CAVE_STEVEN,
    [RS_FLAG_HIDE_STEVEN_ROUTE128]                       = FLAG_HIDE_ROUTE_128_STEVEN,
    [RS_FLAG_HIDE_GABBY_AND_TY_SLATEPORT]                = FLAG_HIDE_SLATEPORT_CITY_GABBY_AND_TY,
    [RS_FLAG_HIDE_STERN_SLATEPORT]                       = FLAG_HIDE_SLATEPORT_CITY_CAPTAIN_STERN,
    [RS_FLAG_HIDE_STERN_SLATEPORT_HARBOR]                = FLAG_HIDE_SLATEPORT_CITY_HARBOR_CAPTAIN_STERN,
    [RS_FLAG_UNKNOWN_34B]                                = 
    [RS_FLAG_UNKNOWN_34C]                                = 
    [RS_FLAG_HIDE_GRUNT_1_SLATEPORT_HARBOR]              = FLAG_HIDE_SLATEPORT_CITY_HARBOR_AQUA_GRUNT,
    [RS_FLAG_HIDE_GRUNT_2_SLATEPORT_HARBOR]              = FLAG_HIDE_SLATEPORT_CITY_HARBOR_ARCHIE,
    [RS_FLAG_UNKNOWN_34F]                                = 
    [RS_FLAG_HIDE_SUBMARINE_SHADOW_SLATEPORT_HARBOR]     = FLAG_HIDE_SLATEPORT_CITY_HARBOR_SUBMARINE_SHADOW,
    [RS_FLAG_HIDE_MAY_PICHU_DOLL]                        = FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_2F_PICHU_DOLL,
    [RS_FLAG_HIDE_RIVAL_ROUTE119]                        = FLAG_HIDE_ROUTE_119_RIVAL,
    [RS_FLAG_HIDE_GRUNTS_LILYCOVE]                       = FLAG_HIDE_LILYCOVE_CITY_AQUA_GRUNTS,
    [RS_FLAG_HIDE_SOOTOPOLIS_RESIDENTS]                  = FLAG_HIDE_SOOTOPOLIS_CITY_RESIDENTS,
    [RS_FLAG_HIDE_CAVE_OF_ORIGIN_ENTRANCE_WOMAN_1]       = 
    [RS_FLAG_HIDE_CAVE_OF_ORIGIN_ENTRANCE_WOMAN_2]       = 
    [RS_FLAG_HIDE_WALLY_BATTLE_VICTORY_ROAD]             = FLAG_HIDE_VICTORY_ROAD_ENTRANCE_WALLY,
    [RS_FLAG_HIDE_AWAKENED_MON_SEAFLOOR_CAVERN]          = FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_KYOGRE,
    [RS_FLAG_HIDE_SS_TIDAL_SLATEPORT_HARBOR]             = FLAG_HIDE_SLATEPORT_CITY_HARBOR_SS_TIDAL,
    [RS_FLAG_HIDE_SS_TIDAL_LILYCOVE_HARBOR]              = FLAG_HIDE_LILYCOVE_HARBOR_SSTIDAL,
    [RS_FLAG_HIDE_WALLY_PETALBURG_GYM]                   = FLAG_HIDE_PETALBURG_GYM_WALLY,
    [RS_FLAG_UNKNOWN_363]                                = 
    [RS_FLAG_HIDE_FAT_MAN_LITTLEROOT]                    = FLAG_HIDE_LITTLEROOT_TOWN_FAT_MAN,
    [RS_FLAG_HIDE_BRINEY_SLATEPORT_SHIPYARD]             = FLAG_HIDE_SLATEPORT_CITY_STERNS_SHIPYARD_MR_BRINEY,
    [RS_FLAG_HIDE_LANETTE]                               = FLAG_HIDE_LANETTES_HOUSE_LANETTE,
    [RS_FLAG_HIDE_LANETTE_FALLARBOR]                     = FLAG_HIDE_FALLORBOR_POKEMON_CENTER_LANETTE,
    [RS_FLAG_HIDE_TRICKMASTER_ENTRANCE]                  = FLAG_HIDE_TRICK_HOUSE_ENTRANCE_MAN,
    [RS_FLAG_HIDE_MT_CHIMNEY_PEOPLE]                     = FLAG_HIDE_MT_CHIMNEY_TRAINERS,
    [RS_FLAG_HIDE_GRUNT_RUSTURF_TUNNEL]                  = FLAG_HIDE_RUSTURF_TUNNEL_AQUA_GRUNT,
    [RS_FLAG_HIDE_BRINEY_RUSTURF_TUNNEL]                 = FLAG_HIDE_RUSTURF_TUNNEL_BRINEY,
    [RS_FLAG_HIDE_PEEKO_RUSTURF_TUNNEL]                  = FLAG_HIDE_RUSTURF_TUNNEL_PEEKO,
    [RS_FLAG_HIDE_PEEKO_BRINEY_HOUSE]                    = FLAG_HIDE_BRINEYS_HOUSE_PEEKO,
    [RS_FLAG_HIDE_EVIL_TEAM_SLATEPORT]                   = FLAG_HIDE_SLATEPORT_CITY_TEAM_AQUA,
    [RS_FLAG_HIDE_EVIL_TEAM_OCEANIC_MUSEUM]              = FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_AQUA_GRUNTS,
    [RS_FLAG_HIDE_GRUNT_1_OCEANIC_MUSEUM_2F]             = FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_1,
    [RS_FLAG_HIDE_GRUNT_2_OCEANIC_MUSEUM_2F]             = FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_2,
    [RS_FLAG_HIDE_EVIL_TEAM_LEADER_OCEANIC_MUSEUM_2F]    = FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_ARCHIE,
    [RS_FLAG_HIDE_STERN_OCEANIC_MUSEUM_2F]               = FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_CAPTAIN_STERN,
    [RS_FLAG_HIDE_BATTLE_TOWER_OPPONENT]                 = FLAG_HIDE_BATTLE_TOWER_OPPONENT,
    [RS_FLAG_HIDE_RIVAL_BIRCH_LAB]                       = FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_RIVAL,
    [RS_FLAG_HIDE_EVIL_TEAM_WEATHER_INSTITUTE]           = FLAG_HIDE_ROUTE_119_TEAM_AQUA,
    [RS_FLAG_HIDE_BRINEY_ROUTE116]                       = FLAG_HIDE_ROUTE_116_MR_BRINEY,
    [RS_FLAG_HIDE_WEATHER_INSTITUTE_WORKERS_1F]          = FLAG_HIDE_WEATHER_INSTITUTE_1F_WORKERS,
    [RS_FLAG_HIDE_WEATHER_INSTITUTE_WORKERS_2F]          = FLAG_HIDE_WEATHER_INSTITUTE_2F_WORKERS,
    [RS_FLAG_HIDE_TUNNER_DIGGER_ROUTE116]                = FLAG_HIDE_ROUTE_116_WANDAS_BOYFRIEND,
    [RS_FLAG_HIDE_ARTIST_LILCOVE_CONTEST]                = FLAG_HIDE_LILYCOVE_CONTEST_HALL_CONTEST_ATTENDANT_2,
    [RS_FLAG_UNKNOWN_BIRCH_380]                          = 
    [RS_FLAG_HIDE_BIRCH_ROUTE101]                        = FLAG_HIDE_ROUTE_101_BIRCH,
    [RS_FLAG_HIDE_BIRCH_ROUTE103]                        = FLAG_HIDE_ROUTE_103_BIRCH,
    [RS_FLAG_HIDE_TRICKMASTER_END]                       = FLAG_HIDE_TRICK_HOUSE_END_MAN,
    [RS_FLAG_HIDE_EVIL_TEAM_ROUTE110]                    = FLAG_HIDE_ROUTE_110_TEAM_AQUA,
    [RS_FLAG_HIDE_GABBY_AND_TY_ROUTE118_2]               = FLAG_HIDE_ROUTE_118_GABBY_AND_TY_2,
    [RS_FLAG_HIDE_GABBY_AND_TY_ROUTE120_2]               = FLAG_HIDE_ROUTE_120_GABBY_AND_TY_2,
    [RS_FLAG_HIDE_GABBY_AND_TY_ROUTE111_3]               = FLAG_HIDE_ROUTE_111_GABBY_AND_TY_2,
    [RS_FLAG_HIDE_GABBY_AND_TY_ROUTE118_3]               = FLAG_HIDE_ROUTE_118_GABBY_AND_TY_3,
    [RS_FLAG_HIDE_WORKERS_SLATEPORT_HARBOR]              = FLAG_HIDE_SLATEPORT_CITY_HARBOR_PATRONS,
    [RS_FLAG_HIDE_FLOWER_SHOP_WORKER_OUTSIDE]            = FLAG_HIDE_ROUTE_104_WHITE_HERB_FLORIST,
    [RS_FLAG_HIDE_AZURILL_FALLARBOR]                     = FLAG_HIDE_FALLARBOR_AZURILL,
    [RS_FLAG_HIDE_FERRY_ATTENDANT_LILYCOVE]              = FLAG_HIDE_LILYCOVE_HARBOR_FERRY_ATTENDANT,
    [RS_FLAG_HIDE_FERRY_SAILOR_LILYCOVE]                 = FLAG_HIDE_LILYCOVE_HARBOR_FERRY_SAILOR,
    [RS_FLAG_HIDE_LATIOS_OR_LATIAS_FLYING]               = 
    [RS_FLAG_HIDE_LATIOS_OR_LATIAS_STATIONARY]           = 
    [RS_FLAG_HIDE_WATTSON_MAUVILLE]                      = FLAG_HIDE_MAUVILLE_CITY_WATTSON,
    [RS_FLAG_HIDE_WATTSON_MAUVILLE_GYM]                  = FLAG_HIDE_MAUVILLE_GYM_WATTSON,
    [RS_FLAG_HIDE_GRUNTS_ROUTE121]                       = FLAG_HIDE_ROUTE_121_TEAM_AQUA_GRUNTS,
    [RS_FLAG_UNKNOWN_393]                                = 
    [RS_FLAG_HIDE_LEADER_MT_PYRE_SUMMIT]                 = FLAG_HIDE_MT_PYRE_SUMMIT_ARCHIE,
    [RS_FLAG_HIDE_GRUNTS_MT_PYRE_SUMMIT]                 = FLAG_HIDE_MT_PYRE_SUMMIT_TEAM_AQUA,
    [RS_FLAG_HIDE_REPORTER_BATTLE_TOWER]                 = FLAG_HIDE_BATTLE_TOWER_REPORTER,
    [RS_FLAG_HIDE_RIVAL_ROUTE110]                        = FLAG_HIDE_ROUTE_110_RIVAL,
    [RS_FLAG_HIDE_RIVAL_CHAMPIONS_ROOM]                  = FLAG_HIDE_CHAMPIONS_ROOM_RIVAL,
    [RS_FLAG_HIDE_BIRCH_CHAMPIONS_ROOM]                  = FLAG_HIDE_CHAMPIONS_ROOM_BIRCH,
    [RS_FLAG_HIDE_RIVAL_ON_BIKE_ROUTE110]                = FLAG_HIDE_ROUTE_110_RIVAL_ON_BIKE,
    [RS_FLAG_HIDE_RIVAL_ROUTE119_ON_BIKE]                = FLAG_HIDE_ROUTE_119_RIVAL_ON_BIKE,
    [RS_FLAG_HIDE_GRUNTS_HIDEOUTS]                       = FLAG_HIDE_AQUA_HIDEOUT_GRUNTS,
    [RS_FLAG_HIDE_LILYCOVE_MOTEL_PEOPLE]                 = FLAG_HIDE_LILYCOVE_MOTEL_GAME_DESIGNERS,
    [RS_FLAG_HIDE_EVIL_TEAM_MT_CHIMNEY]                  = FLAG_HIDE_MT_CHIMNEY_TEAM_AQUA,
    [RS_FLAG_HIDE_OTHER_TEAM_MT_CHIMNEY]                 = FLAG_HIDE_MT_CHIMNEY_TEAM_MAGMA,
    [RS_FLAG_HIDE_PROF_COSMO_FALLARBOR]                  = FLAG_HIDE_FALLARBOR_HOUSE_PROF_COZMO,
    [RS_FLAG_HIDE_RIVAL_LAVARIDGE_1]                     = FLAG_HIDE_LAVARIDGE_TOWN_RIVAL,
    [RS_FLAG_HIDE_RIVAL_LAVARIDGE_2]                     = FLAG_HIDE_LAVARIDGE_TOWN_RIVAL_ON_BIKE,
    [RS_FLAG_HIDE_RUSTURF_TUNNEL_ROCK_1]                 = FLAG_HIDE_RUSTURF_TUNNEL_ROCK_1,
    [RS_FLAG_HIDE_RUSTURF_TUNNEL_ROCK_2]                 = FLAG_HIDE_RUSTURF_TUNNEL_ROCK_2,
    [RS_FLAG_HIDE_WINGULL_FORTREE_HOUSE]                 = FLAG_HIDE_FORTREE_CITY_HOUSE_4_WINGULL,
    [RS_FLAG_HIDE_WINGULL_MOSSDEEP_HOUSE]                = FLAG_HIDE_MOSSDEEP_CITY_HOUSE_2_WINGULL,
    [RS_FLAG_HIDE_REGIROCK]                              = FLAG_HIDE_REGIROCK,
    [RS_FLAG_HIDE_REGICE]                                = FLAG_HIDE_REGICE,
    [RS_FLAG_HIDE_REGISTEEL]                             = FLAG_HIDE_REGISTEEL,
    [RS_FLAG_HIDE_GRUNTS_METEOR_FALLS_1F]                = FLAG_HIDE_METEOR_FALLS_TEAM_AQUA,
    [RS_FLAG_HIDE_OTHER_TEAM_METEOR_FALLS_1F]            = FLAG_HIDE_METEOR_FALLS_TEAM_MAGMA,
    [RS_FLAG_HIDE_SLUDGE_BOMB_MAN_DEWFORD_HALL]          = FLAG_HIDE_DEWFORD_HALL_SLUDGE_BOMB_MAN,
    [RS_FLAG_HIDE_AWARD_MAN_BATTLE_TOWER]                = 
    [RS_FLAG_HIDE_PROF_COSMO_METEOR_FALLS]               = FLAG_HIDE_METEOR_FALLS_1F_1R_COZMO,
    [RS_FLAG_HIDE_SUBMARINE_SHADOW_HIDEOUT]              = FLAG_HIDE_AQUA_HIDEOUT_B2F_SUBMARINE_SHADOW,
    [RS_FLAG_HIDE_EVIL_LEADER_ROUTE128]                  = FLAG_HIDE_ROUTE_128_ARCHIE,
    [RS_FLAG_HIDE_OTHER_LEADER_ROUTE128]                 = FLAG_HIDE_ROUTE_128_MAXIE,
    [RS_FLAG_HIDE_EVIL_TEAM_GRUNTS_SEAFLOOR_CAVERN]      = FLAG_HIDE_SEAFLOOR_CAVERN_AQUA_GRUNTS,
    [RS_FLAG_HIDE_DEVON_EMPLOYEE_ROUTE116]               = FLAG_HIDE_ROUTE_116_DEVON_EMPLOYEE,
    [RS_FLAG_HIDE_TM_SALESMAN_SLATEPORT]                 = FLAG_HIDE_SLATEPORT_CITY_TM_SALESMAN,
    [RS_FLAG_HIDE_EMPLOYEE_DEVON_CORP_3F]                = FLAG_HIDE_RUSTBORO_CITY_DEVON_CORP_3F_EMPLOYEE,
    [RS_FLAG_HIDE_BRINEY_AND_PEEKO_SS_TIDAL]             = FLAG_HIDE_SS_TIDAL_CORRIDOR_MR_BRINEY,
    [RS_FLAG_HIDE_TM_49_GIVER_SS_TIDAL]                  = FLAG_HIDE_SS_TIDAL_ROOMS_SNATCH_GIVER,
    [RS_FLAG_HIDE_TOOK_SHOAL_SALT_1]                     = FLAG_RECEIVED_SHOAL_SALT_1,
    [RS_FLAG_HIDE_TOOK_SHOAL_SALT_2]                     = FLAG_RECEIVED_SHOAL_SALT_2,
    [RS_FLAG_HIDE_TOOK_SHOAL_SALT_3]                     = FLAG_RECEIVED_SHOAL_SALT_3,
    [RS_FLAG_HIDE_TOOK_SHOAL_SALT_4]                     = FLAG_RECEIVED_SHOAL_SALT_4,
    [RS_FLAG_HIDE_TOOK_SHOAL_SHELL_1]                    = FLAG_RECEIVED_SHOAL_SHELL_1,
    [RS_FLAG_HIDE_TOOK_SHOAL_SHELL_2]                    = FLAG_RECEIVED_SHOAL_SHELL_2,
    [RS_FLAG_HIDE_TOOK_SHOAL_SHELL_3]                    = FLAG_RECEIVED_SHOAL_SHELL_3,
    [RS_FLAG_HIDE_TOOK_SHOAL_SHELL_4]                    = FLAG_RECEIVED_SHOAL_SHELL_4,
    [RS_FLAG_HIDE_SECRET_POWER_MAN]                      = FLAG_HIDE_ROUTE_111_SECRET_POWER_MAN,
    [RS_FLAG_HIDE_OCEANIC_MUSEUM_VISITORS]               = FLAG_HIDE_SLATEPORT_MUSEUM_POPULATION,
    [RS_FLAG_HIDE_ROOFTOP_LADY_LILYCOVE_MART]            = FLAG_HIDE_LILYCOVE_DEPARTMENT_STORE_ROOFTOP_SALE_WOMAN,
    [RS_FLAG_HIDE_ROOT_FOSSIL]                           = FLAG_HIDE_MIRAGE_TOWER_ROOT_FOSSIL,
    [RS_FLAG_HIDE_CLAW_FOSSIL]                           = FLAG_HIDE_MIRAGE_TOWER_CLAW_FOSSIL,
    [RS_FLAG_HIDE_SCARED_GRUNT_OCEANIC_MUSEUM]           = FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_FAMILIAR_AQUA_GRUNT,
    [RS_FLAG_HIDE_STEVEN_ROUTE118]                       = FLAG_HIDE_ROUTE_118_STEVEN,
    [RS_FLAG_HIDE_STEVEN_STEVENS_HOUSE]                  = FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_STEVEN,
    [RS_FLAG_HIDE_BELDUM_BALL_STEVENS_HOUSE]             = FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_BELDUM_POKEBALL,
    [RS_FLAG_HIDE_KECLEON_FORTREE]                       = FLAG_HIDE_FORTREE_CITY_KECLEON,
    [RS_FLAG_HIDE_KECLEON_ROUTE120_1]                    = FLAG_HIDE_ROUTE_120_KECLEON_BRIDGE,
    [RS_FLAG_HIDE_RIVAL_LILYCOVE_MART]                   = FLAG_HIDE_LILYCOVE_CITY_RIVAL,
    [RS_FLAG_HIDE_STEVEN_ROUTE120]                       = FLAG_HIDE_ROUTE_120_STEVEN,
    [RS_FLAG_HIDE_STEVEN_SOOTOPOLIS]                     = FLAG_HIDE_SOOTOPOLIS_CITY_STEVEN,
    [RS_FLAG_HIDE_VOLTORB_1_NEW_MAUVILLE]                = FLAG_HIDE_NEW_MAUVILLE_VOLTORB_1,
    [RS_FLAG_HIDE_VOLTORB_2_NEW_MAUVILLE]                = FLAG_HIDE_NEW_MAUVILLE_VOLTORB_2,
    [RS_FLAG_HIDE_VOLTORB_3_NEW_MAUVILLE]                = FLAG_HIDE_NEW_MAUVILLE_VOLTORB_3,
    [RS_FLAG_HIDE_ELECTRODE_1_HIDEOUT]                   = FLAG_HIDE_AQUA_HIDEOUT_B1F_ELECTRODE_1,
    [RS_FLAG_HIDE_ELECTRODE_2_HIDEOUT]                   = FLAG_HIDE_AQUA_HIDEOUT_B1F_ELECTRODE_2,
    [RS_FLAG_HIDE_RIVAL_OLDALE_TOWN]                     = FLAG_HIDE_OLDALE_TOWN_RIVAL,
    [RS_FLAG_HIDE_UNDERWATER_SUBMARINE_INTERACTION]      = FLAG_HIDE_UNDERWATER_SEA_FLOOR_CAVERN_STOLEN_SUBMARINE,
    [RS_FLAG_HIDE_KECLEON_ROUTE120_2]                    = FLAG_HIDE_ROUTE_120_KECLEON_BRIDGE_SHADOW,
    [RS_FLAG_HIDE_KECLEON_ROUTE120_3]                    = FLAG_HIDE_ROUTE_120_KECLEON_1,
    [RS_FLAG_HIDE_GIRLFRIEND_RUSTURF_TUNNEL]             = FLAG_HIDE_RUSTURF_TUNNEL_WANDA,
    [RS_FLAG_HIDE_GIRLFRIEND_WANDAS_HOUSE]               = FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WANDA,
    [RS_FLAG_HIDE_KECLEON_ROUTE120_4]                    = FLAG_HIDE_ROUTE_120_KECLEON_2,
    [RS_FLAG_HIDE_KECLEON_ROUTE120_5]                    = FLAG_HIDE_ROUTE_120_KECLEON_3,
    [RS_FLAG_HIDE_KECLEON_ROUTE120_6]                    = FLAG_HIDE_ROUTE_120_KECLEON_4,
    [RS_FLAG_HIDE_KECLEON_ROUTE120_7]                    = FLAG_HIDE_ROUTE_120_KECLEON_5,
    [RS_FLAG_HIDE_KECLEON_ROUTE119_1]                    = FLAG_HIDE_ROUTE_119_KECLEON_1,
    [RS_FLAG_HIDE_KECLEON_ROUTE119_2]                    = FLAG_HIDE_ROUTE_119_KECLEON_2,
    [RS_FLAG_HIDE_BOY_ROUTE101]                          = FLAG_HIDE_ROUTE_101_BOY,
    [RS_FLAG_ITEM_ROUTE102_1 ]                           = FLAG_ITEM_ROUTE_102_POTION,
    [RS_FLAG_ITEM_ROUTE116_1 ]                           = FLAG_ITEM_ROUTE_116_X_SPECIAL,
    [RS_FLAG_ITEM_ROUTE104_1 ]                           = FLAG_ITEM_ROUTE_104_PP_UP,
    [RS_FLAG_ITEM_ROUTE105_1 ]                           = FLAG_ITEM_ROUTE_105_IRON,
    [RS_FLAG_ITEM_ROUTE106_1 ]                           = FLAG_ITEM_ROUTE_106_PROTEIN,
    [RS_FLAG_ITEM_ROUTE109_1 ]                           = FLAG_ITEM_ROUTE_109_PP_UP,
    [RS_FLAG_ITEM_ROUTE110_1 ]                           = FLAG_ITEM_ROUTE_110_RARE_CANDY,
    [RS_FLAG_ITEM_ROUTE110_2 ]                           = FLAG_ITEM_ROUTE_110_DIRE_HIT,
    [RS_FLAG_ITEM_ROUTE111_1 ]                           = FLAG_ITEM_ROUTE_111_TM_SANDSTORM,
    [RS_FLAG_ITEM_ROUTE111_2 ]                           = FLAG_ITEM_ROUTE_111_STARDUST,
    [RS_FLAG_ITEM_ROUTE111_3 ]                           = FLAG_ITEM_ROUTE_111_HP_UP,
    [RS_FLAG_ITEM_ROUTE112_1 ]                           = FLAG_ITEM_ROUTE_112_NUGGET,
    [RS_FLAG_ITEM_ROUTE113_1 ]                           = FLAG_ITEM_ROUTE_113_MAX_ETHER,
    [RS_FLAG_ITEM_ROUTE113_2 ]                           = FLAG_ITEM_ROUTE_113_SUPER_REPEL,
    [RS_FLAG_ITEM_ROUTE114_1 ]                           = FLAG_ITEM_ROUTE_114_RARE_CANDY,
    [RS_FLAG_ITEM_ROUTE114_2 ]                           = FLAG_ITEM_ROUTE_114_PROTEIN,
    [RS_FLAG_ITEM_ROUTE115_1 ]                           = FLAG_ITEM_ROUTE_115_SUPER_POTION,
    [RS_FLAG_ITEM_ROUTE115_2 ]                           = FLAG_ITEM_ROUTE_115_TM_FOCUS_PUNCH,
    [RS_FLAG_ITEM_ROUTE115_3 ]                           = FLAG_ITEM_ROUTE_115_IRON,
    [RS_FLAG_ITEM_ROUTE116_2 ]                           = FLAG_ITEM_ROUTE_116_ETHER,
    [RS_FLAG_ITEM_ROUTE116_3 ]                           = FLAG_ITEM_ROUTE_116_REPEL,
    [RS_FLAG_ITEM_ROUTE116_4 ]                           = FLAG_ITEM_ROUTE_116_HP_UP,
    [RS_FLAG_ITEM_ROUTE117_1 ]                           = FLAG_ITEM_ROUTE_117_GREAT_BALL,
    [RS_FLAG_ITEM_ROUTE117_2 ]                           = FLAG_ITEM_ROUTE_117_REVIVE,
    [RS_FLAG_ITEM_ROUTE119_1 ]                           = FLAG_ITEM_ROUTE_119_SUPER_REPEL,
    [RS_FLAG_ITEM_ROUTE119_2 ]                           = FLAG_ITEM_ROUTE_119_ZINC,
    [RS_FLAG_ITEM_ROUTE119_3 ]                           = FLAG_ITEM_ROUTE_119_ELIXIR_1,
    [RS_FLAG_ITEM_ROUTE119_4 ]                           = FLAG_ITEM_ROUTE_119_LEAF_STONE,
    [RS_FLAG_ITEM_ROUTE119_5 ]                           = FLAG_ITEM_ROUTE_119_RARE_CANDY,
    [RS_FLAG_ITEM_ROUTE119_6 ]                           = FLAG_ITEM_ROUTE_119_HYPER_POTION_1,
    [RS_FLAG_ITEM_ROUTE120_1 ]                           = FLAG_ITEM_ROUTE_120_NUGGET,
    [RS_FLAG_ITEM_ROUTE120_2 ]                           = FLAG_ITEM_ROUTE_120_FULL_HEAL,
    [RS_FLAG_ITEM_ROUTE123_1 ]                           = FLAG_ITEM_ROUTE_123_CALCIUM,
    [RS_FLAG_ITEM_ROUTE123_2 ]                           = 
    [RS_FLAG_ITEM_ROUTE127_1 ]                           = FLAG_ITEM_ROUTE_127_ZINC,
    [RS_FLAG_ITEM_ROUTE127_2 ]                           = FLAG_ITEM_ROUTE_127_CARBOS,
    [RS_FLAG_ITEM_ROUTE132_1 ]                           = FLAG_ITEM_ROUTE_132_RARE_CANDY,
    [RS_FLAG_ITEM_ROUTE133_1 ]                           = FLAG_ITEM_ROUTE_133_BIG_PEARL,
    [RS_FLAG_ITEM_ROUTE133_2 ]                           = FLAG_ITEM_ROUTE_133_STAR_PIECE,
    [RS_FLAG_ITEM_PETALBURG_1]                           = FLAG_ITEM_PETALBURG_CITY_MAX_REVIVE,
    [RS_FLAG_ITEM_PETALBURG_2]                           = FLAG_ITEM_PETALBURG_CITY_ETHER,
    [RS_FLAG_ITEM_RUSTBORO_1]                            = FLAG_ITEM_RUSTBORO_CITY_X_DEFEND,
    [RS_FLAG_ITEM_LILYCOVE_1]                            = FLAG_ITEM_LILYCOVE_CITY_MAX_REPEL,
    [RS_FLAG_ITEM_MOSSDEEP_1]                            = FLAG_ITEM_MOSSDEEP_CITY_NET_BALL,
    [RS_FLAG_ITEM_METEOR_FALLS_1F_1R_1]                  = FLAG_ITEM_METEOR_FALLS_1F_1R_TM_IRON_TAIL,
    [RS_FLAG_ITEM_METEOR_FALLS_1F_1R_2]                  = FLAG_ITEM_METEOR_FALLS_1F_1R_FULL_HEAL,
    [RS_FLAG_ITEM_METEOR_FALLS_1F_1R_3]                  = FLAG_ITEM_METEOR_FALLS_1F_1R_MOON_STONE,
    [RS_FLAG_ITEM_METEOR_FALLS_1F_1R_4]                  = FLAG_ITEM_METEOR_FALLS_1F_1R_PP_UP,
    [RS_FLAG_ITEM_RUSTURF_TUNNEL_1]                      = FLAG_ITEM_RUSTURF_TUNNEL_POKE_BALL,
    [RS_FLAG_ITEM_RUSTURF_TUNNEL_2]                      = FLAG_ITEM_RUSTURF_TUNNEL_MAX_ETHER,
    [RS_FLAG_ITEM_GRANITE_CAVE_1F_1]                     = FLAG_ITEM_GRANITE_CAVE_1F_ESCAPE_ROPE,
    [RS_FLAG_ITEM_GRANITE_CAVE_B1F_1]                    = FLAG_ITEM_GRANITE_CAVE_B1F_POKE_BALL,
    [RS_FLAG_ITEM_MT_PYRE_5F_1]                          = FLAG_ITEM_MT_PYRE_5F_LAX_INCENSE,
    [RS_FLAG_ITEM_GRANITE_CAVE_B2F_1]                    = FLAG_ITEM_GRANITE_CAVE_B2F_REPEL,
    [RS_FLAG_ITEM_GRANITE_CAVE_B2F_2]                    = FLAG_ITEM_GRANITE_CAVE_B2F_RARE_CANDY,
    [RS_FLAG_ITEM_PETALBURG_WOODS_1]                     = FLAG_ITEM_PETALBURG_WOODS_X_ATTACK,
    [RS_FLAG_ITEM_PETALBURG_WOODS_2]                     = FLAG_ITEM_PETALBURG_WOODS_GREAT_BALL,
    [RS_FLAG_ITEM_ROUTE104_2 ]                           = FLAG_ITEM_ROUTE_104_POKE_BALL,
    [RS_FLAG_ITEM_PETALBURG_WOODS_3]                     = FLAG_ITEM_PETALBURG_WOODS_ETHER,
    [RS_FLAG_ITEM_CAVE_OF_ORIGIN_B3F_1]                  = FLAG_ITEM_MAGMA_HIDEOUT_3F_3R_ECAPE_ROPE,
    [RS_FLAG_ITEM_TRICK_HOUSE_PUZZLE_1_1]                = FLAG_ITEM_TRICK_HOUSE_PUZZLE_1_ORANGE_MAIL,
    [RS_FLAG_ITEM_TRICK_HOUSE_PUZZLE_2_1]                = FLAG_ITEM_TRICK_HOUSE_PUZZLE_2_HARBOR_MAIL,
    [RS_FLAG_ITEM_TRICK_HOUSE_PUZZLE_2_2]                = FLAG_ITEM_TRICK_HOUSE_PUZZLE_2_WAVE_MAIL,
    [RS_FLAG_ITEM_TRICK_HOUSE_PUZZLE_3_1]                = FLAG_ITEM_TRICK_HOUSE_PUZZLE_3_SHADOW_MAIL,
    [RS_FLAG_ITEM_TRICK_HOUSE_PUZZLE_3_2]                = FLAG_ITEM_TRICK_HOUSE_PUZZLE_3_WOOD_MAIL,
    [RS_FLAG_ITEM_TRICK_HOUSE_PUZZLE_4_1]                = FLAG_ITEM_TRICK_HOUSE_PUZZLE_4_MECH_MAIL,
    [RS_FLAG_ITEM_ROUTE124_1]                            = FLAG_ITEM_ROUTE_124_YELLOW_SHARD,
    [RS_FLAG_ITEM_TRICK_HOUSE_PUZZLE_6_1]                = FLAG_ITEM_TRICK_HOUSE_PUZZLE_6_GLITTER_MAIL,
    [RS_FLAG_ITEM_TRICK_HOUSE_PUZZLE_7_1]                = FLAG_ITEM_TRICK_HOUSE_PUZZLE_7_TROPIC_MAIL,
    [RS_FLAG_ITEM_TRICK_HOUSE_PUZZLE_8_1]                = FLAG_ITEM_TRICK_HOUSE_PUZZLE_8_BEAD_MAIL,
    [RS_FLAG_ITEM_JAGGED_PASS_1]                         = FLAG_ITEM_JAGGED_PASS_BURN_HEAL,
    [RS_FLAG_ITEM_AQUA_HIDEOUT_B1F_1]                    = FLAG_ITEM_AQUA_HIDEOUT_B1F_MAX_ELIXIR,
    [RS_FLAG_ITEM_AQUA_HIDEOUT_B2F_1]                    = FLAG_ITEM_AQUA_HIDEOUT_B2F_NEST_BALL,
    [RS_FLAG_ITEM_MT_PYRE_EXTERIOR_1]                    = FLAG_ITEM_MT_PYRE_EXTERIOR_MAX_POTION,
    [RS_FLAG_ITEM_MT_PYRE_EXTERIOR_2]                    = FLAG_ITEM_MT_PYRE_EXTERIOR_TM_SKILL_SWAP,
    [RS_FLAG_ITEM_NEW_MAUVILLE_INSIDE_1]                 = FLAG_ITEM_NEW_MAUVILLE_ULTRA_BALL,
    [RS_FLAG_ITEM_NEW_MAUVILLE_INSIDE_2]                 = FLAG_ITEM_NEW_MAUVILLE_ESCAPE_ROPE,
    [RS_FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS_1]   = FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_6_LUXURY_BALL,
    [RS_FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS_2]   = FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_2_SCANNER,
    [RS_FLAG_ITEM_SCORCHED_SLAB_1]                       = FLAG_ITEM_SCORCHED_SLAB_TM_SUNNY_DAY,
    [RS_FLAG_ITEM_METEOR_FALLS_B1F_2R_1]                 = FLAG_ITEM_METEOR_FALLS_B1F_2R_TM_DRAGON_CLAW,
    [RS_FLAG_ITEM_SHOAL_CAVE_LOW_TIDE_ENTRANCE_1]        = FLAG_ITEM_SHOAL_CAVE_ENTRANCE_BIG_PEARL,
    [RS_FLAG_ITEM_SHOAL_CAVE_LOW_TIDE_INNER_ROOM_1]      = FLAG_ITEM_SHOAL_CAVE_INNER_ROOM_RARE_CANDY,
    [RS_FLAG_ITEM_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM_1]     = FLAG_ITEM_SHOAL_CAVE_STAIRS_ROOM_ICE_HEAL,
    [RS_FLAG_ITEM_VICTORY_ROAD_1F_1]                     = FLAG_ITEM_VICTORY_ROAD_1F_MAX_ELIXIR,
    [RS_FLAG_ITEM_VICTORY_ROAD_1F_2]                     = FLAG_ITEM_VICTORY_ROAD_1F_PP_UP,
    [RS_FLAG_ITEM_VICTORY_ROAD_B1F_1]                    = FLAG_ITEM_VICTORY_ROAD_B1F_TM_PSYCHIC,
    [RS_FLAG_ITEM_VICTORY_ROAD_B1F_2]                    = FLAG_ITEM_VICTORY_ROAD_B1F_FULL_RESTORE,
    [RS_FLAG_ITEM_VICTORY_ROAD_B2F_1]                    = FLAG_ITEM_VICTORY_ROAD_B2F_FULL_HEAL,
    [RS_FLAG_ITEM_MT_PYRE_6F_1]                          = FLAG_ITEM_MT_PYRE_6F_TM_SHADOW_BALL,
    [RS_FLAG_ITEM_SEAFLOOR_CAVERN_ROOM_9_1]              = FLAG_ITEM_SEAFLOOR_CAVERN_ROOM_9_TM_EARTHQUAKE,
    [RS_FLAG_ITEM_FIERY_PATH_1]                          = FLAG_ITEM_FIERY_PATH_TM_TOXIC,
    [RS_FLAG_ITEM_ROUTE124_2]                            = FLAG_ITEM_ROUTE_124_RED_SHARD,
    [RS_FLAG_ITEM_ROUTE124_3]                            = FLAG_ITEM_ROUTE_124_BLUE_SHARD,
    [RS_FLAG_ITEM_SAFARI_ZONE_NORTHWEST_1]               = FLAG_ITEM_SAFARI_ZONE_NORTH_WEST_TM_SOLAR_BEAM,
    [RS_FLAG_ITEM_ABANDONED_SHIP_ROOMS_1F_1]             = FLAG_ITEM_ABANDONED_SHIP_ROOMS_1F_HARBOR_MAIL,
    [RS_FLAG_ITEM_ABANDONED_SHIP_ROOMS_B1F_1]            = FLAG_ITEM_ABANDONED_SHIP_ROOMS_B1F_ESCAPE_ROPE,
    [RS_FLAG_ITEM_ABANDONED_SHIP_ROOMS_2_B1F_1]          = FLAG_ITEM_ABANDONED_SHIP_ROOMS_2_B1F_DIVE_BALL,
    [RS_FLAG_ITEM_ABANDONED_SHIP_ROOM_B1F_1]             = FLAG_ITEM_ABANDONED_SHIP_ROOMS_B1F_TM_ICE_BEAM,
    [RS_FLAG_ITEM_ABANDONED_SHIP_ROOMS_2_1F_1]           = FLAG_ITEM_ABANDONED_SHIP_ROOMS_2_1F_REVIVE,
    [RS_FLAG_ITEM_ABANDONED_SHIP_CAPTAINS_OFFICE_1]      = FLAG_ITEM_ABANDONED_SHIP_CAPTAINS_OFFICE_STORAGE_KEY,
    [RS_FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS_3]   = FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_3_WATER_STONE,
    [RS_FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS_4]   = FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_1_TM_RAIN_DANCE,
    [RS_FLAG_ITEM_ROUTE121_1]                            = FLAG_ITEM_ROUTE_121_CARBOS,
    [RS_FLAG_ITEM_ROUTE123_3]                            = FLAG_ITEM_ROUTE_123_ULTRA_BALL,
    [RS_FLAG_ITEM_ROUTE126_1]                            = FLAG_ITEM_ROUTE_126_GREEN_SHARD,
    [RS_FLAG_ITEM_ROUTE119_7]                            = FLAG_ITEM_ROUTE_119_HYPER_POTION_2,
    [RS_FLAG_ITEM_ROUTE120_3]                            = FLAG_ITEM_ROUTE_120_HYPER_POTION,
    [RS_FLAG_ITEM_ROUTE120_4]                            = FLAG_ITEM_ROUTE_120_NEST_BALL,
    [RS_FLAG_ITEM_ROUTE123_4]                            = FLAG_ITEM_ROUTE_123_ELIXIR,
    [RS_FLAG_ITEM_NEW_MAUVILLE_INSIDE_3]                 = FLAG_ITEM_NEW_MAUVILLE_THUNDER_STONE,
    [RS_FLAG_ITEM_FIERY_PATH_2]                          = FLAG_ITEM_FIERY_PATH_FIRE_STONE,
    [RS_FLAG_ITEM_SHOAL_CAVE_LOW_TIDE_ICE_ROOM_1]        = FLAG_ITEM_SHOAL_CAVE_ICE_ROOM_TM_HAIL,
    [RS_FLAG_ITEM_SHOAL_CAVE_LOW_TIDE_ICE_ROOM_2]        = FLAG_ITEM_SHOAL_CAVE_ICE_ROOM_NEVER_MELT_ICE,
    [RS_FLAG_ITEM_ROUTE103_1]                            = FLAG_ITEM_ROUTE_103_GUARD_SPEC,
    [RS_FLAG_ITEM_ROUTE104_3]                            = FLAG_ITEM_ROUTE_104_X_ACCURACY,
    [RS_FLAG_ITEM_MAUVILLE_1]                            = FLAG_ITEM_MAUVILLE_CITY_X_SPEED,
    [RS_FLAG_ITEM_PETALBURG_WOODS_4]                     = FLAG_ITEM_PETALBURG_WOODS_PARALYZE_HEAL,
    [RS_FLAG_ITEM_ROUTE115_4]                            = FLAG_ITEM_ROUTE_115_GREAT_BALL,
    [RS_FLAG_ITEM_SAFARI_ZONE_NORTHEAST_1]               = FLAG_ITEM_SAFARI_ZONE_NORTH_CALCIUM,
    [RS_FLAG_ITEM_MT_PYRE_3F_1]                          = FLAG_ITEM_MT_PYRE_3F_SUPER_REPEL,
    [RS_FLAG_ITEM_ROUTE118_1]                            = FLAG_ITEM_ROUTE_118_HYPER_POTION,
    [RS_FLAG_ITEM_NEW_MAUVILLE_INSIDE_4]                 = FLAG_ITEM_NEW_MAUVILLE_FULL_HEAL,
    [RS_FLAG_ITEM_NEW_MAUVILLE_INSIDE_5]                 = FLAG_ITEM_NEW_MAUVILLE_PARALYZE_HEAL,
    [RS_FLAG_ITEM_AQUA_HIDEOUT_B1F_2]                    = FLAG_ITEM_AQUA_HIDEOUT_B1F_MASTER_BALL,
    [RS_FLAG_ITEM_MAGMA_HIDEOUT_B1F_1]                   = 
    [RS_FLAG_ITEM_MAGMA_HIDEOUT_B1F_2]                   = 
    [RS_FLAG_ITEM_MAGMA_HIDEOUT_B2F_1]                   = 
    [RS_FLAG_ITEM_MT_PYRE_2F_1]                          = FLAG_ITEM_MT_PYRE_2F_ULTRA_BALL,
    [RS_FLAG_ITEM_MT_PYRE_4F_1]                          = FLAG_ITEM_MT_PYRE_4F_SEA_INCENSE,
    [RS_FLAG_ITEM_SAFARI_ZONE_SOUTHWEST]                 = FLAG_ITEM_SAFARI_ZONE_SOUTH_WEST_MAX_REVIVE,
    [RS_FLAG_ITEM_AQUA_HIDEOUT_B1F_3]                    = FLAG_ITEM_AQUA_HIDEOUT_B1F_NUGGET,
    [RS_FLAG_ITEM_MOSSDEEP_STEVENS_HOUSE_HM08]           = 
    [RS_FLAG_ITEM_MAGMA_HIDEOUT_B1F_3]                   = FLAG_ITEM_ROUTE_119_NUGGET,
    [RS_FLAG_ITEM_ROUTE104_4]                            = FLAG_ITEM_ROUTE_104_POTION,
    [RS_FLAG_DEFEATED_RUSTBORO_GYM]                      = FLAG_DEFEATED_RUSTBORO_GYM,
    [RS_FLAG_DEFEATED_DEWFORD_GYM]                       = FLAG_DEFEATED_DEWFORD_GYM,
    [RS_FLAG_DEFEATED_MAUVILLE_GYM]                      = FLAG_DEFEATED_MAUVILLE_GYM,
    [RS_FLAG_DEFEATED_LAVARIDGE_GYM]                     = FLAG_DEFEATED_LAVARIDGE_GYM,
    [RS_FLAG_DEFEATED_PETALBURG_GYM]                     = FLAG_DEFEATED_PETALBURG_GYM,
    [RS_FLAG_DEFEATED_FORTREE_GYM]                       = FLAG_DEFEATED_FORTREE_GYM,
    [RS_FLAG_DEFEATED_MOSSDEEP_GYM]                      = FLAG_DEFEATED_MOSSDEEP_GYM,
    [RS_FLAG_DEFEATED_SOOTOPOLIS_GYM]                    = FLAG_DEFEATED_SOOTOPOLIS_GYM,
    [RS_FLAG_DEFEATED_ELITE_4_SYDNEY]                    = FLAG_DEFEATED_ELITE_4_SIDNEY,
    [RS_FLAG_DEFEATED_ELITE_4_PHOEBE]                    = FLAG_DEFEATED_ELITE_4_PHOEBE,
    [RS_FLAG_DEFEATED_ELITE_4_GLACIA]                    = FLAG_DEFEATED_ELITE_4_GLACIA,
    [RS_FLAG_DEFEATED_ELITE_4_DRAKE]                     = FLAG_DEFEATED_ELITE_4_DRAKE,
    [RS_FLAG_SYS_POKEMON_GET]                            = FLAG_SYS_POKEMON_GET,
    [RS_FLAG_SYS_POKEDEX_GET]                            = FLAG_SYS_POKEDEX_GET,
    [RS_FLAG_SYS_POKENAV_GET]                            = FLAG_SYS_POKENAV_GET,
    [RS_FLAG_SYS_GAME_CLEAR]                             = FLAG_SYS_GAME_CLEAR,
    [RS_FLAG_SYS_CHAT_USED]                              = FLAG_SYS_CHAT_USED,
    [RS_FLAG_SYS_HIPSTER_MEET]                           = FLAG_UNLOCKED_TRENDY_SAYINGS,
    [RS_FLAG_BADGE01_GET]                                = FLAG_BADGE01_GET,
    [RS_FLAG_BADGE02_GET]                                = FLAG_BADGE02_GET,
    [RS_FLAG_BADGE03_GET]                                = FLAG_BADGE03_GET,
    [RS_FLAG_BADGE04_GET]                                = FLAG_BADGE04_GET,
    [RS_FLAG_BADGE05_GET]                                = FLAG_BADGE05_GET,
    [RS_FLAG_BADGE06_GET]                                = FLAG_BADGE06_GET,
    [RS_FLAG_BADGE07_GET]                                = FLAG_BADGE07_GET,
    [RS_FLAG_BADGE08_GET]                                = FLAG_BADGE08_GET,
    [RS_FLAG_VISITED_LITTLEROOT_TOWN]                    = FLAG_VISITED_LITTLEROOT_TOWN,
    [RS_FLAG_VISITED_OLDALE_TOWN]                        = FLAG_VISITED_OLDALE_TOWN,
    [RS_FLAG_VISITED_DEWFORD_TOWN]                       = FLAG_VISITED_DEWFORD_TOWN,
    [RS_FLAG_VISITED_LAVARIDGE_TOWN]                     = FLAG_VISITED_LAVARIDGE_TOWN,
    [RS_FLAG_VISITED_FALLARBOR_TOWN                      = FLAG_VISITED_FALLARBOR_TOWN,
    [RS_FLAG_VISITED_VERDANTURF_TOWN]                    = FLAG_VISITED_VERDANTURF_TOWN,
    [RS_FLAG_VISITED_PACIFIDLOG_TOWN]                    = FLAG_VISITED_PACIFIDLOG_TOWN,
    [RS_FLAG_VISITED_PETALBURG_CITY]                     = FLAG_VISITED_PETALBURG_CITY,
    [RS_FLAG_VISITED_SLATEPORT_CITY]                     = FLAG_VISITED_SLATEPORT_CITY,
    [RS_FLAG_VISITED_MAUVILLE_CITY]                      = FLAG_VISITED_MAUVILLE_CITY,
    [RS_FLAG_VISITED_RUSTBORO_CITY]                      = FLAG_VISITED_RUSTBORO_CITY,
    [RS_FLAG_VISITED_FORTREE_CITY]                       = FLAG_VISITED_FORTREE_CITY,
    [RS_FLAG_VISITED_LILYCOVE_CITY]                      = FLAG_VISITED_LILYCOVE_CITY,
    [RS_FLAG_VISITED_MOSSDEEP_CITY]                      = FLAG_VISITED_MOSSDEEP_CITY,
    [RS_FLAG_VISITED_SOOTOPOLIS_CITY]                    = FLAG_VISITED_SOOTOPOLIS_CITY,
    [RS_FLAG_VISITED_EVER_GRANDE_CITY]                   = FLAG_VISITED_EVER_GRANDE_CITY,
    [RS_FLAG_SYS_USE_FLASH]                              = FLAG_SYS_USE_FLASH,
    [RS_FLAG_SYS_USE_STRENGTH]                           = FLAG_SYS_USE_STRENGTH,
    [RS_FLAG_SYS_WEATHER_CTRL]                           = FLAG_SYS_WEATHER_CTRL,
    [RS_FLAG_SYS_CYCLING_ROAD]                           = FLAG_SYS_CYCLING_ROAD,
    [RS_FLAG_SYS_SAFARI_MODE]                            = FLAG_SYS_SAFARI_MODE,
    [RS_FLAG_SYS_CRUISE_MODE]                            = FLAG_SYS_CRUISE_MODE,
    [RS_FLAG_SYS_TV_HOME]                                = FLAG_SYS_TV_HOME,
    [RS_FLAG_SYS_TV_WATCH]                               = FLAG_SYS_TV_WATCH,
    [RS_FLAG_SYS_TV_START]                               = FLAG_SYS_TV_START,
    [RS_FLAG_SYS_POPWORD_INPUT]                          = FLAG_SYS_CHANGED_DEWFORD_TREND,
    [RS_FLAG_SYS_MIX_RECORD]                             = FLAG_SYS_MIX_RECORD,
    [RS_FLAG_SYS_CLOCK_SET]                              = FLAG_SYS_CLOCK_SET,
    [RS_FLAG_SYS_NATIONAL_DEX]                           = 
    [RS_FLAG_SYS_CAVE_SHIP]                              = 
    [RS_FLAG_SYS_CAVE_WONDER]                            = 
    [RS_FLAG_SYS_CAVE_BATTLE]                            = 
    [RS_FLAG_SYS_SHOAL_TIDE]                             = FLAG_SYS_SHOAL_TIDE,
    [RS_FLAG_SYS_RIBBON_GET]                             = FLAG_SYS_RIBBON_GET,
    [RS_FLAG_LANDMARK_FLOWER_SHOP]                       = FLAG_LANDMARK_FLOWER_SHOP
    [RS_FLAG_LANDMARK_MR_BRINEY_HOUSE]                   = FLAG_LANDMARK_MR_BRINEY_HOUSE,
    [RS_FLAG_LANDMARK_ABANDONED_SHIP]                    = FLAG_LANDMARK_ABANDONED_SHIP,
    [RS_FLAG_LANDMARK_SEASHORE_HOUSE]                    = FLAG_LANDMARK_SEASHORE_HOUSE,
    [RS_FLAG_LANDMARK_NEW_MAUVILLE]                      = FLAG_LANDMARK_NEW_MAUVILLE,
    [RS_FLAG_LANDMARK_OLD_LADY_REST_SHOP]                = FLAG_LANDMARK_OLD_LADY_REST_SHOP,
    [RS_FLAG_LANDMARK_TRICK_HOUSE]                       = FLAG_LANDMARK_TRICK_HOUSE,
    [RS_FLAG_LANDMARK_WINSTRATE_FAMILY]                  = FLAG_LANDMARK_WINSTRATE_FAMILY,
    [RS_FLAG_LANDMARK_GLASS_WORKSHOP]                    = FLAG_LANDMARK_GLASS_WORKSHOP,
    [RS_FLAG_LANDMARK_LANETTES_HOUSE]                    = FLAG_LANDMARK_LANETTES_HOUSE,
    [RS_FLAG_LANDMARK_POKEMON_DAYCARE]                   = FLAG_LANDMARK_POKEMON_DAYCARE,
    [RS_FLAG_LANDMARK_SEAFLOOR_CAVERN]                   = FLAG_LANDMARK_SEAFLOOR_CAVERN,
    [RS_FLAG_LANDMARK_BATTLE_TOWER]                      = FLAG_LANDMARK_BATTLE_FRONTIER,
    [RS_FLAG_LANDMARK_SOUTHERN_ISLAND]                   = FLAG_LANDMARK_SOUTHERN_ISLAND,
    [RS_FLAG_LANDMARK_FIERY_PATH]                        = FLAG_LANDMARK_FIERY_PATH,
    [RS_FLAG_SYS_PC_LANETTE]                             = FLAG_SYS_PC_LANETTE,
    [RS_FLAG_SYS_EXDATA_ENABLE]                          = FLAG_SYS_MYSTERY_EVENT_ENABLE,
    [RS_FLAG_SYS_ENC_UP_ITEM]                            = FLAG_SYS_ENC_UP_ITEM,
    [RS_FLAG_SYS_ENC_DOWN_ITEM]                          = FLAG_SYS_ENC_DOWN_ITEM,
    [RS_FLAG_SYS_BRAILLE_DIG]                            = FLAG_SYS_BRAILLE_DIG,
    [RS_FLAG_SYS_BRAILLE_STRENGTH]                       = FLAG_SYS_REGIROCK_PUZZLE_COMPLETED,
    [RS_FLAG_SYS_BRAILLE_WAIT]                           = FLAG_SYS_BRAILLE_REGICE_COMPLETED,
    [RS_FLAG_SYS_BRAILLE_FLY]                            = FLAG_SYS_REGISTEEL_PUZZLE_COMPLETED,
    [RS_FLAG_SYS_HAS_EON_TICKET]                         = FLAG_ENABLE_SHIP_SOUTHERN_ISLAND,
    [RS_FLAG_SYS_POKEMON_LEAGUE_FLY]                     = FLAG_LANDMARK_POKEMON_LEAGUE,
    [RS_FLAG_LANDMARK_ISLAND_CAVE]                       = FLAG_LANDMARK_ISLAND_CAVE,
    [RS_FLAG_LANDMARK_DESERT_RUINS]                      = FLAG_LANDMARK_DESERT_RUINS,
    [RS_FLAG_LANDMARK_FOSSIL_MANIACS_HOUSE]              = FLAG_LANDMARK_FOSSIL_MANIACS_HOUSE,
    [RS_FLAG_LANDMARK_SCORCHED_SLAB]                     = FLAG_LANDMARK_SCORCHED_SLAB,
    [RS_FLAG_LANDMARK_ANCIENT_TOMB]                      = FLAG_LANDMARK_ANCIENT_TOMB,
    [RS_FLAG_LANDMARK_TUNNELERS_REST_HOUSE]              = FLAG_LANDMARK_TUNNELERS_REST_HOUSE,
    [RS_FLAG_LANDMARK_HUNTERS_HOUSE]                     = FLAG_LANDMARK_HUNTERS_HOUSE,
    [RS_FLAG_LANDMARK_SEALED_CHAMBER]                    = FLAG_LANDMARK_SEALED_CHAMBER,
    [RS_FLAG_SYS_TV_LATI]                                = FLAG_SYS_TV_LATIAS_LATIOS,
    [RS_FLAG_LANDMARK_SKY_PILLAR]                        = FLAG_LANDMARK_SKY_PILLAR,
    [RS_FLAG_SYS_SHOAL_ITEM]                             = FLAG_SYS_SHOAL_ITEM,
    [RS_FLAG_SYS_B_DASH]                                 = FLAG_SYS_B_DASH,
    [RS_FLAG_SYS_CTRL_OBJ_DELETE]                        = FLAG_SYS_CTRL_OBJ_DELETE,
    [RS_FLAG_SYS_RESET_RTC_ENABLE]                       = FLAG_SYS_RESET_RTC_ENABLE,
    [RS_FLAG_LANDMARK_BERRY_MASTERS_HOUSE]               = FLAG_LANDMARK_BERRY_MASTERS_HOUSE,
    [RS_FLAG_DAILY_RECEIVED_BERRY_FALLARBOR]             = FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY,
    [RS_FLAG_DAILY_UNKNOWN_8C2]                          = 
    [RS_FLAG_DAILY_PICKED_LOTTO_TICKET]                  = FLAG_DAILY_PICKED_LOTO_TICKET,
    [RS_FLAG_DAILY_RECEIVED_BERRY_ROUTE114]              = FLAG_DAILY_ROUTE_114_RECEIVED_BERRY,
    [RS_FLAG_DAILY_RECEIVED_BERRY_ROUTE111]              = FLAG_DAILY_ROUTE_111_RECEIVED_BERRY,
    [RS_FLAG_DAILY_RECEIVED_BERRY_FROM_BERRYMASTER]      = FLAG_DAILY_BERRY_MASTER_RECEIVED_BERRY,
    [RS_FLAG_DAILY_RECEIVED_BERRY_ROUTE120]              = FLAG_DAILY_ROUTE_120_RECEIVED_BERRY,
    [RS_FLAG_DAILY_RECEIVED_BERRY_LILYCOVE]              = FLAG_DAILY_LILYCOVE_RECEIVED_BERRY,
    [RS_FLAG_DAILY_RECEIVED_BERRY_FLOWER_SHOP]           = FLAG_DAILY_FLOWER_SHOP_RECEIVED_BERRY,
    [RS_FLAG_DAILY_RECEIVED_BERRY_FROM_BERRYMASTER_WIFE] = FLAG_DAILY_BERRY_MASTERS_WIFE,
    [RS_FLAG_DAILY_RECEIVED_BERRY_SOOTOPOLIS]            = FLAG_DAILY_SOOTOPOLIS_RECEIVED_BERRY,
};

static const u16 sRSFlagsToNLFlags[] = {
    [RS_VAR_RECYCLE_GOODS]                      = VAR_RECYCLE_GOODS,
    [RS_VAR_REPEL_STEP_COUNT]                   = VAR_REPEL_STEP_COUNT,
    [RS_VAR_ICE_STEP_COUNT]                     = VAR_ICE_STEP_COUNT,
    [RS_VAR_STARTER_MON]                        = VAR_STARTER_MON,
    [RS_VAR_MIRAGE_RND_H]                       = VAR_MIRAGE_RND_H,
    [RS_VAR_MIRAGE_RND_L]                       = VAR_MIRAGE_RND_L,
    [RS_VAR_SECRET_BASE_MAP]                    = VAR_SECRET_BASE_MAP,
    [RS_VAR_CYCLING_ROAD_RECORD_COLLISIONS]     = VAR_CYCLING_ROAD_RECORD_COLLISIONS,
    [RS_VAR_CYCLING_ROAD_RECORD_TIME_L]         = VAR_CYCLING_ROAD_RECORD_TIME_L,
    [RS_VAR_CYCLING_ROAD_RECORD_TIME_H]         = VAR_CYCLING_ROAD_RECORD_TIME_H,
    [RS_VAR_HAPPINESS_STEP_COUNTER]             = VAR_FRIENDSHIP_STEP_COUNTER,
    [RS_VAR_POISON_STEP_COUNTER]                = VAR_POISON_STEP_COUNTER,
    [RS_VAR_RESET_RTC_ENABLE]                   = VAR_RESET_RTC_ENABLE,
    [RS_VAR_ENIGMA_BERRY_AVAILABLE]             = VAR_ENIGMA_BERRY_AVAILABLE,
    [RS_VAR_DAYS]                               = VAR_DAYS,
    [RS_VAR_FANCLUB_UNKNOWN_1]                  = VAR_FANCLUB_FAN_COUNTER,
    [RS_VAR_FANCLUB_UNKNOWN_2]                  = VAR_FANCLUB_LOSE_FAN_TIMER,
    [RS_VAR_DEPT_STORE_FLOOR]                   = VAR_DEPT_STORE_FLOOR,
    [RS_VAR_TRICK_HOUSE_ROOMS_COMPLETED]        = VAR_TRICK_HOUSE_LEVEL,
    [RS_VAR_LOTTERY_PRIZE]                      = VAR_POKELOT_PRIZE_ITEM,
    [RS_VAR_NATIONAL_DEX]                       = VAR_NATIONAL_DEX,
    [RS_VAR_SHROOMISH_SIZE_RECORD]              = 
    [RS_VAR_ASH_GATHER_COUNT]                   = VAR_ASH_GATHER_COUNT,
    [RS_VAR_BIRCH_STATE]                        = VAR_BIRCH_STATE,
    [RS_VAR_CRUISE_STEP_COUNT]                  = VAR_CRUISE_STEP_COUNT,
    [RS_VAR_LOTTERY_RND_L]                      = VAR_POKELOT_RND1,
    [RS_VAR_LOTTERY_RND_H]                      = VAR_POKELOT_RND2,
    [RS_VAR_BARBOACH_SIZE_RECORD]               = 
    [RS_VAR_LITTLEROOT_STATE]                   = VAR_LITTLEROOT_TOWN_STATE,
    [RS_VAR_ROUTE102_ACCESSIBLE]                = 
    [RS_VAR_LAVARIDGE_RIVAL_STATE]              = VAR_LAVARIDGE_TOWN_STATE,
    [RS_VAR_CURRENT_SECRET_BASE]                = VAR_CURRENT_SECRET_BASE,
    [RS_VAR_PETALBURG_STATE]                    = VAR_PETALBURG_CITY_STATE,
    [RS_VAR_SLATEPORT_STATE]                    = VAR_SLATEPORT_CITY_STATE,
    [RS_VAR_RUSTBORO_STATE]                     = VAR_RUSTBORO_CITY_STATE,
    [RS_VAR_SOOTOPOLIS_STATE]                   = VAR_SOOTOPOLIS_CITY_STATE,
    [RS_VAR_ROUTE101_STATE]                     = VAR_ROUTE101_STATE,
    [RS_VAR_ROUTE103_STATE]                     = 
    [RS_VAR_ROUTE110_STATE]                     = VAR_ROUTE110_STATE,
    [RS_VAR_ROUTE116_STATE]                     = VAR_ROUTE116_STATE,
    [RS_VAR_ROUTE118_STATE]                     = VAR_ROUTE118_STATE,
    [RS_VAR_ROUTE119_STATE]                     = VAR_ROUTE119_STATE,
    [RS_VAR_ROUTE121_STATE]                     = VAR_ROUTE121_STATE,
    [RS_VAR_ROUTE128_STATE]                     = VAR_ROUTE128_STATE,
    [RS_VAR_LITTLEROOT_HOUSES_STATE]            = VAR_LITTLEROOT_HOUSES_STATE_MAY,
    [RS_VAR_BIRCH_LAB_STATE]                    = VAR_BIRCH_LAB_STATE,
    [RS_VAR_PETALBURG_GYM_STATE]                = VAR_PETALBURG_GYM_STATE,
    [RS_VAR_LINK_CONTEST_ROOM_STATE]            = VAR_CONTEST_HALL_STATE,
    [RS_VAR_CABLE_CLUB_STATE]                   = VAR_CABLE_CLUB_STATE,
    [RS_VAR_CONTEST_LOCATION]                   = VAR_CONTEST_TYPE,
    [RS_VAR_SECRET_BASE_INITIALIZED]            = VAR_SECRET_BASE_INITIALIZED,
    [RS_VAR_CONTEST_PRIZE_PICKUP]               = VAR_CONTEST_PRIZE_PICKUP,
    [RS_VAR_LITTLEROOT_HOUSES_STATE_2]          = VAR_LITTLEROOT_HOUSES_STATE_BRENDAN,
    [RS_VAR_LITTLEROOT_RIVAL_STATE]             = VAR_LITTLEROOT_RIVAL_STATE,
    [RS_VAR_BOARD_BRINEY_BOAT_ROUTE104_STATE]   = VAR_BOARD_BRINEY_BOAT_STATE,
    [RS_VAR_DEVON_CORP_3F_STATE]                = VAR_DEVON_CORP_3F_STATE,
    [RS_VAR_BRINEY_HOUSE_STATE]                 = VAR_BRINEY_HOUSE_STATE,
    [RS_VAR_LITTLEROOT_INTRO_STATE]             = VAR_LITTLEROOT_INTRO_STATE,
    [RS_VAR_MAUVILLE_GYM_STATE]                 = VAR_MAUVILLE_GYM_STATE,
    [RS_VAR_LILYCOVE_MUSEUM_2F_STATE]           = VAR_LILYCOVE_MUSEUM_2F_STATE,
    [RS_VAR_LILYCOVE_FAN_CLUB_STATE]            = VAR_LILYCOVE_FAN_CLUB_STATE,
    [RS_VAR_BRINEY_LOCATION]                    = VAR_BRINEY_LOCATION,
    [RS_VAR_INIT_SECRET_BASE]                   = VAR_INIT_SECRET_BASE,
    [RS_VAR_PETALBURG_WOODS_STATE]              = VAR_PETALBURG_WOODS_STATE,
    [RS_VAR_LILYCOVE_CONTEST_LOBBY_STATE]       = VAR_LILYCOVE_CONTEST_LOBBY_STATE,
    [RS_VAR_RUSTURF_TUNNEL_STATE]               = VAR_RUSTURF_TUNNEL_STATE,
    [RS_VAR_CAVE_OF_ORIGIN_B4F_STATE]           = 
    [RS_VAR_ELITE_4_STATE]                      = VAR_ELITE_4_STATE,
    [RS_VAR_SLATEPORT_HARBOR_STATE]             = VAR_SLATEPORT_HARBOR_STATE,
    [RS_VAR_SEAFLOOR_CAVERN_STATE]              = VAR_SEAFLOOR_CAVERN_STATE,
    [RS_VAR_CABLE_CAR_STATION_STATE]            = VAR_CABLE_CAR_STATION_STATE,
    [RS_VAR_SAFARI_ZONE_STATE]                  = VAR_SAFARI_ZONE_STATE,
    [RS_VAR_TRICK_HOUSE_ENTRANCE_STATE]         = VAR_TRICK_HOUSE_BEING_WATCHED_STATE,
    [RS_VAR_TRICK_HOUSE_ENTRANCE_STATE_2]       = VAR_TRICK_HOUSE_FOUND_TRICK_MASTER,
    [RS_VAR_TRICK_HOUSE_ENTRANCE_STATE_3]       = VAR_TRICK_HOUSE_ENTRANCE_STATE,
    [RS_VAR_CYCLING_CHALLENGE_STATE]            = VAR_CYCLING_CHALLENGE_STATE,
    [RS_VAR_SLATEPORT_MUSEUM_1F_STATE]          = VAR_SLATEPORT_MUSEUM_1F_STATE,
    [RS_VAR_TRICK_HOUSE_PUZZLE_1_STATE]         = VAR_TRICK_HOUSE_PUZZLE_1_STATE,
    [RS_VAR_TRICK_HOUSE_PUZZLE_2_STATE]         = VAR_TRICK_HOUSE_PUZZLE_2_STATE,
    [RS_VAR_TRICK_HOUSE_PUZZLE_3_STATE]         = VAR_TRICK_HOUSE_PUZZLE_3_STATE,
    [RS_VAR_TRICK_HOUSE_PUZZLE_4_STATE]         = VAR_TRICK_HOUSE_PUZZLE_4_STATE,
    [RS_VAR_TRICK_HOUSE_PUZZLE_5_STATE]         = VAR_TRICK_HOUSE_PUZZLE_5_STATE,
    [RS_VAR_TRICK_HOUSE_PUZZLE_6_STATE]         = VAR_TRICK_HOUSE_PUZZLE_6_STATE,
    [RS_VAR_TRICK_HOUSE_PUZZLE_7_STATE]         = VAR_TRICK_HOUSE_PUZZLE_7_STATE,
    [RS_VAR_TRICK_HOUSE_PUZZLE_8_STATE]         = VAR_TRICK_HOUSE_PUZZLE_8_STATE,
    [RS_VAR_WEATHER_INSTITUTE_STATE]            = VAR_WEATHER_INSTITUTE_STATE,
    [RS_VAR_PORTHOLE_STATE]                     = VAR_SS_TIDAL_STATE,
    [RS_VAR_TRICK_HOUSE_STATE]                  = VAR_TRICK_HOUSE_ENTER_FROM_CORRIDOR,
    [RS_VAR_TRICK_HOUSE_PUZZLE_7_STATE_2]       = 
    [RS_VAR_SLATEPORT_FAN_CLUB_STATE]           = VAR_SLATEPORT_FAN_CLUB_STATE,
    [RS_VAR_MT_PYRE_STATE]                      = VAR_MT_PYRE_STATE,
    [RS_VAR_NEW_MAUVILLE_STATE]                 = VAR_NEW_MAUVILLE_STATE,
    [RS_VAR_BRAVO_TRAINER_BATTLE_TOWER_ON]      = VAR_BRAVO_TRAINER_BATTLE_TOWER_ON,
    [RS_VAR_JAGGED_PASS_ASH_WEATHER]            = VAR_JAGGED_PASS_ASH_WEATHER,
    [RS_VAR_GLASS_WORKSHOP_STATE]               = VAR_GLASS_WORKSHOP_STATE,
    [RS_VAR_METEOR_FALLS_STATE]                 = VAR_METEOR_FALLS_STATE,
    [RS_VAR_GAME_CORNER_STATE]                  = 
    [RS_VAR_TRICK_HOUSE_PRIZE_PICKUP]           = VAR_TRICK_HOUSE_PRIZE_PICKUP,
    [RS_VAR_PACIFIDLOG_TM_RECEIVED_DAY]         = VAR_PACIFIDLOG_TM_RECEIVED_DAY,
    [RS_VAR_VICTORY_ROAD_1F_STATE]              = VAR_VICTORY_ROAD_1F_STATE,
    [RS_VAR_FOSSIL_RESURRECTION_STATE]          = VAR_FOSSIL_RESURRECTION_STATE,
    [RS_VAR_WHICH_FOSSIL_REVIVED]               = VAR_WHICH_FOSSIL_REVIVED,
    [RS_VAR_STEVENS_HOUSE_STATE]                = VAR_STEVENS_HOUSE_STATE,
    [RS_VAR_OLDALE_STATE]                       = VAR_OLDALE_RIVAL_STATE,
};
*/

u8 DetectSaveType(void)
{
    u32 i;
    u8 *rawBlock1 = (u8 *)gSaveBlock1Ptr;
    u8 *rawBlock2 = (u8 *)gSaveBlock2Ptr;

    if (rawBlock1[0x31] == 27)
        return SAVE_TYPE_NL;

    if (rawBlock2[0xAC] == 1 && rawBlock2[0xAD] == 0 && rawBlock2[0xAE] == 0 && rawBlock2[0xAF] == 0)
        return SAVE_TYPE_FRLG;

    for (i = 0x890; i < 0xF2C; i++)
    {
        if (rawBlock2[i] != 0)
            return SAVE_TYPE_E;
    }

    return SAVE_TYPE_RS; // Split R/S detection post-game
}

u8 ConvertSaveFileFromRSToNL(void)
{
    u32 i;
    struct SaveBlock1 *nlSaveBlock1Ptr = AllocZeroed(sizeof(struct SaveBlock1));
    struct SaveBlock2 *nlSaveBlock2Ptr = AllocZeroed(sizeof(struct SaveBlock2));
    struct RubySapphireSaveBlock1 *rsSaveBlock1Ptr = (struct RubySapphireSaveBlock1 *)gSaveBlock1Ptr;
    struct RubySapphireSaveBlock2 *rsSaveBlock2Ptr = (struct RubySapphireSaveBlock2 *)gSaveBlock2Ptr;

    memcpy(nlSaveBlock1Ptr, rsSaveBlock1Ptr, 0x560); // Save block structure is the same all the way until the Bag

    memcpy(nlSaveBlock1Ptr->pokeblocks, rsSaveBlock1Ptr->pokeblocks, 0xA28); // This whole chunk is identical (although offset) until the flags
    // Convert flags and vars
    memcpy(nlSaveBlock1Ptr->gameStats, rsSaveBlock1Ptr->gameStats, sizeof(rsSaveBlock1Ptr->gameStats));

    memcpy(nlSaveBlock1Ptr->berryTrees, rsSaveBlock1Ptr->berryTrees, 0xA40);

    TransferItemsToNewPockets(nlSaveBlock1Ptr, SAVE_TYPE_RS);

    memcpy(nlSaveBlock1Ptr->playerRoomDecorations, rsSaveBlock1Ptr->playerRoomDecorations, 0x914);

    memcpy(&nlSaveBlock1Ptr->daycare.mons[0].mon, &rsSaveBlock1Ptr->daycare.mons[0], sizeof(rsSaveBlock1Ptr->daycare.mons[0]));
    memcpy(&nlSaveBlock1Ptr->daycare.mons[0].mail, &rsSaveBlock1Ptr->daycare.misc.mail[0], sizeof(rsSaveBlock1Ptr->daycare.misc.mail[0]));

    nlSaveBlock1Ptr->daycare.mons[0].mail.gameLanguage = GAME_LANGUAGE;
    nlSaveBlock1Ptr->daycare.mons[0].mail.monLanguage = GAME_LANGUAGE;

    memcpy(&nlSaveBlock1Ptr->daycare.mons[0].steps, &rsSaveBlock1Ptr->daycare.misc.countersEtc.steps[0], sizeof(rsSaveBlock1Ptr->daycare.misc.countersEtc.steps[0]));
    memcpy(&nlSaveBlock1Ptr->daycare.mons[1].mon, &rsSaveBlock1Ptr->daycare.mons[1], sizeof(rsSaveBlock1Ptr->daycare.mons[1]));
    memcpy(&nlSaveBlock1Ptr->daycare.mons[1].mail, &rsSaveBlock1Ptr->daycare.misc.mail[1], sizeof(rsSaveBlock1Ptr->daycare.misc.mail[1]));

    nlSaveBlock1Ptr->daycare.mons[1].mail.gameLanguage = GAME_LANGUAGE;
    nlSaveBlock1Ptr->daycare.mons[1].mail.monLanguage = GAME_LANGUAGE;

    memcpy(&nlSaveBlock1Ptr->daycare.mons[1].steps, &rsSaveBlock1Ptr->daycare.misc.countersEtc.steps[1], sizeof(rsSaveBlock1Ptr->daycare.misc.countersEtc.steps[1]));
    // Probably gen a new PID here -v
    memcpy(&nlSaveBlock1Ptr->daycare.offspringPersonality, &rsSaveBlock1Ptr->daycare.misc.countersEtc.pendingEggPersonality, sizeof(rsSaveBlock1Ptr->daycare.misc.countersEtc.pendingEggPersonality));
    memcpy(&nlSaveBlock1Ptr->daycare.stepCounter, &rsSaveBlock1Ptr->daycare.misc.countersEtc.eggCycleStepsRemaining, sizeof(rsSaveBlock1Ptr->daycare.misc.countersEtc.eggCycleStepsRemaining));

    memcpy(&nlSaveBlock1Ptr->linkBattleRecords, rsSaveBlock1Ptr->linkBattleRecords, 0xA8); // This whole chunk is (almost) identical (although offset) until the Enigma Berry

    for (i = 0; i < LINK_B_RECORDS_COUNT; i++)
        nlSaveBlock1Ptr->linkBattleRecords.languages[i] = GAME_LANGUAGE;

    // Convert Enigma Berry

    memcpy(&nlSaveBlock1Ptr->recordMixingGift, &rsSaveBlock1Ptr->recordMixingGift, 0x44); // Copy Record Mixing Gift and seen2 flags.  Everything else we keep zero as it's new Emerald/Heliodor content.  We don't keep the RAM Script as the script commands don't match between RS and E's languages

    memcpy(gSaveBlock1Ptr, nlSaveBlock1Ptr, sizeof(*nlSaveBlock1Ptr));

    memcpy(nlSaveBlock2Ptr, rsSaveBlock2Ptr, 0xAC); // All of save block 2 is identical until you hit the RS Battle Tower data

    memcpy(gSaveBlock2Ptr, nlSaveBlock2Ptr, sizeof(*nlSaveBlock2Ptr));

    FREE_AND_SET_NULL(nlSaveBlock1Ptr);
    FREE_AND_SET_NULL(nlSaveBlock2Ptr);

    LoadFakePockets();

    //Do some clean initializations like new game
    
    gSaveBlock2Ptr->frontier.opponentNames[0][0] = 0xFF;
    gSaveBlock2Ptr->frontier.opponentNames[1][0] = 0xFF;
    if (FlagGet(FLAG_SYS_POKEDEX_GET))
        gSaveBlock2Ptr->gcnLinkFlags = 0x803F;
    VarSet(VAR_SEEDOT_SIZE_RECORD, 0x8000);
    VarSet(VAR_LOTAD_SIZE_RECORD, 0x8000);
    InitUnionRoomChatRegisteredTexts();
    InitLilycoveLady();
    ResetAllApprenticeData();
    ClearRankingHallRecords();
    InitMatchCallCounters();
    ResetTrainerHillResults();
	VarSet(VAR_SAVE_VER, 6);
    SetContinueGameWarpStatus();
    if (gSaveBlock2Ptr->playerGender == MALE)
        SetContinueGameWarpToHealLocation(HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F);
    else
        SetContinueGameWarpToHealLocation(HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE_2F);
}

u8 ConvertSaveFileFromEToNL(void)
{
    u32 i;
    struct SaveBlock1 *nlSaveBlock1Ptr = AllocZeroed(sizeof(struct SaveBlock1));
    struct SaveBlock2 *nlSaveBlock2Ptr = AllocZeroed(sizeof(struct SaveBlock2));
    struct PreNLSaveBlock1 *preNLSaveBlock1Ptr = (struct PreNLSaveBlock1 *)gSaveBlock1Ptr;
    struct PreNLSaveBlock2 *preNLSaveBlock2Ptr = (struct PreNLSaveBlock2 *)gSaveBlock2Ptr;

    memcpy(nlSaveBlock1Ptr, preNLSaveBlock1Ptr, 0x235);
    nlSaveBlock1Ptr->saveMagic = 27;
    memcpy(nlSaveBlock1Ptr->playerParty, preNLSaveBlock1Ptr->playerParty, 0x328);
    nlSaveBlock1Ptr->money = preNLSaveBlock1Ptr->money ^ preNLSaveBlock2Ptr->encryptionKey;
    nlSaveBlock1Ptr->coins = preNLSaveBlock1Ptr->coins ^ preNLSaveBlock2Ptr->encryptionKey;

    TransferItemsToNewPockets(nlSaveBlock1Ptr, SAVE_TYPE_E);

    memcpy(nlSaveBlock1Ptr->pokeblocks, preNLSaveBlock1Ptr->pokeblocks, sizeof(struct Pokeblock) * POKEBLOCKS_COUNT);
    memcpy(nlSaveBlock1Ptr->berryBlenderRecords, preNLSaveBlock1Ptr->berryBlenderRecords, 0x6);
    memcpy(&nlSaveBlock1Ptr->trainerRematchStepCounter, &preNLSaveBlock1Ptr->trainerRematchStepCounter, 0x10D4);

    for (i = 0; i < NUM_USED_GAME_STATS; i++)
        nlSaveBlock1Ptr->gameStats[i] = preNLSaveBlock1Ptr->gameStats[i] ^ preNLSaveBlock2Ptr->encryptionKey;

    memcpy(nlSaveBlock1Ptr->secretBases, preNLSaveBlock1Ptr->secretBases, sizeof(struct SecretBase) * SECRET_BASES_COUNT); // Do we need to select specific ones to preserve?
    memcpy(nlSaveBlock1Ptr->playerRoomDecorations, preNLSaveBlock1Ptr->playerRoomDecorations, 0x166C);

    memcpy(gSaveBlock1Ptr, nlSaveBlock1Ptr, sizeof(struct SaveBlock1));

    memcpy(nlSaveBlock2Ptr, preNLSaveBlock2Ptr, sizeof(struct PreNLSaveBlock2));
    nlSaveBlock2Ptr->berryCrush.berryPowderAmount= preNLSaveBlock2Ptr->berryCrush.berryPowderAmount ^ preNLSaveBlock2Ptr->encryptionKey;

    memcpy(gSaveBlock2Ptr, nlSaveBlock2Ptr, sizeof(struct SaveBlock2));

    FREE_AND_SET_NULL(nlSaveBlock1Ptr);
    FREE_AND_SET_NULL(nlSaveBlock2Ptr);

    LoadFakePockets();
}
