	.align 1
gMetatiles_General::
	.incbin "data/tilesets/primary/general/metatiles.bin"

	.align 1
gMetatileAttributes_General::
	.incbin "data/tilesets/primary/general/metatile_attributes.bin"

	.align 1
gMetatiles_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/metatiles.bin"

	.align 1
gMetatileAttributes_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/metatile_attributes.bin"

	.align 1
gMetatiles_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/metatiles.bin"

	.align 1
gMetatileAttributes_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/metatile_attributes.bin"

	.align 1
gMetatiles_Dewford::
	.incbin "data/tilesets/secondary/dewford/metatiles.bin"

	.align 1
gMetatileAttributes_Dewford::
	.incbin "data/tilesets/secondary/dewford/metatile_attributes.bin"

	.align 1
gMetatiles_Slateport::
	.incbin "data/tilesets/secondary/slateport/metatiles.bin"

	.align 1
gMetatileAttributes_Slateport::
	.incbin "data/tilesets/secondary/slateport/metatile_attributes.bin"

	.align 1
gMetatiles_Mauville::
	.incbin "data/tilesets/secondary/mauville/metatiles.bin"

	.align 1
gMetatileAttributes_Mauville::
	.incbin "data/tilesets/secondary/mauville/metatile_attributes.bin"

	.align 1
gMetatiles_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/metatiles.bin"

	.align 1
gMetatileAttributes_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/metatile_attributes.bin"

	.align 1
gMetatiles_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/metatiles.bin"

	.align 1
gMetatileAttributes_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/metatile_attributes.bin"

	.align 1
gMetatiles_Fortree::
	.incbin "data/tilesets/secondary/fortree/metatiles.bin"

	.align 1
gMetatileAttributes_Fortree::
	.incbin "data/tilesets/secondary/fortree/metatile_attributes.bin"

	.align 1
gMetatiles_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/metatiles.bin"

	.align 1
gMetatileAttributes_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/metatile_attributes.bin"

	.align 1
gMetatiles_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/metatiles.bin"

	.align 1
gMetatileAttributes_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/metatile_attributes.bin"

	.align 1
gMetatiles_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/metatiles.bin"

	.align 1
gMetatileAttributes_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/metatile_attributes.bin"

	.align 1
gMetatiles_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/metatiles.bin"

	.align 1
gMetatileAttributes_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/metatile_attributes.bin"

	.align 1
gMetatiles_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/metatiles.bin"

	.align 1
gMetatileAttributes_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatile_attributes.bin"

	.align 1
gMetatiles_InsideBuilding::
	.incbin "data/tilesets/primary/building/metatiles.bin"

	.align 1
gMetatileAttributes_InsideBuilding::
	.incbin "data/tilesets/primary/building/metatile_attributes.bin"

	.align 1
gMetatiles_Shop::
	.incbin "data/tilesets/secondary/shop/metatiles.bin"

	.align 1
gMetatileAttributes_Shop::
	.incbin "data/tilesets/secondary/shop/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatile_attributes.bin"

	.align 1
gMetatiles_Cave::
	.incbin "data/tilesets/secondary/cave/metatiles.bin"

	.align 1
gMetatileAttributes_Cave::
	.incbin "data/tilesets/secondary/cave/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/metatile_attributes.bin"

	.align 1
gMetatiles_Unused1::
	.incbin "data/tilesets/secondary/unused_1/metatiles.bin"

	.align 1
gMetatileAttributes_Unused1::
	.incbin "data/tilesets/secondary/unused_1/metatile_attributes.bin"

	.align 1
gMetatiles_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/metatiles.bin"

	.align 1
gMetatileAttributes_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/metatile_attributes.bin"

	.align 1
gMetatiles_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/metatiles.bin"

	.align 1
gMetatileAttributes_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/metatile_attributes.bin"

	.align 1
gMetatiles_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatiles.bin"

	.align 1
gMetatileAttributes_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatile_attributes.bin"

	.align 1
gMetatiles_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/metatiles.bin"

	.align 1
gMetatileAttributes_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/metatile_attributes.bin"

	.align 1
gMetatiles_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/metatiles.bin"

	.align 1
gMetatileAttributes_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/metatile_attributes.bin"

	.align 1
gMetatiles_Facility::
	.incbin "data/tilesets/secondary/facility/metatiles.bin"

	.align 1
gMetatileAttributes_Facility::
	.incbin "data/tilesets/secondary/facility/metatile_attributes.bin"

	.align 1
gMetatiles_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatiles.bin"

	.align 1
gMetatileAttributes_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatile_attributes.bin"

	.align 1
gMetatiles_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/metatiles.bin"

	.align 1
gMetatileAttributes_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/metatile_attributes.bin"

	.align 1
gMetatiles_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/metatiles.bin"

	.align 1
gMetatileAttributes_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/metatile_attributes.bin"

	.align 1
gMetatiles_Contest::
	.incbin "data/tilesets/secondary/contest/metatiles.bin"

	.align 1
gMetatileAttributes_Contest::
	.incbin "data/tilesets/secondary/contest/metatile_attributes.bin"

	.align 1
gMetatiles_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/metatiles.bin"

	.align 1
gMetatileAttributes_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/metatile_attributes.bin"

	.align 1
gMetatiles_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/metatiles.bin"

	.align 1
gMetatileAttributes_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/metatile_attributes.bin"

	.align 1
gMetatiles_Lab::
	.incbin "data/tilesets/secondary/lab/metatiles.bin"

	.align 1
gMetatileAttributes_Lab::
	.incbin "data/tilesets/secondary/lab/metatile_attributes.bin"

	.align 1
gMetatiles_Underwater::
	.incbin "data/tilesets/secondary/underwater/metatiles.bin"

	.align 1
gMetatileAttributes_Underwater::
	.incbin "data/tilesets/secondary/underwater/metatile_attributes.bin"

	.align 1
gMetatiles_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/metatiles.bin"

	.align 1
gMetatileAttributes_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/metatile_attributes.bin"

	.align 1
gMetatiles_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/metatile_attributes.bin"

	.align 1
gMetatiles_Unused2::
	.incbin "data/tilesets/secondary/unused_2/metatiles.bin"

	.align 1
gMetatileAttributes_Unused2::
	.incbin "data/tilesets/secondary/unused_2/metatile_attributes.bin"

	.align 1
gMetatiles_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/metatiles.bin"

	.align 1
gMetatileAttributes_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/metatile_attributes.bin"

	.align 1
gMetatiles_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/metatiles.bin"

	.align 1
gMetatileAttributes_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/metatile_attributes.bin"

	.align 1
gMetatiles_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/metatiles.bin"

	.align 1
gMetatileAttributes_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/metatile_attributes.bin"

	.align 1
gMetatiles_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/metatiles.bin"

	.align 1
gMetatileAttributes_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/metatile_attributes.bin"

	.align 1
gMetatiles_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/metatiles.bin"

	.align 1
gMetatileAttributes_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/metatile_attributes.bin"

	.align 1
gMetatiles_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/metatile_attributes.bin"

	.align 1
gMetatiles_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/metatiles.bin"

	.align 1
gMetatileAttributes_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/metatile_attributes.bin"

	.align 1
gMetatiles_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/metatiles.bin"

	.align 1
gMetatileAttributes_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/metatile_attributes.bin"

	.align 1
gMetatiles_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatiles.bin"

	.align 1
gMetatileAttributes_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatile_attributes.bin"

	.align 1
gMetatiles_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/metatiles.bin"

	.align 1
gMetatileAttributes_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/metatile_attributes.bin"

	.align 1
gMetatiles_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/metatiles.bin"

	.align 1
gMetatileAttributes_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/metatile_attributes.bin"

	.align 1
gMetatiles_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/metatiles.bin"

	.align 1
gMetatileAttributes_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/metatile_attributes.bin"

	.align 1
gMetatiles_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/metatiles.bin"

	.align 1
gMetatileAttributes_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/metatile_attributes.bin"

	.align 1
gMetatiles_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/metatiles.bin"

	.align 1
gMetatileAttributes_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/metatile_attributes.bin"

	.align 1
gMetatiles_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatile_attributes.bin"

	.align 1
gMetatiles_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatiles.bin"

	.align 1
gMetatileAttributes_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatile_attributes.bin"

	.align 1
gMetatiles_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/metatiles.bin"

	.align 1
gMetatileAttributes_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/metatile_attributes.bin"

	.align 1
gMetatiles_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatiles.bin"

	.align 1
gMetatileAttributes_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatile_attributes.bin"

	.align 1
gMetatiles_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/metatiles.bin"

	.align 1
gMetatileAttributes_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/metatile_attributes.bin"

	.align 1
gMetatiles_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/metatiles.bin"

	.align 1
gMetatileAttributes_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/metatile_attributes.bin"

	.align 1
gMetatiles_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/metatiles.bin"

	.align 1
gMetatileAttributes_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/metatile_attributes.bin"

// Kanto

	.align 1
gMetatiles_FRLG_General::
	.incbin "data/tilesets/primary/frlg_general/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_General::
	.incbin "data/tilesets/primary/frlg_general/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_Building::
	.incbin "data/tilesets/primary/frlg_building/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_Building::
	.incbin "data/tilesets/primary/frlg_building/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_PalletTown::
	.incbin "data/tilesets/secondary/frlg_pallet_town/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_PalletTown::
	.incbin "data/tilesets/secondary/frlg_pallet_town/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_ViridianCity::
	.incbin "data/tilesets/secondary/frlg_viridian_city/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_ViridianCity::
	.incbin "data/tilesets/secondary/frlg_viridian_city/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_PewterCity::
	.incbin "data/tilesets/secondary/frlg_pewter_city/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_PewterCity::
	.incbin "data/tilesets/secondary/frlg_pewter_city/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_CeruleanCity::
	.incbin "data/tilesets/secondary/frlg_cerulean_city/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_CeruleanCity::
	.incbin "data/tilesets/secondary/frlg_cerulean_city/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_LavenderTown::
	.incbin "data/tilesets/secondary/frlg_lavender_town/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_LavenderTown::
	.incbin "data/tilesets/secondary/frlg_lavender_town/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_VermilionCity::
	.incbin "data/tilesets/secondary/frlg_vermilion_city/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_VermilionCity::
	.incbin "data/tilesets/secondary/frlg_vermilion_city/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_CeladonCity::
	.incbin "data/tilesets/secondary/frlg_celadon_city/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_CeladonCity::
	.incbin "data/tilesets/secondary/frlg_celadon_city/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_FuchsiaCity::
	.incbin "data/tilesets/secondary/frlg_fuchsia_city/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_FuchsiaCity::
	.incbin "data/tilesets/secondary/frlg_fuchsia_city/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_CinnabarIsland::
	.incbin "data/tilesets/secondary/frlg_cinnabar_island/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_CinnabarIsland::
	.incbin "data/tilesets/secondary/frlg_cinnabar_island/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_IndigoPlateau::
	.incbin "data/tilesets/secondary/frlg_indigo_plateau/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_IndigoPlateau::
	.incbin "data/tilesets/secondary/frlg_indigo_plateau/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_SaffronCity::
	.incbin "data/tilesets/secondary/frlg_saffron_city/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_SaffronCity::
	.incbin "data/tilesets/secondary/frlg_saffron_city/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_PewterGym::
	.incbin "data/tilesets/secondary/frlg_pewter_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_PewterGym::
	.incbin "data/tilesets/secondary/frlg_pewter_gym/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_CeruleanGym::
	.incbin "data/tilesets/secondary/frlg_cerulean_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_CeruleanGym::
	.incbin "data/tilesets/secondary/frlg_cerulean_gym/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_VermilionGym::
	.incbin "data/tilesets/secondary/frlg_vermilion_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_VermilionGym::
	.incbin "data/tilesets/secondary/frlg_vermilion_gym/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_CeladonGym::
	.incbin "data/tilesets/secondary/frlg_celadon_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_CeladonGym::
	.incbin "data/tilesets/secondary/frlg_celadon_gym/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_FuchsiaGym::
	.incbin "data/tilesets/secondary/frlg_fuchsia_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_FuchsiaGym::
	.incbin "data/tilesets/secondary/frlg_fuchsia_gym/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_SaffronGym::
	.incbin "data/tilesets/secondary/frlg_saffron_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_SaffronGym::
	.incbin "data/tilesets/secondary/frlg_saffron_gym/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_CinnabarGym::
	.incbin "data/tilesets/secondary/frlg_cinnabar_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_CinnabarGym::
	.incbin "data/tilesets/secondary/frlg_cinnabar_gym/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_ViridianGym::
	.incbin "data/tilesets/secondary/frlg_viridian_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_ViridianGym::
	.incbin "data/tilesets/secondary/frlg_viridian_gym/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_Dummy1::
	.incbin "data/tilesets/secondary/frlg_dummy_1/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_Dummy1::
	.incbin "data/tilesets/secondary/frlg_dummy_1/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_HoennBuilding::
	.incbin "data/tilesets/secondary/frlg_hoenn_building/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_HoennBuilding::
	.incbin "data/tilesets/secondary/frlg_hoenn_building/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_BikeShop::
	.incbin "data/tilesets/secondary/frlg_bike_shop/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_BikeShop::
	.incbin "data/tilesets/secondary/frlg_bike_shop/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_Mart::
	.incbin "data/tilesets/secondary/frlg_mart/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_Mart::
	.incbin "data/tilesets/secondary/frlg_mart/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_PokemonCenter::
	.incbin "data/tilesets/secondary/frlg_pokemon_center/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_PokemonCenter::
	.incbin "data/tilesets/secondary/frlg_pokemon_center/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_GenericBuilding1::
	.incbin "data/tilesets/secondary/frlg_generic_building_1/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_GenericBuilding1::
	.incbin "data/tilesets/secondary/frlg_generic_building_1/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_Cave::
	.incbin "data/tilesets/secondary/frlg_cave/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_Cave::
	.incbin "data/tilesets/secondary/frlg_cave/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_GameCorner::
	.incbin "data/tilesets/secondary/frlg_game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_GameCorner::
	.incbin "data/tilesets/secondary/frlg_game_corner/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_Lab::
	.incbin "data/tilesets/secondary/frlg_lab/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_Lab::
	.incbin "data/tilesets/secondary/frlg_lab/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_SSAnne::
	.incbin "data/tilesets/secondary/frlg_ss_anne/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_SSAnne::
	.incbin "data/tilesets/secondary/frlg_ss_anne/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_Dummy2::
	.incbin "data/tilesets/secondary/frlg_dummy_2/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_Dummy2::
	.incbin "data/tilesets/secondary/frlg_dummy_2/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_ViridianForest::
	.incbin "data/tilesets/secondary/frlg_viridian_forest/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_ViridianForest::
	.incbin "data/tilesets/secondary/frlg_viridian_forest/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_UnusedGatehouse1::
	.incbin "data/tilesets/secondary/frlg_unused_gatehouse_1/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_UnusedGatehouse1::
	.incbin "data/tilesets/secondary/frlg_unused_gatehouse_1/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_RockTunnel::
	.incbin "data/tilesets/secondary/frlg_rock_tunnel/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_RockTunnel::
	.incbin "data/tilesets/secondary/frlg_rock_tunnel/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_DiglettsCave::
	.incbin "data/tilesets/secondary/frlg_digletts_cave/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_DiglettsCave::
	.incbin "data/tilesets/secondary/frlg_digletts_cave/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_SeafoamIslands::
	.incbin "data/tilesets/secondary/frlg_seafoam_islands/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_SeafoamIslands::
	.incbin "data/tilesets/secondary/frlg_seafoam_islands/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_UnusedGatehouse2::
	.incbin "data/tilesets/secondary/frlg_unused_gatehouse_2/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_UnusedGatehouse2::
	.incbin "data/tilesets/secondary/frlg_unused_gatehouse_2/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_CeruleanCave::
	.incbin "data/tilesets/secondary/frlg_cerulean_cave/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_CeruleanCave::
	.incbin "data/tilesets/secondary/frlg_cerulean_cave/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_DepartmentStore::
	.incbin "data/tilesets/secondary/frlg_department_store/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_DepartmentStore::
	.incbin "data/tilesets/secondary/frlg_department_store/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_GenericBuilding2::
	.incbin "data/tilesets/secondary/frlg_generic_building_2/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_GenericBuilding2::
	.incbin "data/tilesets/secondary/frlg_generic_building_2/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_PowerPlant::
	.incbin "data/tilesets/secondary/frlg_power_plant/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_PowerPlant::
	.incbin "data/tilesets/secondary/frlg_power_plant/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_SeaCottage::
	.incbin "data/tilesets/secondary/frlg_sea_cottage/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_SeaCottage::
	.incbin "data/tilesets/secondary/frlg_sea_cottage/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_SilphCo::
	.incbin "data/tilesets/secondary/frlg_silph_co/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_SilphCo::
	.incbin "data/tilesets/secondary/frlg_silph_co/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_UndergroundPath::
	.incbin "data/tilesets/secondary/frlg_underground_path/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_UndergroundPath::
	.incbin "data/tilesets/secondary/frlg_underground_path/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_PokemonTower::
	.incbin "data/tilesets/secondary/frlg_pokemon_tower/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_PokemonTower::
	.incbin "data/tilesets/secondary/frlg_pokemon_tower/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_SafariZoneBuilding::
	.incbin "data/tilesets/secondary/frlg_safari_zone_building/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_SafariZoneBuilding::
	.incbin "data/tilesets/secondary/frlg_safari_zone_building/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_PokemonMansion::
	.incbin "data/tilesets/secondary/frlg_pokemon_mansion/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_PokemonMansion::
	.incbin "data/tilesets/secondary/frlg_pokemon_mansion/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_Museum::
	.incbin "data/tilesets/secondary/frlg_museum/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_Museum::
	.incbin "data/tilesets/secondary/frlg_museum/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_CableClub::
	.incbin "data/tilesets/secondary/frlg_cable_club/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_CableClub::
	.incbin "data/tilesets/secondary/frlg_cable_club/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_RestaurantHotel::
	.incbin "data/tilesets/secondary/frlg_restaurant_hotel/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_RestaurantHotel::
	.incbin "data/tilesets/secondary/frlg_restaurant_hotel/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_School::
	.incbin "data/tilesets/secondary/frlg_school/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_School::
	.incbin "data/tilesets/secondary/frlg_school/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_FanClubDaycare::
	.incbin "data/tilesets/secondary/frlg_fan_club_daycare/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_FanClubDaycare::
	.incbin "data/tilesets/secondary/frlg_fan_club_daycare/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_Condominiums::
	.incbin "data/tilesets/secondary/frlg_condominiums/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_Condominiums::
	.incbin "data/tilesets/secondary/frlg_condominiums/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_BurgledHouse::
	.incbin "data/tilesets/secondary/frlg_burgled_house/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_BurgledHouse::
	.incbin "data/tilesets/secondary/frlg_burgled_house/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_Dummy3::
	.incbin "data/tilesets/secondary/frlg_dummy_3/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_Dummy3::
	.incbin "data/tilesets/secondary/frlg_dummy_3/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_Dummy4::
	.incbin "data/tilesets/secondary/frlg_dummy_4/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_Dummy4::
	.incbin "data/tilesets/secondary/frlg_dummy_4/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_MtEmber::
	.incbin "data/tilesets/secondary/frlg_mt_ember/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_MtEmber::
	.incbin "data/tilesets/secondary/frlg_mt_ember/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_BerryForest::
	.incbin "data/tilesets/secondary/frlg_berry_forest/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_BerryForest::
	.incbin "data/tilesets/secondary/frlg_berry_forest/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_NavelRock::
	.incbin "data/tilesets/secondary/frlg_navel_rock/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_NavelRock::
	.incbin "data/tilesets/secondary/frlg_navel_rock/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_TanobyRuins::
	.incbin "data/tilesets/secondary/frlg_tanoby_ruins/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_TanobyRuins::
	.incbin "data/tilesets/secondary/frlg_tanoby_ruins/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_SeviiIslands123::
	.incbin "data/tilesets/secondary/frlg_sevii_islands_123/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_SeviiIslands123::
	.incbin "data/tilesets/secondary/frlg_sevii_islands_123/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_SeviiIslands45::
	.incbin "data/tilesets/secondary/frlg_sevii_islands_45/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_SeviiIslands45::
	.incbin "data/tilesets/secondary/frlg_sevii_islands_45/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_SeviiIslands67::
	.incbin "data/tilesets/secondary/frlg_sevii_islands_67/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_SeviiIslands67::
	.incbin "data/tilesets/secondary/frlg_sevii_islands_67/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_TrainerTower::
	.incbin "data/tilesets/secondary/frlg_trainer_tower/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_TrainerTower::
	.incbin "data/tilesets/secondary/frlg_trainer_tower/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_IslandHarbor::
	.incbin "data/tilesets/secondary/frlg_island_harbor/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_IslandHarbor::
	.incbin "data/tilesets/secondary/frlg_island_harbor/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_PokemonLeague::
	.incbin "data/tilesets/secondary/frlg_pokemon_league/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_PokemonLeague::
	.incbin "data/tilesets/secondary/frlg_pokemon_league/metatile_attributes.bin"

	.align 1
gMetatiles_FRLG_HallOfFame::
	.incbin "data/tilesets/secondary/frlg_hall_of_fame/metatiles.bin"

	.align 1
gMetatileAttributes_FRLG_HallOfFame::
	.incbin "data/tilesets/secondary/frlg_hall_of_fame/metatile_attributes.bin"
